### ISSUE TITLE
Creating SalesReceipt (& SalesItemLineDetail).

### ISSUE THREAD

**Issue by amxn** [ruckus/quickbooks-ruby#108]
I've been trying to create a SalesReceipt unsuccessfully. I've looked at the spec examples, but I keep running into a few errors.
1. undefined method `each' for #<Quickbooks::Model::Line:0x007fac35488558> if I add`Model::Line` as given in the specs.
2. I get various different errors if I opt for Model::SalesItemLineDetail, such as the one above (with a different model name),  or this undefined method `to_xml` for "user@email.com":String`

**Comment by chibuezeayogu** [comment]
Hi @bhaity, Please how do a create a sales receipt for an invoice. Like attach an invoice Id to a sales.
```
salesreceipt = Quickbooks::Model::SalesReceipt.new({
  customer_id: 3, 
  placed_on: Date.civil(2013, 11, 20), 
  payment_ref_number: "111", #optional payment reference number/string - e.g. stripe token
  deposit_to_account_id: 53, #The ID of the Account entity you want the SalesReciept to be deposited to
  payment_method_id: 5 #The ID of the PaymentMethod entity you want to be used for this transaction
}) 




Say we do something like get the invoice id/ids the add it to the sales receipt 
salesreceipt.invoices << [invoice_1, invoice_2, ...]
```

**Comment by Bilal14100** [comment]
> Hi @bhaity, Please how do a create a sales receipt for an invoice. Like attach an invoice Id to a sales.
> 
> ```
> salesreceipt = Quickbooks::Model::SalesReceipt.new({
>   customer_id: 3, 
>   placed_on: Date.civil(2013, 11, 20), 
>   payment_ref_number: "111", #optional payment reference number/string - e.g. stripe token
>   deposit_to_account_id: 53, #The ID of the Account entity you want the SalesReciept to be deposited to
>   payment_method_id: 5 #The ID of the PaymentMethod entity you want to be used for this transaction
> }) 
> 
> 
> 
> 
> Say we do something like get the invoice(s) add it to the sales receipt 
> salesreceipt.invoices << [invoice_1, invoice_2, ...]
> ```

Have you create the sales receipt for an invoice? Please let me know how you do that.
