### ISSUE TITLE
Can't access Bill line item line_num

### ISSUE THREAD

**Issue by blythburgh** [ruckus/quickbooks-ruby#130]
New to Quickbooks and API-ing it Making good headway with your gem (big Tx) but can't seem to retrieve the line number of bill lines - I can do this for invoices no problem, and I can get various other attributes of the bill line e.g. description.

Still checking my code and not a confident enough developer to be sure but think there may be an issue.

Note. as part of my troubleshoot I checked the intuit API to make sure attributes were mapped OK - it is there. However, I used the API explorer on the Intuit dev site to query a test bill and test invoice - the line numbers do get returned for the invoice but not the bill. Both test records were created in QuickBooks and appear to have line numbers. Is this an Intuit problem?

**Comment by minimul** [comment]
Closing. Check with Intuit to see if QBO-36643 gets resolved.
