### ISSUE TITLE
Sparse update and inactivate name list entities with batch operation

### ISSUE THREAD

**Issue by arthurchui** [ruckus/quickbooks-ruby#152]
There are 2 related issues:
1. The interface of `BatchRequest#add` does not take options (e.g. sparse). Changing that seems non-trivial. 
2. Similar to `Customer#delete`, the batch operation should be smart enough to inactivate a Name List Entity instead of deleting it. When the operation is set to "delete", `BatchRequest#add` can covert the operation to "update" and set `active = false` as a sparse update.

**Comment by drewish** [comment]
I think #2 can be ignored at this point. It looks like many of the services are implementing delete as a soft delete:
```rb
      def delete(item)
        item.active = false
        update(item, :sparse => true)
      end
```
https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/service/item.rb#L5-L8

But I'd love to see what it would take to allow batches of sparse updates. I'm not sure if the XML and JSON APIs differ that much but in the QBO docs they make it look like it's just adding an attribute:
```json
    { 
        "bId": "bid3",
        "operation": "update",
        "SalesReceipt": {
               "domain": "QBO",
               "sparse": true,
               "Id": "11",
               "SyncToken": "0",
               "PrivateNote":"A private note."       
          }
    },
```
https://developer.intuit.com/docs/api/accounting/batch

I'm curious if you'd consider allowing folks to just set the attribute and take responsibility for only using it on objects that support it.

**Comment by minimul** [comment]
I find that I am using batching all the time in my consulting so it is probably worth the investment on a PR.
