### ISSUE TITLE
During invoice generation in sandbox account getting error  "Subscription for company has lapsed or Invalid destination URL is used. Sandbox company works with Sandbox URL and Production company works with Production URL.; errorCode=007001; statusCode=400:efoodsinc"

### ISSUE THREAD

**Issue by ahmedanees** [ruckus/quickbooks-ruby#206]
Hello ,
 I am trying to generate an invoice using your gem 

Gem File:
            gem 'quickbooks-ruby'

Initializers file
 quickbooks_ruby.rb

QB_KEY = "qyprdcwytMQ53evwGa0ILQEEYDn9Em"
QB_SECRET = "lFc1L1Q5Xi1durWtGyBSwyG3gYfPTD3w1HxPGcrP"

$qb_oauth_consumer = OAuth::Consumer.new(QB_KEY, QB_SECRET, {
   :site                 => "https://oauth.intuit.com",
   :request_token_path   => "/oauth/v1/get_request_token",
   :authorize_url        => "https://appcenter.intuit.com/Connect/Begin",
   :access_token_path    => "/oauth/v1/get_access_token"
})

Error message is :
message=Subscription for company has lapsed or Invalid destination URL is used. Sandbox company works with Sandbox URL and Production company works with Production URL.; errorCode=007001; statusCode=400:efoodsinc

Test Invoice generation code for testing 

invoice = Quickbooks::Model::Invoice.new
   invoice.customer_id = 58
   invoice.txn_date = Date.civil(2013, 11, 20)
   invoice.doc_number = "1001" # my custom Invoice # - can leave blank to have Intuit auto-generate it

   line_item = Quickbooks::Model::InvoiceLineItem.new
   line_item.amount = 50
   line_item.description = "Plush Baby Doll"
   line_item.sales_item! do |detail|
     detail.unit_price = 50
     detail.quantity = 1
     detail.item_id = 500 # Item ID here
   end

   invoice.line_items << line_item

  service = Quickbooks::Service::Invoice.new
  service.company_id = "58"
  service.access_token = access_token
  #created_invoice = service.create(invoice)

Detail of Invoice Object 

--- !ruby/object:Quickbooks::Model::Invoice
line_items:
- !ruby/object:Quickbooks::Model::InvoiceLineItem
  amount: 50
  description: Plush Baby Doll
  detail_type: SalesItemLineDetail
  sales_line_item_detail: !ruby/object:Quickbooks::Model::SalesItemLineDetail
    unit_price: 50
    quantity: 1
    item_ref: !ruby/object:Quickbooks::Model::BaseReference
      value: 500
customer_ref: !ruby/object:Quickbooks::Model::BaseReference
  value: 58
txn_date: 2013-11-20
doc_number: '1001'

When i try to create invoice against service object code below

       service.create(invoice)

Error message is :
message=Subscription for company has lapsed or Invalid destination URL is used. Sandbox company works with Sandbox URL and Production company works with Production URL.; errorCode=007001; statusCode=400:efoodsinc

**Comment by minimul** [comment]
You need:
```
Quickbooks.sandbox_mode = true
```

in your initializer file.

See more here: http://minimul.com/connect-rails-and-quickbooks-online-via-a-sandbox.html

**Comment by ruckus** [comment]
> Quickbooks.sandbox_mode = true

**Comment by ahmedanees** [comment]
Hello Ruckus ,
Thanks for your response i had tried this in the file "Initializers" file

quickbooks_ruby.rb

QB_KEY = "qyprdcwytMQ53evwGa0ILQEEYDn9Em"
QB_SECRET = "lFc1L1Q5Xi1durWtGyBSwyG3gYfPTD3w1HxPGcrP"
 Quickbooks.sandbox_mode = true 

But the results  remains the same, Please tell me if there is any thing wrong thanks

**Comment by minimul** [comment]
Check your gem version.

**Comment by ahmedanees** [comment]
Here it my gem file spec
source 'https://rubygems.org'
gem 'rails', '3.2.11'
gem 'mysql2'
.....
......
gem 'quickbooks-ruby'

**Comment by minimul** [comment]
Are you restarting the Rails server on changes to the initializers file?

**Comment by ahmedanees** [comment]
Yes i had tried to restart the Rails server many time but no luck:(

**Comment by minimul** [comment]
Install the HttpLogger
Open up a Rails console and do this:
>> HttpLogger.log_headers = true
>> HttpLogger.logger = Logger.new(STDOUT)

Now try your invoice create and see if you spot anything strange like no sandbox url.

**Comment by ahmedanees** [comment]
Thanks minimul,
                   Let me try this

**Comment by ahmedanees** [comment]
Here are the response 

** [out :: dev.com] HTTP POST (565.54ms)   https://sandbox-quickbooks.api.intuit.com:443/v3/company/58/invoice
 ** [out :: dev.com] Request body   <?xml version="1.0" encoding="utf-8"?>
 ** [out :: dev.com] <Invoice xmlns="http://schema.intuit.com/finance/v3" sparse="false">
 ** [out :: dev.com] <DocNumber>1001</DocNumber>
 ** [out :: dev.com] <TxnDate>2013-11-20</TxnDate>
 ** [out :: dev.com] <Line>
 ** [out :: dev.com] <Description>Plush Baby Doll</Description>
 ** [out :: dev.com] <Amount>50.0</Amount>
 ** [out :: dev.com] <DetailType>SalesItemLineDetail</DetailType>
 ** [out :: dev.com] <SalesItemLineDetail>
 ** [out :: dev.com] <ItemRef>500</ItemRef>
 ** [out :: dev.com] <UnitPrice>50.0</UnitPrice>
 ** [out :: dev.com] <Qty>1.0</Qty>
 ** [out :: dev.com] </SalesItemLineDetail>
 ** [out :: dev.com] </Line>
 ** [out :: dev.com] <CustomerRef>58</CustomerRef>
 ** [out :: dev.com] </Invoice>
 ** [out :: dev.com] HTTP request header   Content-Type: application/xml
 ** [out :: dev.com] HTTP request header   Accept: application/xml
 ** [out :: dev.com] HTTP request header   Accept-Encoding: gzip, deflate
 ** [out :: dev.com] HTTP request header   User-Agent: OAuth gem v0.4.7
 ** [out :: dev.com] HTTP request header   Content-Length: 442
 ** [out :: dev.com] HTTP request header   Authorization: OAuth oauth_body_hash="KP9TrJ43OnNnaSIEcvdMcW90S54%3D", oauth_consumer_key="qyprdygiRYgHmpiTRi7BnpwfGFPwTh", oauth_nonce="aHpLdpWm3r19TXcAEwpNCXsfQaJKAFbG7jNfs82kk", oauth_signature="kny%2FoPqA3HQ6Tz%2B5O82SYOzxGjI%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1421155902", oauth_token="qyprdUgavGUAHPAUQQfDrR9Cq4ShqcSlFTyo3aGwo5zC0oub", oauth_version="1.0"
 ** [out :: dev.com] HTTP request header   Connection: close
 ** [out :: dev.com] HTTP request header   Host: sandbox-quickbooks.api.intuit.com
 ** [out :: dev.com] Response status   Net::HTTPBadRequest (400)
 ** [out :: dev.com] HTTP response header   Date: Tue, 13 Jan 2015 13:30:27 GMT
 ** [out :: dev.com] HTTP response header   Content-Type: application/xml;charset=ISO-8859-1
 ** [out :: dev.com] HTTP response header   Intuit_tid: gw-aac5a01d-fac0-4392-a3dc-c0c0d131547a
 ** [out :: dev.com] HTTP response header   Content-Length: 479
 ** [out :: dev.com] HTTP response header   Connection: close
 ** [out :: dev.com] Response body   
 ** [out :: dev.com] <IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2015-01-13T13:30:27.695Z" requestId="a0ee251fefa746b0973f5c8fc176d066">
 ** [out :: dev.com] <Fault type="VALIDATION">
 ** [out :: dev.com] <Error code="7001">
 ** [out :: dev.com] <Message>message=Subscription for company has lapsed or Invalid destination URL is used. Sandbox company works with Sandbox URL and Production company works with Production URL.; errorCode=007001; statusCode=400</Message>
 ** [out :: dev.com] </Error>

**Comment by ahmedanees** [comment]
Also FYI
My last conversation with quick books guys they suggest me that url request should be look like 

https://sandbox-api.intuit.com/v3/company/1315187170/invoice
But in our logs 
https://sandbox-quickbooks.api.intuit.com:443/v3/company/58/invoice

Thanks

**Comment by ahmedanees** [comment]
Please guide 
Here is the response from Quick-book Guys , 

"https://sandbox-quickbooks.api.intuit.com/v3/company/<companyID>/invoice is the correct full url.
You need to send the companyid/realmid which you get from oauth in the above url." 


But in file https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/service/base_service.rb

 @base_uri = "https://#{domain}/v3/company" 


===Code ===
 BASE_DOMAIN = 'quickbooks.api.intuit.com'
      SANDBOX_DOMAIN = 'sandbox-quickbooks.api.intuit.com'

      def initialize(attributes = {})
        domain = Quickbooks.sandbox_mode ? SANDBOX_DOMAIN : BASE_DOMAIN
        @base_uri = "https://#{domain}/v3/company"
        attributes.each {|key, value| public_send("#{key}=", value) }
      end
===End Code ===

**Comment by minimul** [comment]
The problem is how you are setting your company_id e.g.
```
   service = Quickbooks::Service::Invoice.new
   service.company_id = "58"
   service.access_token = access_token
   #created_invoice = service.create(invoice)
```
58 is not a proper company id. You can get the proper company id from the OAuth callback.
See my tutorial parts 1 and 2. In part http://minimul.com/integrating-rails-and-quickbooks-online-via-the-version-3-api-part-2.html pay attention to the `set_qb_service` method.

**Comment by ahmedanees** [comment]
minimul 
Thanks  a lot  that help me to resolve the problem

**Comment by sachin-7777** [comment]
Hi minimul,
Subscription for company has lapsed or Invalid destination URL is used. Sandbox company works with Sandbox URL and Production company works with Production URL.; errorCode=007001; statusCode=400",
In node.js i tried through Rest API as well as using module but couldnt do in right way,how to pass oauth parameter in both type of scenario
