### ISSUE TITLE
token_rejected when trying to authorize sandbox

### ISSUE THREAD

**Issue by peter-umb** [ruckus/quickbooks-ruby#208]
After clicking the 'Connect to Quickbooks' button on my webpage it opens a new window and I click authorize. Then the page bombs out with(I changed the params to blah):
OAuth::Problem in VendorsController#oauth_callback
token_rejected
app/controllers/vendors_controller.rb:92:in `oauth_callback'

{"oauth_token"=>"blah",
 "oauth_verifier"=>"blah",
 "realmId"=>"blah",
 "dataSource"=>"QBO"}

#vendors_controller.rb

#vendors_controller.rb
  def oauth_callback
    at = session[:qb_request_token].get_access_token(:oauth_verifier => params[:oauth_verifier])
    session[:token] = at.token
    session[:secret] = at.secret
    session[:realm_id] = params['realmId']
    redirect_to 'quickbooks/oauth_callback', notice: "Your QuickBooks account has been successfully linked."
 end

**Comment by ruckus** [comment]
What does your `authenticate` method look like in the (assuming) same controller?

**Comment by n8armstrong** [comment]
In case it helps, I just switched to sandbox and was able to authorize this morning without any changes to my code.

**Comment by peter-umb** [comment]
I figured it out. I was not storeing the key properly.
