### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ahmedanees** [ruckus/quickbooks-ruby#211]
Can you please guide how can i add address and phone number for customer write now it give me some error

**Comment by ahmedanees** [comment]
Got answer

phone1 = Quickbooks::Model::TelephoneNumber.new
phone1.free_form_number = "97335530394"
customer.mobile_phone =   phone1

Thanks

**Comment by ruckus** [comment]
Yep you got it! Telephones and Addresses are top-level objects so must be instantiated and configured directly. 

I've added some notes to the README about these types.

https://github.com/ruckus/quickbooks-ruby/blob/master/README.md#telephone-numbers

Thanks for the heads up.

**Comment by ahmedanees** [comment]
Thanks ruckus :)
