### ISSUE TITLE
Gitter room

### ISSUE THREAD

**Issue by jimmybaker** [ruckus/quickbooks-ruby#212]
Can we start a gitter chat room for this repo? I can't create one for some reason.

**Comment by minimul** [comment]
+1

**Comment by ruckus** [comment]
Ok, I went to the Gitter site, authorized my GH account and seemingly created a room for this repo. But:

![dog-no-idea](https://cloud.githubusercontent.com/assets/320/5979021/f1a04622-a858-11e4-95e6-8834d76f8b02.jpg)

**Comment by jimmybaker** [comment]
@ruckus - Can you post a link to the gitter room?

**Comment by jimmybaker** [comment]
Never mind. I found it. Pull request sent.
