### ISSUE TITLE
Inventory Asset

### ISSUE THREAD

**Issue by jimmybaker** [ruckus/quickbooks-ruby#213]
I get an error when trying to set the inventory related fields for an item. What am I missing here?

```
def to_quickbooks(qbo=::Quickbooks::Model::Item.new)
    qbo.name = name
    qbo.type = 'Inventory'
    qbo.asset_account_ref = 'Inventory Asset'
    qbo.description = description
    qbo.purchase_cost = cost
    qbo.track_quantity_on_hand = true
    qbo.quantity_on_hand = 123
    today = Time.now
    qbo.inv_start_date = Date.civil(today.year, today.month, today.day)
    qbo.taxable = true
    qbo
  end
```

The error I'm getting:

```
NoMethodError: undefined method `to_xml' for "Inventory Asset":String
```

So apparently I'm setting the asset_account_ref incorrectly. How do I do this properly?

**Comment by jimmybaker** [comment]
I found my way around this:

```
def to_quickbooks(qbo=::Quickbooks::Model::Item.new)
    qbo.name = name
    qbo.type = 'Inventory'

    inv_asset_account = ::Quickbooks::Model::BaseReference.new(81)
    inv_asset_account.name = "Inventory Asset"
    qbo.asset_account_ref = inv_asset_account

    expense_account = ::Quickbooks::Model::BaseReference.new(80)
    expense_account.name = "Cost of Goods Sold"
    qbo.expense_account_ref = expense_account

    qbo.description = description
    qbo.purchase_cost = cost
    qbo.track_quantity_on_hand = true
    qbo.quantity_on_hand = 123
    today = Time.now
    qbo.inv_start_date = Date.civil(today.year, today.month, today.day)
    qbo.taxable = true
    qbo
  end
```

The new error reads:
```
Invalid account type: For an inventory product, the income account must have Account Type: 'Income' and Detail Type: 'Sales of Product Income.'
```

Still working through this but any suggestions are appreciated.

**Comment by jimmybaker** [comment]
Got it working with:

```
def to_quickbooks(qbo=::Quickbooks::Model::Item.new)
    qbo.name = name
    qbo.type = 'Inventory'

    inv_asset_account = ::Quickbooks::Model::BaseReference.new(81)
    inv_asset_account.name = "Inventory Asset"
    qbo.asset_account_ref = inv_asset_account

    expense_account = ::Quickbooks::Model::BaseReference.new(80)
    expense_account.name = "Cost of Goods Sold"
    qbo.expense_account_ref = expense_account

    income_account = ::Quickbooks::Model::BaseReference.new(79)
    income_account.name = "Sales of Product Income"
    qbo.income_account_ref = income_account

    qbo.description = description
    qbo.purchase_cost = cost
    qbo.track_quantity_on_hand = true
    qbo.quantity_on_hand = 123
    today = Time.now
    qbo.inv_start_date = Date.civil(today.year, today.month, today.day)
    qbo.taxable = true
    qbo
  end
```

Are these various account refs available to all Quickbooks online accounts? I would rather not have my users map these products in my app as well as in quickbooks. Does this library provide a way to create these different types?

Thanks a lot for all the work you put into this. It's really great!

**Comment by ruckus** [comment]
Hi Jimmy,

Firstly, you can simplify your code a little by using the `_id` setters, so lines like:

```ruby
income_account = ::Quickbooks::Model::BaseReference.new(79)
income_account.name = "Sales of Product Income"
qbo.income_account_ref = income_account
```

Can be replaced with:

```ruby
qbo.income_account_id = 79
```

Behind the scenes the setter runs the same `BaseReference` stuff like what you're doing, but just makes it simpler for you. In this case the ID is set to 79 which is all that QBO needs. The string `name` is purely for human descriptive purposes (?). Anyways, its not needed.

That being said, I think to answer your question:

> I would rather not have my users map these products in my app as well as in quickbooks. 

Since you do need to find IDs to this library it implies you have them on hand. So yes they will need to be mapped in your app. 

> Does this library provide a way to create these different types?

Not sure what you mean. Can you please elaborate?

Thanks!

**Comment by jimmybaker** [comment]
Hi Cody. Thanks for the reply. I found the answer to my question about creating the types. I was referring to cost of goods sold account types. I have created that model on my end and they sync to Quickbooks now too.

I'm working on a SalesReceipt now and I'm trying to get it to stop creating new line items each time I update a sales receipt that already exists in quickbooks. Is that the purpose of the item_id in the line_item detail?

**Comment by ruckus** [comment]
> I'm working on a SalesReceipt now and I'm trying to get it to stop creating new line items each time I update a sales receipt that already exists in quickbooks.

Sounds like you want to do a `sparse` update. From the intuit docs:

> Sparse updating provides the ability to update a subset of properties for a given object; only elements specified in the request are updated. Missing elements are left untouched. The ID of the object to update is specified in the request body.​

Try this:

```ruby
sales_receipt_service.update(an_existing_sales_receipt, :sparse => true)
```

**Comment by jimmybaker** [comment]
I haven't tried this yet but I think it will still give me duplicate line items. I'm not sure how it decides when a line item is new. Is it by the id? If so, would I need to store the id of the line item on my sales order item? I was hoping i could assign my active record id to the item so it would know that it already exists.

**Comment by ruckus** [comment]
Yeah I havent had to update invoices yet either. I'd love for you to guinea pig it and let me know your findings. I'll update the docs as needed. Thank you!

**Comment by jimmybaker** [comment]
According to their documentation, the id of a line item must be present for an update to occur. If no id is present then it is considered a create action. How can I see what is being sent to Quickbooks?

It would be awesome if I could just assign the id before it gets sent.

**Comment by jimmybaker** [comment]
Here is the documentation that I was referring to:

http://cl.ly/image/0B1i0X1t3m37

**Comment by ruckus** [comment]
You can enable logging to see the request / response:

https://github.com/ruckus/quickbooks-ruby#logging

You can also run an HTTP Proxy on your local machine and have the HTTP library point to it, ala:

```ruby
$qb = OAuth::Consumer.new($consumer_key, $consumer_secret, {
    :site                 => "https://oauth.intuit.com",
    :request_token_path   => "/oauth/v1/get_request_token",
    :authorize_path       => "/oauth/v1/get_access_token",
    :access_token_path    => "/oauth/v1/get_access_token",
    :proxy => "http://127.0.0.1:8888"
})
```

Notice that last line. This is the tactic I use, with Charles Proxy:

http://www.charlesproxy.com/

But there are free / open-sources proxies out there.

Try this route:

1) Fetch the Invoice you want to update.
2) Iterate through its line-items array and delete the ones you dont want to update
3) You're now left with what you want to update: make changes to that line-item(s) as needed.
4) Save the invoice - which should be pre-populated with all its IDs + your final changes.

**Comment by minimul** [comment]
Personally, I use the HttpLogger gem if I need to see absolutely all communication, which is rare, as ``Quickbooks.log = true``` is usually enough.

Put this in the quickbooks initializer file after putting HttpLogger in the gemfile
```
HttpLogger.log_headers = true
HttpLogger.logger = Rails.logger
```

As for updating invoices send the full payload on an update. The latest line items take precedence. All previous line items are deleted with this approach. With a sparse update you need to figure out what has changed and this is a more complex and error prone endeavor. I have not found a need for sparse update yet in my consulting.
