### ISSUE TITLE
issue in creating invoice - undefined method `post' for "xxxxxxxxmy-access-tokenxxxxxxxx":String 

### ISSUE THREAD

**Issue by zeeshananis** [ruckus/quickbooks-ruby#215]
I am getting the error below while creating an invoice: 
Exactly after this line -> created_invoice = service.create(invoice)

undefined method `post' for "xxxxxxxxmy-access-tokenxxxxxxxx":String 

My code is as follows: 

user_data =    User.find_by_id(current_user.id)
 if !user_data.qb_access_token.blank? && !user_data.qb_access_secret.blank?
      access_token = user_data.qb_access_token
      access_secret=  user_data.qb_access_secret
      realm_id  = user_data.qb_company_id

      invoice = Quickbooks::Model::Invoice.new
      invoice.customer_id = 84 # Existing customer id
      invoice.txn_date = Date.civil(2015, 01, 28)
      invoice.doc_number = "1001" 

      line_item = Quickbooks::Model::InvoiceLineItem.new
      line_item.amount = 50
      line_item.description = "Plush Baby Doll"
      line_item.sales_item! do |detail|
        detail.unit_price = 50
        detail.quantity = 1
        detail.item_id = 38 # Existing Item ID 
      end
      
      invoice.line_items << line_item

      service = Quickbooks::Service::Invoice.new
      service.company_id = realm_id
      service.access_token = access_token
      created_invoice = service.create(invoice)
      
    end

**Comment by minimul** [comment]
Your service creation should look like this:
```
      oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, access_token, access_secret)
      service = Quickbooks::Service::Invoice.new
      service.access_token = oauth_client
      service.company_id = realm_id
```

**Comment by zeeshananis** [comment]
Thanks minimul for your reply,it was oauth_client which was confused with access_token in below line

service.access_token = access_token #oauth_client
 
as it was written in "Generating an Invoice" example 

service = Quickbooks::Service::Invoice.new
service.company_id = "123"
service.access_token = access_token
created_invoice = service.create(invoice)
puts created_invoice.id

I got it now, and it worked, Thanks again
