### ISSUE TITLE
How to add discount value in quickbooks

### ISSUE THREAD

**Issue by zeeshananis** [ruckus/quickbooks-ruby#216]
Hi, i am new to quickbooks-ruby
just going through the code by how we can add percent discount using the below code:

discount_line_item = Quickbooks::Model::InvoiceLineItem.new
discount_line_item.amount = 149
discount_line_item.discount_item! do |detail|
  detail.discount_percent = 10
  detail.percent_based = true
  detail.discount_account_id = 99
end
invoice.line_items << discount_line_item

but how can we add discount value in the transaction other than percent discount?

**Comment by bhaity** [comment]
you could add a line item with a negative amount ?

**Comment by zeeshananis** [comment]
![untitled](https://cloud.githubusercontent.com/assets/10771981/6038366/2d3cac7e-ac7e-11e4-8f3b-03d3e2700b42.png)

No bhaity, Please check the screenshot, i am talking about

**Comment by zeeshananis** [comment]
ok thanks, but what will i add in item id column

**Comment by minimul** [comment]
Like this:
```
discount_line_item = Quickbooks::Model::InvoiceLineItem.new
discount_line_item.amount = 149
discount_line_item.discount_item! do |detail|
  detail.discount_account_id = 99
end
invoice.line_items << discount_line_item
```

XML
```
      <Line>
        <Amount>149.00</Amount>
        <DetailType>DiscountLineDetail</DetailType>
        <DiscountLineDetail>
          <DiscountAccountRef>99</DiscountAccountRef>
        </DiscountLineDetail>
      </Line>
```

**Comment by zeeshananis** [comment]
Thanks minimul for your reply,i have a question here, as discount_account_id is optional as written by ruckus here 
https://github.com/ruckus/quickbooks-ruby/issues/70
so i leave it blank,which gives me below error message:
Required param missing, need to supply the required value for the API:
	Required parameter Line.DiscountLineDetail is missing in the request

**Comment by minimul** [comment]
Perhaps it is optional for percent-based discounts but not for value based. Try an account reference for discount_account_id. Should be an income account.

**Comment by zeeshananis** [comment]
Thanks, currently i am working on sandbox, what can i add here as accountid

**Comment by minimul** [comment]
Try 86

**Comment by zeeshananis** [comment]
i tried it but no luck, it gives this message
Invalid Customer:
	The customer you have specified has been deleted. You cannot create or edit a transaction with a deleted customer.

**Comment by ruckus** [comment]
Try it with an active Customer ID

**Comment by zeeshananis** [comment]
I have tried with an active customer id but without discount line item it worked, but when i add discount line item having discount_account_id with active customer id, it gives me below message:

Invalid Reference Id:
	Invalid Reference Id : Something you're trying to use has been deleted. Check the fields with accounts, customers, items, vendors or employees

Here is my invoice object:

{"line_items":[{"amount":"5.99","description":"Plush Baby Doll","detail_type":"SalesItemLineDetail","sales_line_item_detail":{"unit_price":"5.99","quantity":1,"item_ref":{"value":"36"}}},{"amount":1,"detail_type":"DiscountLineDetail","discount_line_detail":{"discount_account_ref":{"value":95}}}],"customer_ref":{"value":95},"txn_date":"2015-02-04","doc_number":""}

**Comment by minimul** [comment]
Try discount_account_id = 86 or go to the API explorer at https://developer.intuit.com and do a

```
SELECT * FROM Account
```
to find a valid income account.

**Comment by zeeshananis** [comment]
Thanks minimul for guidance, i found an active account by query and assigned to it and it worked

**Comment by gurmindersingh42** [comment]
Hi, i am new to quickbooks.
As mentioned above, we are using the the discount_account_id = 86 for the sandbox account. Does this id change when we shift the code on production mode?
Also these ids are different for different quickbook accounts?

**Comment by minimul** [comment]
Yes and Yes.

**Comment by faisalsahil** [comment]
discount_account_id is optional. Here is my code with discount value and its working fine.

discount_line_item = Quickbooks::Model::InvoiceLineItem.new
discount_line_item.amount = 70
discount_line_item.discount_item! do |detail|
    detail.percent_based = false
    # detail.discount_percent = 10.          // Its mandatory if percent_based  is true
    # detail.discount_account_id = 54.    // Optional
end
