### ISSUE TITLE
Send an attachment with quickbooks invoice

### ISSUE THREAD

**Issue by zeeshananis** [ruckus/quickbooks-ruby#217]
I was looking around is there any way to send an attachment with quickbooks invoice generation using this gem

**Comment by minimul** [comment]
There is no support yet for [Attachable](https://developer.intuit.com/docs/0025_quickbooksapi/0050_data_services/030_entity_services_reference/attachable), which is what is needed for this.

**Comment by zeeshananis** [comment]
I am generating a pdf invoice here in my system to email customers, so i need it as an attachment to send in quickbooks online for record purpose. Any way around for this?

**Comment by ruckus** [comment]
I've added a task to to implement Attachable. Seems like it should be pretty straight-forward to implement. Maybe I will get a chance in the next week or so.

https://github.com/ruckus/quickbooks-ruby/issues/218

**Comment by ruckus** [comment]
I took a stab at implementing the Attachable model/service:

https://github.com/ruckus/quickbooks-ruby/commit/f930d2251c3d3beadae0a4237da4d2efd652b2c4

What is not clear from the API documentation is how to upload a file. I can create and upload an Attachable like:

```ruby
attachable.file_name = "monkey.jpg"
attachable.note = "A note"
entity = Quickbooks::Model::EntityRef.new
entity.type = 'Customer'
entity.value = 3
attachable.attachable_ref = Quickbooks::Model::AttachableRef.new(entity)
service.create(attachable)
```

But its not clear how I can actually upload the contents of a file. I tried to reference a file handle:

```ruby
attachable.file_name = File.open("monkey.jpg")
```

But that doesnt work. The docs are poor in this regard.

**Comment by bretweinraub** [comment]
Seems to be a separate request to upload:

https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/attachments#/Uploading_files

Note you need the right mime type.

**Comment by minimul** [comment]
Yep, see https://github.com/ruckus/quickbooks-ruby/issues/218

**Comment by ruckus** [comment]
Going to merge in the `attachable` branch

**Comment by ruckus** [comment]
I've merged the `attachable` branch into master and updated the README with notes:

https://github.com/ruckus/quickbooks-ruby#attachments

Give it a try? I'll hold off on releasing an official gem until I can get more users to give it a try.
