### ISSUE TITLE
Implement Attachable

### ISSUE THREAD

**Issue by ruckus** [ruckus/quickbooks-ruby#218]
Implement `Attachable` entity.

https://developer.intuit.com/docs/0025_quickbooksapi/0050_data_services/030_entity_services_reference/attachable

**Comment by ruckus** [comment]
First stab at implementation:

https://github.com/ruckus/quickbooks-ruby/commit/f930d2251c3d3beadae0a4237da4d2efd652b2c4

**Comment by minimul** [comment]
Looks like the Upload endpoint needs to be used in conjunction.

See .NET code here: https://intuitdeveloper.lc.intuit.com/questions/1027130?_ans=1&_pos=8&_src=sapi&_tot=18&from=sapi&tags=

related: https://github.com/ruckus/quickbooks-ruby/tree/file-upload-prototype

**Comment by ruckus** [comment]
To me, its still not clear how to use the Attachable/Upload API. 

I had written the `file-upload-prototype` branch but it all it does is allow you to upload the actual file with no meta-data like Note, Tag, etc.

On the other hand, the Attachable API only seemingly provides the upload of the meta-data.

So the question is: how do you combine the two? If you create an `Attachable` model with all the meta-data attributes, is there a new attribute we need to create to set the `StringIO` / Upload object on? If so, what is it called?

I opened a Forum ticket:

https://intuitdeveloper.lc.intuit.com/questions/1090278-uploading-documents-via-attachable

But I'm not holding my breath on getting a response.

**Comment by minimul** [comment]
No, they are good on getting back.

**Comment by ruckus** [comment]
Ok, I think I got it. 

First stab is on the `attachable` branch:

https://github.com/ruckus/quickbooks-ruby/commit/bfc2b27082add501686c37485114125443e3b632

Usage:

```ruby
service = Quickbooks::Service::Upload.new
service.access_token = token
service.company_id = '12345'

meta = Quickbooks::Model::Attachable.new
meta.file_name = "monkey.jpg"
meta.note = "A note"
meta.content_type = "image/jpeg"
entity = Quickbooks::Model::EntityRef.new
entity.type = 'Customer'
entity.value = 3
meta.attachable_ref = Quickbooks::Model::AttachableRef.new(entity)

# args: 
#     local-path to file
#     file mime-type
#     (optional) instance of Quickbooks::Model::Attachable - metadata
attach = service.upload("tmp/monkey.jpg", "image/jpeg", meta)

puts attach.temp_download_uri
=> "https://intuit-qbo-prod-29.s3.amazonaws.com/12345%2Fattachments%2Fmonkey-1423760870606.jpg?Expires=1423761772&AWSAcc ... snip ..."
```

This will upload a physical file + meta-data. If you **only** have Metadata and no file, then you need to use the `Attachable` service:

```ruby
service = Quickbooks::Service::Attachable.new
service.create(meta)
```

Please bang on it and let me know your feedback.

**Comment by ruckus** [comment]
Oh yeah, this branch adds a new gem dependency `multipart-post` so dont forget to `bundle install` after you pull down the branch

**Comment by ruckus** [comment]
Merged into master

**Comment by railsruby0** [comment]
I am doing same steps and facing error: NoMethodError: undefined method `post_with_multipart' for "XXXXXX":String

**Comment by ruckus** [comment]
@railsruby0 you're not setting up your `token` correctly

Please reference this working example:

https://gist.github.com/ruckus/a8245437e809497d37ead9554c2e25b4

But specifically in your line:

```ruby
upload_service = Quickbooks::Service::Upload.new(:realm_id=> '123XXX', :access_token=> 'QTYXXXXX')
```
The value of `:access_token` is NOT a String but a fully-fledged instance of a `OAuth::AccessToken` object. See the above example

**Comment by railsruby0** [comment]
Hello Cody
It's working now😊
Thank you so much for help :)
