### ISSUE TITLE
custom field value not saving in qb

### ISSUE THREAD

**Issue by zeeshananis** [ruckus/quickbooks-ruby#219]
I am creating and saving custom field in invoice using the below code:

custom_field = Quickbooks::Model::CustomField.new
              custom_field.name = "LFI Invoice #"
              custom_field.type = "StringType"
              custom_field.string_value = "LFI12345678"
              invoice = Quickbooks::Model::Invoice.new
              invoice.custom_fields = [custom_field]

so before saving the invoice object json is as below while debugging:

{"line_items":[{"amount":"5.99","description":"Plush Baby Doll","detail_type":"SalesItemLineDetail","sales_line_item_detail":

{"unit_price":"5.99","quantity":1,"item_ref":{"value":"36"}}}],"custom_fields":[{"name":"LFI Invoice 

#","type":"StringType","string_value":"LFI123456"}],"customer_ref":{"value":"95"},"txn_date":"2015-02-05","doc_number":""}

but after invoice creation it gives me empty custom field,when i query invoice in API explorer, it gives me below json of custom field part:

"CustomField": [
          {
            "DefinitionId": "1",
            "Name": "LFI Invoice #",
           "Type": "StringType"
          }
        ],

Any suggestion what's the issue

**Comment by zeeshananis** [comment]
Hi ruckus or minimul. Any suggestion,you can guide?

**Comment by minimul** [comment]
You can't add a new custom field via the API. It must be done on QBO Company Preferences.
See attached.
![screen shot 2015-02-10 at 10 23 56 am](https://cloud.githubusercontent.com/assets/199862/6129829/21d64526-b10f-11e4-87cc-5539db1f8699.png)

You would need to add 'LFI Invoice #' in there. After that you would need to set the Definition Id, which would be 2
```
custom_field.id = 2
```

**Comment by zeeshananis** [comment]
Thanks minimul, it works, I got confused from this post https://github.com/ruckus/quickbooks-ruby/issues/64 and missed custom_field.id as it was not mentioned in script while saving the custom field 
![quickbooks_ruckus](https://cloud.githubusercontent.com/assets/10771981/6210536/8aedbc50-b5f2-11e4-903e-640569debf9c.png)
