### ISSUE TITLE
ItemRef required to create an invoice

### ISSUE THREAD

**Issue by bretweinraub** [ruckus/quickbooks-ruby#220]
This works via the API (https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Invoice)

    <Invoice xmlns="http://schema.intuit.com/finance/v3">
      <DocNumber>385</DocNumber>
      <TxnDate>2015-02-10 04:22:59 UTC</TxnDate>
      <Line>
    	<Amount>100</Amount>
        <DetailType>SalesItemLineDetail</DetailType>
        <SalesItemLineDetail>
          <ItemRef>1</ItemRef>
        </SalesItemLineDetail>
      </Line>
      <CustomerRef type="Customer">99</CustomerRef>
    </Invoice>

Note the use of ItemRef.  If I use the quickbooks-ruby API, I get something like this:

    <Invoice xmlns="http://schema.intuit.com/finance/v3" sparse="false">
      <Line>
    	<Amount>100</Amount>
    	<DetailType>SalesItemLineDetail</DetailType>
    	<SalesItemLineDetail>
    	  <Name>.......</Name>
    	  <Type>Inventory</Type>
    	  <IncomeAccountRef name="Services" type="Account">1</IncomeAccountRef>
    	</SalesItemLineDetail>
      </Line>
      <CustomerRef type="Customer">99</CustomerRef>
    </Invoice>

Which QBO hates and sends back an error like:

     <Fault type="ValidationFault"><Error code="2020" element="Line.SalesItemLineDetail">         <Message>Required param missing, need to supply the required value for the API</Message><Detail>Required parameter Line.SalesItemLineDetail is missing in the request</Detail></Error></Fault>

Using the API explorer, I can only seem to get an invoice created using the "ItemRef" model, although I can't use quickbooks-ruby to create it [although I will shortly attempt to hack same].

**Comment by bretweinraub** [comment]
now it gets really weird.  Since I don't understand the underguts of this gem, I hacked this into base_service.rb:

        if body.is_a? String and  match = body.match(/(.*?)(<SalesItemLineDetail>)(.*?)(<\/SalesItemLineDetail>)(.+)/m)
          internal = match[3]
          item_ref_s = internal.match(/>([0-9]+)</)
          item_ref = item_ref_s[1]
          body = "#{match[1]}#{match[2]}<ItemRef>#{item_ref}</ItemRef>#{match[4]}#{match[5]}"
          puts "--- Modified REQUEST --- \n\n#{body}\n\n"
        end

And this gives me a document that works correctly here:

https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Invoice

BUT it still fails here ... with the same error:

    <Fault type="ValidationFault"><Error code="2020" element="Line.SalesItemLineDetail"><Message>Required param missing, need to supply the required value for the API</Message><Detail>Required parameter Line.SalesItemLineDetail is missing in the request</Detail></Error></Fault>

You can't win for trying......

**Comment by bretweinraub** [comment]
Here are the original and modified docs.....

    --- REQUEST --- 
    
    <?xml version="1.0" encoding="utf-8"?>
    <Invoice xmlns="http://schema.intuit.com/finance/v3" sparse="false">
      <Line>
    	<Amount>1686.28109</Amount>
    	<DetailType>SalesItemLineDetail</DetailType>
    	<SalesItemLineDetail>
    	  <Type>Inventory</Type>
    	  <IncomeAccountRef name="Services" type="Account">1</IncomeAccountRef>
    	</SalesItemLineDetail>
      </Line>
      <CustomerRef type="Customer">99</CustomerRef>
    </Invoice>
    
    --- Modified REQUEST --- 
    
    <?xml version="1.0" encoding="utf-8"?>
    <Invoice xmlns="http://schema.intuit.com/finance/v3" sparse="false">
      <Line>
    	<Amount>1686.28109</Amount>
    	<DetailType>SalesItemLineDetail</DetailType>
    	<SalesItemLineDetail><ItemRef>1</ItemRef></SalesItemLineDetail>
      </Line>
      <CustomerRef type="Customer">99</CustomerRef>
    </Invoice>

**Comment by ruckus** [comment]
Did you have a look at the quick intro to creating an Invoice in the README:

https://github.com/ruckus/quickbooks-ruby#generating-an-invoice

Ultimately, you need to invoke a specific-line item detail to add to the line-itself. And then you can assign the Item ID (generating an `ItemRef` behind the scenes). 

So you're code should look like:

```ruby
line_item = Quickbooks::Model::InvoiceLineItem.new
line_item.amount = 1686.28
line_item.description = "Plush Baby Doll"
line_item.sales_item! do |detail|
  detail.unit_price = 1686.28 # change as necessary
  detail.quantity = 1 # change as necesary: note that unit_price * quantity must = amount
  detail.item_id = 1 # Item ID here
end
```

**Comment by bretweinraub** [comment]
i'll have a look next time i'm under the hood [at our next invoice run]

**Comment by bretweinraub** [comment]
Have you ever seen that before where something will work in the API explorer but fail via the API from the gem?

**Comment by ruckus** [comment]
To create an invoice line-item `ItemRef` is a required field.

> Have you ever seen that before where something will work in the API explorer but fail via the API from the gem?

I have in the past, with the v2 API, but not really with the v3 API. But funny enough I have yet to put this gem in production, so I haven't banged on it as much as others have, thereby finding potential issues.

**Comment by bretweinraub** [comment]
This formulation seems to be working; thanks.
