### ISSUE TITLE
How to add income account while creating an Item in quickbooks

### ISSUE THREAD

**Issue by gouravmodi** [ruckus/quickbooks-ruby#225]
I had to do something like this.

quickbook_product_type = Quickbooks::Model::Item.new
quickbook_product_type.income_account_ref = Quickbooks::Model::BaseReference.new(14)

Here id of 14 refers to Income account "Miscellaneous".

But this is not a nice way of assigning the income account as we cannot rely on id to fetch this as different quickbooks account may have different id for it.
So,please can you tell me a better solution for this

**Comment by minimul** [comment]
No easy solution. Reference IDs are going to be different on an account by account basis and you need to handle that. 
Yeah, it would be nice to refer to a reference by name but all references in v3 must be assigned via its numeric ID.
