### ISSUE TITLE
TaxServices - how to implement

### ISSUE THREAD

**Issue by lugoland** [ruckus/quickbooks-ruby#228]
I need to implement  TaxService , to be able to create taxCodes and associate them with taxAgencies, can some one guide me how to do this? would like to modify this gem to be able to do this.

**Comment by ruckus** [comment]
Thanks for your interest!

Have a look at the docs for `TaxService`: https://developer.intuit.com/docs/api/accounting#/taxservice

It looks like to be pretty straight-forward. Then you can copy any existing model / service classes and tailor them to have these fields and/or validations.

**Comment by lugoland** [comment]
Hi ruckus thanks for you prompt response, i was able to implement TaxAgency query but it looks like to "create" TaxService the api only accepts json. Is there an easy way to tell the gem to transmit in json instead of XML?

**Comment by ruckus** [comment]
Hmm interesting. Yeah it looks like XML is not supported for TaxService creation.

Unfortunately the whole library is built around XML, so using JSON for this request / response is not possible at the moment. We'll have to wait until Intuit supports XML for that endpoint.

Sorry!

**Comment by HeathNaylor** [comment]
Would it be a worthy undertaking to support JSON in this library, seems like a better option than just waiting for Iintuit to update their API. I need to push a specific amount of tax per transaction and TaxService seems to be the only way to do it.

**Comment by yul** [comment]
Not sure why this issue is closed, it is not fixed. Intuit didn't add XML support and can never add it at all, or even drop XML support in next API version. 
So currently there is no way to create tax codes manually to assign taxes to invoices?

**Comment by ruckus** [comment]
This library only reads/writes XML and according to the Intuit documentation for TaxService creation only supports JSON. Thus - as of now this library doesnt support creating TaxService

**Comment by minimul** [comment]
Update: TaxService is JSON is supported now.

**Comment by HeathNaylor** [comment]
This makes me happy.
