### ISSUE TITLE
Invalid account type used

### ISSUE THREAD

**Issue by tgirotto** [ruckus/quickbooks-ruby#229]
I am trying to create a purchase through the Purchase object, but having a pretty hard time figuring it out. Apparently, the syntax of my objects is correct (no errors); however, I am getting this error

    Invalid account type: You need to select a different type of account for this transaction.

When I set my order object to have the property

    account_ref  = Quickbooks::Model::BaseReference.new
    account_ref.value = '{some value here}'
    order.account_ref = account_ref

what should I input in as the account_ref.value field? 

Thank you for the support and, above all, for writing great code.

**Comment by ruckus** [comment]
You probably need to set the ID of the Account, not the value (the `Account` model doesn't even have a `value` property, so not sure where that is coming from?)

Check out the section in the docs for **Reference Setters**:

https://github.com/ruckus/quickbooks-ruby#reference-setters

Your code should look like:

```ruby
purchase = Quickbooks::Model::Purchase.new
purchase.account_id = 99 # ID your Account Object
... other stuff ...
```

In this case the `_id` setter is really just a convenience routine for doing:

```ruby
purchase = Quickbooks::Model::Purchase.new
account_ref = Quickbooks::Model::BaseReference.new(99) # Account ID
purchase.account_ref = account_ref
```

Give that a shot!

**Comment by tgirotto** [comment]
mm isn't Account just a BaseReference object? Which means that it has an id, a type and a value? However, changing the code as you said did improve the situation :) Thanks! 

The new error states that I cannot use 'Cash' as payment method, while in the Quickbooks Online API the example uses 'Cash'. Do you have any idea why?

**Comment by ruckus** [comment]
> isn't Account just a BaseReference object? Which means that it has an id, a type and a value? 

Yes you're right. I was being obtuse! Hah.

> The new error states that I cannot use 'Cash' as payment method, while in the Quickbooks Online API the example uses 'Cash'. Do you have any idea why?

Strange indeed. The docs do suggest a string value of `Cash` should work. Whats your full XML? Maybe there is some other attribute that is mucking it up?

**Comment by tgirotto** [comment]
mm i have read quite a bit about the problem, and apparently it is about the account type one has. quoting the docs:

    ReferenceType, required 
    Specifies the account reference. Check must specify bank account, CreditCard must specify credit      card account. 
    Validation Rules:Valid and Active Account Reference of an appropriate type.

**Comment by Craggar** [comment]
Just FYI, I found that when I was reading a list of accounts and wanted CC, it expected "Credit Card" rather than, as the documentation said, "CreditCard". I don't do any writing, only reading, so don't know if the same issue is present on a create.

**Comment by tgirotto** [comment]
Mm nope, I am using 'CreditCard', so that should be ok. However, the snipped posted in issue 232 helped :)
