### ISSUE TITLE
Cannot create purchases.

### ISSUE THREAD

**Issue by tgirotto** [ruckus/quickbooks-ruby#232]
I have been trying hard to create and push purchases to quickbooks, but haven't had any luck yet. Here is my code:

    purchase = Quickbooks::Model::Purchase.new()

        account_ref = Quickbooks::Model::BaseReference.new() #--> apparently not needed
        account_ref.value = '1' #--> apparently not needed

    purchase.account_ref = account_ref #--> apparently not needed
    purchase.payment_type = 'Cash'

        array = Array.new

            line_item = Quickbooks::Model::PurchaseLineItem.new() #-->required
            line_item.id = '1' #--> not required
            line_item.amount = '10' # --> not required
            line_item.detail_type = 'AccountBasedExpenseLineDetail' #--> required

                line_detail = Quickbooks::Model::AccountBasedExpenseLineDetail.new() #--> required

                line_detail_account_ref = Quickbooks::Model::BaseReference.new()
                line_detail_account_ref.value = '1'

                line_detail.account_ref = line_detail_account_ref
        
            line_item.account_based_expense_line_detail = line_detail #--> required

      array.push line_item #--> required

    purchase.line_items = array
    purchase.account_id = '1352646220'  #this is correct

    @order_service.create(purchase)

Where am I wrong? 

Again, thank you for the support.

**Comment by minimul** [comment]
Here is a working example

```ruby

    purchase = Quickbooks::Model::Purchase.new
    purchase.payment_type = 'Cash'
    purchase.account_id = 36 # Sandbox bank/asset account: Savings
    line_item = Quickbooks::Model::PurchaseLineItem.new
    line_item.amount = 419.99
    line_item.description = "Rink Liner"
    line_item.account_based_expense! do |detail|
      detail.account_id = 28 #  # Sandbox expense account: Disposal fees
      detail.customer_id = 1
    end
    purchase.line_items = []
    purchase.line_items << line_item
    #puts purchase.to_xml

    result = @order_service.create(purchase)
end

**Comment by hrrf** [comment]
:+1: 

I had an issue here as well, which was resolved when I initialized the array with:
```
purchase.line_items = []
```

I think perhaps @tgirotto may have had issues because the `Invoice` example in the `readme` doesn't initialize the `line_items` array.  It isn't clear that this is necessary until you've hit your head against it a few times.

**Comment by Craggar** [comment]
Should the purchase model perhaps include 'has_line_items', as invoices, credit memos, etc. as this ensures the initialization of the line_items[] array?

**Comment by tgirotto** [comment]
wow, @minimul 's snippet worked!!! I think it really was as @Craggar said. 

Thank you again! 

Closing this now :)

**Comment by vishalyuvasoft** [comment]
In Quickbook purchase how to we set my customer and billable_status

**Comment by hrrf** [comment]
You have to have a `customer_ref` which would be the ID of one of your QuickBooks Online customer entities.  If you think about it - it can't be billable unless you have someone to bill it against, right?

If you have the id, you can apply the `customer_ref` and toggle `billable_status` on any `PurchaseLineItem` added to that `Purchase`:

Here's a quick example:

```
purchase = Quickbooks::Model::Purchase.new
# initialize your purchase ...
purchase.line_items = []  # This may not be necessary anymore

line_item = Quickbooks::Model::PurchaseLineItem.new
line_item.account_based_expense! do |detail|
  detail.customer_id    = <Your customer reference or id>
  detail.billable_status = 'Billable'  # Or whatever status. see BillableStatusEnum 

  # ...
end
```

**Comment by vishalyuvasoft** [comment]
@hrrf 

thanks for your response its work for me.

 Thank you again!
