### ISSUE TITLE
Invoice Status

### ISSUE THREAD

**Issue by rkjbnz** [ruckus/quickbooks-ruby#233]
Is there a way to get the invoice status e.g. Open, Paid, Overdue. Looking at the invoice attributes and the API docs it doesn't seem to have this available.

**Comment by rkjbnz** [comment]
Just found it TxnStatus. Doesn't seem to be implemented in the model.

**Comment by minimul** [comment]
I am seeing TxnStatus for Credit Memo, Deposit, and Estimate but not Invoice.
Best to check the balance e.g. Balance = 0.00 is paid.

**Comment by rkjbnz** [comment]
I was obviously looking in the wrong place. Sorry about that. Thanks for the advice.
