### ISSUE TITLE
How to get all expenses?

### ISSUE THREAD

**Issue by ricsrock** [ruckus/quickbooks-ruby#236]
I'm implementing budget-to-actual reporting. I can get budget items by date, class, and account.

How do I get all expenses? I can't seem to find which model/service provides the whole picture.

Thanks!

**Comment by ruckus** [comment]
Is an Expense just a `Bill`? In which case you can use the `Bill` service.

**Comment by ricsrock** [comment]
Could be a bill or a purchase, I suppose. 

Are there additional models that may represent cash basis expenses? I could combine all of them to get the full picture. 

Or is there a model that represents any/all expenses? 

Thanks!

**Comment by ruckus** [comment]
There is no distinct top-level `Expense` entity that I can see in the API docs. However, you can create an Expense through the QB site. So it looks like it comes down to:

1. Intuit has the concept of an `Expense` entity but just doesn't expose it to the API and there is nothing we can do until they make it public.

2. There really is no `Expense` entity, its something else like an `Bill` or `Purchase` and there is some flag or UI convention whereby its labelled an expense.

Something like that...(?)

**Comment by minimul** [comment]
Answered here: https://intuitdeveloper.lc.intuit.com/questions/1129731-how-to-get-all-expenses-via-v3-api

**Comment by ruckus** [comment]
Thanks for the link @minimul
