### ISSUE TITLE
Get a salesreceipt as PDF

### ISSUE THREAD

**Issue by JShelto** [ruckus/quickbooks-ruby#242]
Is there any support to allow users make the necessary GET request to return a sales receipt as a pdf?

**Comment by minimul** [comment]
No, but until that support is added (hint, hint) you can do this:

```
service = Quickbooks::Service::Invoice.new
service.company_id = "123" 
service.access_token = access_token

service.oauth.get(service.url_for_base + '/invoice/159/pdf', { 'Accept' => 'application/pdf' })
```

**Comment by ruckus** [comment]
Hi @JShelto - this has been implemented, check out the README for a quick how-to:

https://github.com/ruckus/quickbooks-ruby#download-pdf-of-an-invoice-or-salesreceipt
