### ISSUE TITLE
total in Bill model should be total_amt to stay consistent

### ISSUE THREAD

**Issue by illegalnumbers** [ruckus/quickbooks-ruby#243]
This is just an opinion so stay open minded with me!

When you use the bill model it'd be nice if it reflected the actual api similar to all the rest of the models in the library. Or at least have an alias for total to be the same. I got a method undefined error and it was quite the bummer because of that.

Like I said, just an opinion.

**Comment by minimul** [comment]
Not at all. Thanks for the feedback. Would you be able to submit a PR detailing this?

**Comment by bytenel** [comment]
Yeah man! I'll get one up this weekend.
