### ISSUE TITLE
AccountBasedExpenseLineDetail in line.rb

### ISSUE THREAD

**Issue by bytenel** [ruckus/quickbooks-ruby#244]
Is AccountBasedExpenseLineDetail not accessed from the Line model? I see in lines 19-23 that you can get the other detail types but this one seems to be missing.

**Comment by ruckus** [comment]
It appears that `AccountBasedExpenseLineDetail` is related to the `PurchaseLineItem` class and is not used for Invoices, which the `Line` model is part of. 

From the docs this is the list of valid `Invoice#Line` types:

![screen shot 2015-04-23 at 2 03 26 pm](https://cloud.githubusercontent.com/assets/320/7307419/95f6196e-e9c1-11e4-818f-bab4f958fda8.png)

What are you trying to do that you're expecting to access `AccountBasedExpenseLineDetail` from `Line`?

From this somewhat-related StackOverflow answer:

http://stackoverflow.com/a/18854387/25398

It hints about differences between the v2 and v3 APIs so maybe there is another way to do what you're trying to do.

**Comment by bytenel** [comment]
It seems you were right, there was another way to do what I wanted. Thanks!
