### ISSUE TITLE
Error deleting Purchase Order

### ISSUE THREAD

**Issue by ginter** [ruckus/quickbooks-ruby#248]
Anyone have an idea why this would be causing an error? I can delete other resources like invoices with no issue.

I, [2015-04-30T11:08:59.664451 #95611]  INFO -- : ------ QUICKBOOKS-RUBY REQUEST ------
I, [2015-04-30T11:08:59.664518 #95611]  INFO -- : METHOD = post
I, [2015-04-30T11:08:59.664551 #95611]  INFO -- : RESOURCE = https://sandbox-quickbooks.api.intuit.com/v3/company/1370622550/purchaseorder?operation=delete
I, [2015-04-30T11:08:59.664580 #95611]  INFO -- : REQUEST BODY:
I, [2015-04-30T11:08:59.664810 #95611]  INFO -- :

``` xml
<?xml version="1.0" encoding="utf-8"?>
<Bill xmlns="http://schema.intuit.com/finance/v3" sparse="false">
<Id>5204</Id>
<SyncToken>0</SyncToken>
<MetaData>
<CreateTime>2015-04-29T20:39:32-0700</CreateTime>
<LastUpdatedTime>2015-04-29T20:39:32-0700</LastUpdatedTime>
</MetaData>
<DocNumber>001A</DocNumber>
<TxnDate>2014-12-03</TxnDate>
<Line>
<Id>1</Id>
<Description>Unit is down.</Description>
<Amount>105.0</Amount>
<DetailType>AccountBasedExpenseLineDetail</DetailType>
<AccountBasedExpenseLineDetail>
<AccountRef name="Job Expenses">58</AccountRef>
<BillableStatus>NotBillable</BillableStatus>
<TaxCodeRef>NON</TaxCodeRef>
</AccountBasedExpenseLineDetail>
</Line>
<VendorRef name="Leaf">333</VendorRef>
<APAccountRef name="Accounts Payable (A/P)">33</APAccountRef>
<DueDate>2015-01-03</DueDate>
<Balance>105.0</Balance>
<TotalAmt>105.0</TotalAmt>
</Bill>
```

I, [2015-04-30T11:08:59.664870 #95611]  INFO -- : REQUEST HEADERS = {"Content-Type"=>"application/xml", "Accept"=>"application/xml", "Accept-Encoding"=>"gzip, deflate"}
I, [2015-04-30T11:09:00.022255 #95611]  INFO -- : ------ QUICKBOOKS-RUBY RESPONSE ------
I, [2015-04-30T11:09:00.022342 #95611]  INFO -- : RESPONSE CODE = 500
I, [2015-04-30T11:09:00.022374 #95611]  INFO -- : RESPONSE BODY:
I, [2015-04-30T11:09:00.022660 #95611]  INFO -- :+1: 

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2015-04-30T11:09:00.338-07:00">
  <Fault type="SystemFault">
    <Error code="10000">
      <Message>An application error has occurred while processing your request</Message>
      <Detail>System Failure Error: Bad arguments passed to public com.intuit.schema.finance.v3.IntuitResponse com.intuit.qbo.servicev3.rest.PurchaseOrder.create(java.lang.String,com.intuit.schema.finance.v3.PurchaseOrder,java.lang.String,java.lang.String,java.lang.String) throws com.intuit.qbo.servicev3.FdmException  ( java.lang.String 1370622550, com.intuit.schema.finance.v3.Bill com.intuit.schema.finance.v3.Bill@2c408fa1, null, null, java.lang.String delete )</Detail>
    </Error>
  </Fault>
</IntuitResponse>
```

`AccountingGateway::InvalidRequest: An application error has occurred while processing your request:
    System Failure Error: Bad arguments passed to public com.intuit.schema.finance.v3.IntuitResponse com.intuit.qbo.servicev3.rest.PurchaseOrder.create(java.lang.String,com.intuit.schema.finance.v3.PurchaseOrder,java.lang.String,java.lang.String,java.lang.String) throws com.intuit.qbo.servicev3.FdmException  ( java.lang.String 1370622550, com.intuit.schema.finance.v3.Bill com.intuit.schema.finance.v3.Bill@2c408fa1, null, null, java.lang.String delete )`

**Comment by minimul** [comment]
You're sending a Bill in the POST request. Needs to be PurchaseOrder.
