### ISSUE TITLE
Generate Invoice Not working

### ISSUE THREAD

**Issue by prateeksinghbundela** [ruckus/quickbooks-ruby#251]
I have used this source code

	  invoice = Quickbooks::Model::Invoice.new
		invoice.customer_id = 99
		invoice.txn_date = Date.civil(2013, 11, 20)
		invoice.doc_number = "1001" 
		line_item = Quickbooks::Model::InvoiceLineItem.new
		line_item.amount = 50
		line_item.description = "Plush Baby Doll"
		line_item.sales_item! do |detail|
		  detail.unit_price = 50
		  detail.quantity = 1
		  detail.item_id = 500 # Item ID here
		end
		invoice.line_items << line_item
                oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, session[:token], session[:secret])
              @invoice_service = Quickbooks::Service::Invoice.new
	      @invoice_service.company_id = "1396814215"
	      @invoice_service.access_token = oauth_client
	      @invoice_service.realm_id = session[:realm_id]
              @invoice_service.create(invoice)

After run create command this type of error occur What can i do Please suggest me Quickbooks::IntuitRequestException Exception: Invalid Reference Id:
	Invalid Reference Id : Line.SalesItemLineDetail.ItemRef

**Comment by minimul** [comment]
The Item reference is invalid . The ```detail.item_id = 500``` needs to be a valid Item on QBO. Search your sandbox or QBO test account for a valid Item ID.
