### ISSUE TITLE
Timesheet integerate with Quickbooks

### ISSUE THREAD

**Issue by prateeksinghbundela** [ruckus/quickbooks-ruby#252]
Hello,

I am unable to create model and service for timesheet please given me the solution , In what way i can used the timesheet integeration.

**Comment by minimul** [comment]
You mean [TimeActivity](https://developer.intuit.com/docs/api/accounting/TimeActivity)?

Check the specs:

[Service spec](https://github.com/ruckus/quickbooks-ruby/blob/master/spec/lib/quickbooks/service/time_activity_spec.rb)

[Model spec](https://github.com/ruckus/quickbooks-ruby/blob/master/spec/lib/quickbooks/model/time_activity_spec.rb)

**Comment by prateeksinghbundela** [comment]
Hello ,

I have worked on this "peaceful-taiga-7787.herokuapp.com"
First login through cred

prateekyuvasoft101@gmail.com
123456789

And then go to peaceful-taiga-7787.herokuapp.com/timesheets

Then you click on Add Time 
new timesheet object created and user can create timesheet this values are also go to Qb ?

**Comment by minimul** [comment]
What kind of QBO transaction are looking to create?

**Comment by minimul** [comment]
Closing. No response.
