### ISSUE TITLE
BaseReference initialize change

### ISSUE THREAD

**Issue by divya-eligible** [ruckus/quickbooks-ruby#253]
Can the BaseReference(https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/model/base_reference.rb) initialize be changed to take type, name and value? I accidentally gave entity type, name and value during initialization and it wasn't working. later checked the initialize and figured out that the initialize takes only value.

**Comment by ruckus** [comment]
Sounds like that could be useful. Care to create a Pull Request?

**Comment by divyak-eligibleapi** [comment]
Sure.
