### ISSUE TITLE
Request ID QuickBooks

### ISSUE THREAD

**Issue by dheeraj510** [ruckus/quickbooks-ruby#256]
Hello,

I found some interesting blog post here https://developer.intuit.com/blog/2015/04/06/15346
It says by using Request ID data is not duplicated in the event of a disruption. this is what exactly I am looking for. I could not figure out how to send Request ID while posting journal entry or sales receipt to stop duplicating same data if posted again and again.

can we use this from  quickbooks-ruby Gem? if possible can you provide some sample code for journal entry or sales receipt?

Thank you.

**Comment by ruckus** [comment]
Hey @dheeraj510  - you want to give this a whack? Used like:

```ruby
created_invoice = @service.create(invoice, :query => {:requestid => "foobar123"})
```

**Comment by dheeraj510** [comment]
Hi @ruckus, Thanks for responding quickly.  I attempted to do it with journal entry using above syntax.  But it seems request id is not sent in my request and journal entries are duplicated in my quickbook account. Is request_id can be used only in invoice or it can be used also for journal entry and sales receipt too?

Following is my code for journal entire:

service = Quickbooks::Service::JournalEntry.new({access_token: oauth_client, company_id: company_id})
journal_entry = Quickbooks::Model::JournalEntry.new(:doc_number => "test", :txn_date => Date.today, :private_note => "test" )
journal_entry.line_items = []

line = Quickbooks::Model::Line.new
line.line_num = 1
line.detail_type = 'JournalEntryLineDetail'
line.description = "test"
line.amount = 12
jeld = Quickbooks::Model::JournalEntryLineDetail.new
jeld.posting_type = 'Credit'
jeld.account_id = 334
line.journal_entry_line_detail = jeld
journal_entry.line_items << line

line = Quickbooks::Model::Line.new
line.line_num = 2
line.detail_type = 'JournalEntryLineDetail'
line.description = "test"
line.amount = 12
jeld = Quickbooks::Model::JournalEntryLineDetail.new
jeld.posting_type = 'Debit'
jeld.account_id = 345
line.journal_entry_line_detail = jeld
journal_entry.line_items << line

service.create(journal_entry , :query => {:requestid => "8f199EGdg5dASY1fG5bEzkt5k2cNgBxx"})

 ------ QUICKBOOKS-RUBY REQUEST ------

METHOD = post
RESOURCE = https://sandbox-quickbooks.api.intuit.com/v3/company/1315124650/journalentry
REQUEST BODY:
<?xml version="1.0" encoding="utf-8"?>
<JournalEntry xmlns="http://schema.intuit.com/finance/v3" sparse="false">
<DocNumber>test</DocNumber>
<TxnDate>2015-07-22</TxnDate>
<PrivateNote>test</PrivateNote>
<Line>
<LineNum>1</LineNum>
<Description>test</Description>
<Amount>12.0</Amount>
<DetailType>JournalEntryLineDetail</DetailType>
<JournalEntryLineDetail>
<PostingType>Credit</PostingType>
<AccountRef>334</AccountRef>
</JournalEntryLineDetail>
</Line>
<Line>
<LineNum>2</LineNum>
<Description>test</Description>
<Amount>12.0</Amount>
<DetailType>JournalEntryLineDetail</DetailType>
<JournalEntryLineDetail>
<PostingType>Debit</PostingType>
<AccountRef>345</AccountRef>
</JournalEntryLineDetail>
</Line>
</JournalEntry>

REQUEST HEADERS = {"Content-Type"=>"application/xml", "Accept"=>"application/xml", "Accept-Encoding"=>"gzip, deflate"}
------ QUICKBOOKS-RUBY RESPONSE ------
RESPONSE CODE = 200
RESPONSE BODY:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2015-07-22T11:20:38.970-07:00">
<JournalEntry domain="QBO" sparse="false">
<Id>4062</Id>
<SyncToken>0</SyncToken>
<MetaData>
<CreateTime>2015-07-22T11:20:39-07:00</CreateTime>
<LastUpdatedTime>2015-07-22T11:20:39-07:00</LastUpdatedTime>
</MetaData>
<DocNumber>test</DocNumber>
<TxnDate>2015-07-22</TxnDate>
<PrivateNote>test</PrivateNote>
<Line>
<Id>0</Id>
<Description>test</Description>
<Amount>12.00</Amount>
<DetailType>JournalEntryLineDetail</DetailType>
<JournalEntryLineDetail>
<PostingType>Credit</PostingType>
<AccountRef name="4SK-Undeposited Funds OTHER">334</AccountRef>
</JournalEntryLineDetail>
</Line>
<Line>
<Id>1</Id>
<Description>test</Description>
<Amount>12.00</Amount>
<DetailType>JournalEntryLineDetail</DetailType>
<JournalEntryLineDetail>
<PostingType>Debit</PostingType>
<AccountRef name="SK-Undeposited Cash">345</AccountRef>
</JournalEntryLineDetail>
</Line>
<TxnTaxDetail/>
<Adjustment>false</Adjustment>
</JournalEntry>
</IntuitResponse>

**Comment by ruckus** [comment]
Did you try this with `master` - which contains my last commit? The released gem on RubyGems doesnt have this fix.

You can refer to `master` in your `Gemfile` like:

`gem 'quickbooks-ruby', :git => 'https://github.com/ruckus/quickbooks-ruby'`

**Comment by dheeraj510** [comment]
Thanks a lot that help me to resolve the problem :+1:

**Comment by ruckus** [comment]
Great. So you used `master` and were able to use the `requestId` feature? If so, I can close this issue and eventually release a new version with this update.

**Comment by dheerajk3** [comment]
yes @ruckus.. I am able to use request Id feature to stop duplicate posting in to QuickBooks using master branch. I tried to post journal entry and sales receipt and I am success. you can close this ticket. Thanks again.
