### ISSUE TITLE
Link payment to invoice

### ISSUE THREAD

**Issue by spq24** [ruckus/quickbooks-ruby#258]
I'm not sure what I'm doing wrong here. I'm creating an invoice and then immediately trying to link a payment (they happen at the same time) to the invoice so it's paid and the payment is marked as closed but I can't get it to work. Here's the code I have now.

The payment and invoice are both created in QBO, but how do I link them?

```ruby
    before_action :set_qb_service, only: [:edit, :update, :create, :destroy]

    def add_payment_to_quickbooks
        amount_to_charge = Money.new(@payment.amount, "USD").format.delete('$')
        invoice = Quickbooks::Model::Invoice.new
        invoice.customer_id = @payment.customer.quickbooks_customer_id
        invoice.txn_date = @payment.created_at
        invoice.doc_number = @payment.invoice_number
        invoice.private_note = @payment.invoice_number + " " + @payment.customer.customer_name
        line_item = Quickbooks::Model::InvoiceLineItem.new
        line_item.amount = amount_to_charge
        line_item.description = "Services Rendered"
        line_item.detail_type = "SalesItemLineDetail"
        line_item.sales_item! do |detail|
          detail.unit_price = amount_to_charge.delete('$')
          detail.quantity = 1
        end
        invoice.line_items << line_item

        created_invoice = @qb_invoice.create(invoice)
    
        if created_invoice.present?
          @payment.update_attribute(:quickbooks_invoice_id, created_invoice.id)
        end                		

        line = Quickbooks::Model::Line.new
        line.linked_transactions = @payment.quickbooks_invoice_id
		payment = Quickbooks::Model::Payment.new
        payment.customer_id = @customer.quickbooks_customer_id
		payment.total = amount_to_charge
        payment.private_note = @payment.invoice_number + " " +     @payment.customer.customer_name
        payment.line_items << line
        response = @qb_payment.create(payment)

		if response.present?
                   @customer.update_attribute(:quickbooks_customer_id, response.customer_ref.value)
		end
    end

 	def set_qb_service
 	  @user = current_user
 	  @company = @user.company
         oauth_client = OAuth::AccessToken.new($qb_oauth_consumer, @company.quickbooks_token, @company.quickbooks_secret)
         @qb_customer = Quickbooks::Service::Customer.new
         @qb_customer.access_token = oauth_client
         @qb_customer.company_id = @company.quickbooks_realm_id
         @qb_payment = Quickbooks::Service::Payment.new
         @qb_payment.access_token = oauth_client
         @qb_payment.company_id = @company.quickbooks_realm_id
         @qb_invoice = Quickbooks::Service::Invoice.new
         @qb_invoice.access_token = oauth_client
        @qb_invoice.company_id = @company.quickbooks_realm_id
      end`
```

**Comment by ruckus** [comment]
Hard to diagnose without seeing the underlying HTTP request / response cycle. There are a couple of ways to tackle this:

* 1: If you're running this locally then you can point the library to a locally running HTTP Proxy - such as Charles:

http://www.charlesproxy.com/

If you go this route then the necessary configuration is:

```ruby
options = {
  :site                 => "https://oauth.intuit.com",
  :request_token_path   => "/oauth/v1/get_request_token",
  :authorize_path       => "/oauth/v1/get_access_token",
  :access_token_path    => "/oauth/v1/get_access_token",
}

if Rails.env.development?
  options[:proxy] = "http://127.0.0.1:8888" # this is the port that Charles is listening on
end

$qb_oauth_consumer = OAuth::Consumer.new(consumer_key, consumer_secret, options)
```

* 2: if you cannot run a proxy then at least turn on logging, see this section in the README:

https://github.com/ruckus/quickbooks-ruby#logging

**Comment by minimul** [comment]
You're not building it correctly. Needs to be like this (not tested):
```ruby


def make_payment
  qb_payment = Quickbooks::Model::Payment.new
  line = Quickbooks::Model::Line.new
  line.amount = 9900
  line.linked_transactions << set_linked_transaction(invoice_qbo_id)
  qb_payment.line_items << line
end

def set_linked_transaction(qbo_id)
  linked_transaction = Quickbooks::Model::LinkedTransaction.new
  linked_transaction.txn_id = qbo_id
  linked_transaction.txn_type = 'Invoice'
  linked_transaction
end

```

**Comment by spq24** [comment]
Thank you! that worked.

Steve Quatrani
E: spq2461@gmail.com
C: 215 205 5322

**Comment by andyzei** [comment]
would be great to put this in the readme -- if you give me an issue, i'll do a pr

**Comment by ruckus** [comment]
@andyzei yes, that would be much appreciated! You dont need an issue - just submit a PR. Thanks!

**Comment by puneetimpinge** [comment]
How can I pay invoices from unapplied payment?

**Comment by minimul** [comment]
Update the payment only now linking the invoice in the modification.

See the `LinkedTransaction` code above but instead you would be updating an
existing Payment and not creating new.

**Comment by puneetimpinge** [comment]
I am creating a new payment.

        payment = Quickbooks::Model::Payment.new
        payment.customer_id = customer.id
        payment.total = paid_amount
        @qb_payment.create(payment)

It adds payment as unapplied in qbo.

Then creating a new invoice. How can I update the payment and pay invoice from unapplied payment.

Also how to delete/inactive the customer if it has open balance?

**Comment by minimul** [comment]
Create the payment and then when creating the invoice, apply the payment by
linking its QBO ID (You are persisting these right?).

See https://developer.intuit.com/docs/api/accounting/payment =>
Line=>LinkedTxn

**Comment by puneetimpinge** [comment]
How to fetch all payments with unapplied amount > 0

code I tried:

@qb_payment.query("SELECT * FROM Payment WHERE UnappliedAmt!='0.0' ")

Quickbooks::IntuitRequestException: Invalid query:
	QueryValidationError: property 'UnappliedAmt' is not queryable

**Comment by ruckus** [comment]
Yes, not all fields are queryable. I dont know what the list is for any given entity, but the error message indicates that `UnappliedAmt` is not a queryable field. You'll have to use some other queryable to fetch records and then check them in application code.

For my own purposes I often want to get recent payments, so my query is:

`SELECT * FROM Payment WHERE MetaData.CreateTime >= ?"` and then the parameter is something like 2 or 3 days ago.

**Comment by puneetimpinge** [comment]
@ruckus how can I get all unapplied payments?

**Comment by minimul** [comment]
The way to find if a resource attribute is "query-able" is to see if it is
"filterable" in the docs. See https://developer.intuit.com/docs/api/accounting/payment
and look for filterable next to the attribute.

The way to get unapplied payments is to do a query like @ruckus suggested.
From there you have `UnappliedAmt` node results and you'll use Ruby to do the
rest.

On Tue, Jul 25, 2017 at 01:30 AM, puneetimpinge <notifications@github.com> wrote:

> from: puneetimpinge <notifications@github.com>
> date: Tue, Jul 25 05:30 AM +00:00 2017
> to: ruckus/quickbooks-ruby <quickbooks-ruby@noreply.github.com>
> cc: Christian Pelczarski <zarski@gmail.com>, State change <state_change@noreply.github.com>
> reply-to: ruckus/quickbooks-ruby <reply@reply.github.com>
> subject: Re: [ruckus/quickbooks-ruby] Link payment to invoice (#258)
> 
> @ruckus how can I get all unapplied payments?
> 
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/ruckus/quickbooks-ruby/issues/258#issuecomment-317633600


Regards — Christian
