### ISSUE TITLE
Unable to Apply TaxRate to Quickbooks Invoice

### ISSUE THREAD

**Issue by kashif-umair** [ruckus/quickbooks-ruby#262]
Hi,
I'm using this gem to integrate quickbooks with my product. I'm able to sync invoice and it's line items to quickbooks and I've also figured out a way that how to apply tax code on invoice line items but I'm facing an issue when I try to apply tax rate to a quickbooks invoice. Can anyone please guide me to some tutorial or help me by telling me about what methods I should use to apply the tax-rate.

**Comment by minimul** [comment]
Is this for a U.S. invoice?

**Comment by kashif-umair** [comment]
Yes, I'm using to sandbox account to test out things and the quickbooks company is U.S.

**Comment by minimul** [comment]
I'll look like this (not tested). Tax rate goes in "header" as `txn_tax_detail`
```ruby

module Qbo
  class Invoice

    def build
      qb_invoice = Quickbooks::Model::Invoice.new
      qb_invoice.customer_ref = set_customer
      qb_invoice.txn_tax_detail = set_transaction_tax
      qb_invoice.line_items << set_sales
      qb_invoice
    end

    def set_customer
      qb_customer = Quickbooks::Model::BaseReference.new(5)
      qb_customer.name = "Dukes Basketball Camp"
      qb_customer
    end

    def set_transaction_tax
      transaction = Quickbooks::Model::TransactionTaxDetail.new
      transaction.txn_tax_code_id = 4 # TaxRate e.g. "Sales Tax" in sandbox
      transaction
    end

    def set_sales
      sales = Quickbooks::Model::InvoiceLineItem.new
      unit_price = 55.5
      sales.amount = (unit_price.to_f * 3).round(2)
      sales.description = 'Concrete'
      sales.sales_item! do |detail|
        detail.unit_price = unit_price
        detail.quantity = 3
        detail.item_ref = 3 # Concrete in sandbox
        detail.rate_percent = 0
        detail.tax_code_id = 'TAX'
      end
      sales
    end

  end
end

```

**Comment by kashif-umair** [comment]
That's exactly what I needed. Thanks for quick response and detailed answer :+1: You can close this now.

**Comment by vanboom** [comment]
Could you elaborate please on how the TransactionTaxDetail works?  I am struggling to get sales tax applied to my invoices also.  In the above example, transaction.txn_tax_code_id = 4, where did '4' come from? 

thanks!

**Comment by minimul** [comment]
4 is a TaxRate from the sandbox. Also, the above example is for a US invoice. The detail.tax_code_id = 'TAX' is a TaxCode.
If you want to go in-depth: https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/global_tax_model

**Comment by markixnim** [comment]
Thanks Christian for your helpful responses. 

In my application, users can apply any tax rate they want to an invoice, we don't have specific tax codes. I understand while you can define different tax_codes in Quickbooks for various regions, you can also override the tax amount directly. I am wondering if it's ok to apply a generic tax code for all invoices, and override the tax_amount for each invoice. Love to hear your thoughts around this. 

Thanks!

**Comment by minimul** [comment]
Is it for non-US? Read this for overriding:
https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/global_tax_model/non-us_sales_tax_integrations#/Overriding_Purchase_Tax

**Comment by markixnim** [comment]
Thanks Christian. 

We are using the US version so here is the portion of the code for overriding: 

  "TxnTaxDetail": {
        "TxnTaxCodeRef": {
            "value": "3",
            "name": "Tucson"
        },
        "TotalTax": 9.5
    },

In this case, should we create a generic TaxCode and override the tax amount for each invoice?

**Comment by minimul** [comment]
Yes, that is how you would override in a US invoice.

Personally, I would not create a TaxCode on your client's QBO.  I would
import their codes and reference them while adding the TotalTax.

If you do create a generic TaxCode make sure you name it well so
they and their accountant know what it is e.g. "Killer App Generic Tax
Code".
