### ISSUE TITLE
Provide a way to fetch all records.

### ISSUE THREAD

**Issue by vanboom** [ruckus/quickbooks-ruby#263]
Would it be possible to have an :all option to retrieve all records in a single query? 

thanks!

**Comment by ruckus** [comment]
QBO does impose default limits.

From: https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/querying_data

> Maximum number of entities in a response

> The maximum number of entities that can be returned in a response is 1000.  If the result size is not specified, the default number is 100. If a query returns many entities, fetch the entities in chunks, as described in Pagination.  To determine the number of entities that a particular query returns, probe by using the COUNT keyword in the query. See Count for details.

So to get more results you can bump up the `per_page` attribute.

**Comment by minimul** [comment]
What you want is the `query_in_batches` method. This is from the README
### Querying in Batches

Often one needs to retrieve multiple pages of records of an Entity type
and loop over them all. Fortunately there is the `query_in_batches` collection method:

```ruby
query = nil
Customer.query_in_batches(query, per_page: 1000) do |batch|
  batch.each do |customer|
    # ...
  end
end
```

The first argument to `query_in_batches` is the `query` (which
can be `nil` to retrieve the default items in that collection).
If you're are running a custom Query then pass it instead.

The second argument is the options, which are optional.
By default, the options are `per_page: 1000`.
