### ISSUE TITLE
Does anyone experiences this OAuth issue?

### ISSUE THREAD

**Issue by raecoo** [ruckus/quickbooks-ruby#265]
this is full error logs https://gist.github.com/raecoo/32ee7150652c77e8e86a

the code running with Sidekiq worker like this:
```ruby
ProductService.new(params).sync_entry
```
and the code line#52 of the ProductService like this:

```ruby
service = Quickbooks::Service::Item.new(access_token: access_token, company_id: company_id)
if qb_item = service.fetch_by_id("#{qb_item_id}")
  qb_item.description = product.body_html
  qb_item.taxable     = product.taxable
  qb_item.unit_price  = product.price
  service.update(qb_item)
end
```
I've changed the Ruby version from 2.0.0 to 2.1.0 and 2.2.0, same result of them.

Once the issue occurs the Sidekiq processes will be quit in a few minutes.

**Comment by ruckus** [comment]
Never seen that one before myself.

Maybe pull the source for Ruby 2.1.5 and look around these lines:

/home/ec2-user/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920

**Comment by raecoo** [comment]
@ruckus I've tested on 2.0.0, 2.1.0 and 2.2.0. all same result of them.

**Comment by minimul** [comment]
I bet the problem is the with:
`qb_item.description = product.body_html`
Comment it out and try again. If you still are getting the error
then comment out the others until you narrow down the problem.

**Comment by minimul** [comment]
Closing no response.
