### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by vishalyuvasoft** [ruckus/quickbooks-ruby#266]

**Comment by vishalyuvasoft** [comment]
In quickbooks purchase  how to we create the billable_status in QB

**Comment by minimul** [comment]
Please provide a detailed question.

**Comment by vishalyuvasoft** [comment]
thanks @minimul 

i have resolved the problem by the help of this code

If you have the id, you can apply the customer_ref and toggle billable_status on any PurchaseLineItem added to that Purchase:

Here's a quick example:

purchase = Quickbooks::Model::Purchase.new
# initialize your purchase ...
purchase.line_items = []  # This may not be necessary anymore

line_item = Quickbooks::Model::PurchaseLineItem.new
line_item.account_based_expense! do |detail|
  detail.customer_id    = <Your customer reference or id>
  detail.billable_status = 'Billable'  # Or whatever status. see BillableStatusEnum 

  # ...
end

purchase.line_items << line_item
