### ISSUE TITLE
How to set discount value in Quick Book?

### ISSUE THREAD

**Issue by ahmedanees** [ruckus/quickbooks-ruby#267]
Hi, 
I am trying to apply discount value in Quick book but for some reason discount does not apply in Quickbook. Can you please guide me how can i resolve this issue?
## Discount value code:

``` ruby
              discount_amount = discount_value
              discount_line_item = Quickbooks::Model::InvoiceLineItem.new
              discount_line_item.amount = discount_amount#149
              discount_line_item.discount_item! do |detail|
                detail.discount_account_id = 48
              end
```
## Discount percentage code:

``` ruby
discount_line_item = Quickbooks::Model::InvoiceLineItem.new
              discount_line_item.amount = discount_percentage_value#149
              discount_line_item.discount_item! do |detail|
                detail.discount_percent = discount_percentage_value#60
                detail.percent_based = percent_based
                detail.discount_account_id = 48
end
 invoice.line_items << discount_line_item
```
## Set Service:

``` ruby
service = Quickbooks::Service::Invoice.new
              service.company_id = realm_id #session[:user_realm_id]
              service.access_token = oauth_client
              created_invoice = service.create(invoice)
```

---

Also please tell me is there any problem with CurrentBalance with 0 balance?. please tell me how can i update this value.

``` xml
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2015-09-17T03:29:25.309-07:00">
  <Account domain="QBO" sparse="false">
    <Id>86</Id>
    <SyncToken>1</SyncToken>
    <MetaData>
      <CreateTime>2014-11-18T14:54:12-08:00</CreateTime>
      <LastUpdatedTime>2015-09-17T02:27:01-07:00</LastUpdatedTime>
    </MetaData>
    <Name>Discounts given</Name>
    <SubAccount>false</SubAccount>
    <Description>hello desctio</Description>
    <FullyQualifiedName>Discounts given</FullyQualifiedName>
    <Active>true</Active>
    <Classification>Revenue</Classification>
    <AccountType>Income</AccountType>
    <AccountSubType>DiscountsRefundsGiven</AccountSubType>
    <CurrentBalance>0</CurrentBalance>
    <CurrentBalanceWithSubAccounts>0</CurrentBalanceWithSubAccounts>
  </Account>
</IntuitResponse>
```

**Comment by ahmedanees** [comment]
When i try test Json Request in browser
https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Invoice

Json:
------
{"line_items":[{"amount":"112.0","description":"QB Test Product Sept 15, 14\n","detail_type":"SalesItemLineDetail","sales_line_item_detail":{"unit_price":"8.0","quantity":14,"item_ref":{"value":123}}},{"amount":67.2,"detail_type":"DiscountLineDetail","discount_line_detail":{"discount_percent":60,"percent_based":true,"discount_account_ref":{"value":86}}},{"amount":"0.0","detail_type":"DiscountLineDetail","discount_line_detail":{"discount_account_ref":{"value":86}}}],"customer_ref":{"value":"115"},"txn_date":"2015-09-17","doc_number":"","custom_fields":[{"id":1,"name":"LFI Invoice #","type":"StringType","string_value":"LFI5003"}]}


Response: 
------------
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2015-09-17T05:43:09.854-07:00">
  <Fault type="SystemFault">
    <Error code="10000">
      <Message>An application error has occurred while processing your request</Message>
      <Detail>System Failure Error: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.</Detail>
    </Error>
  </Fault>
</IntuitResponse>

**Comment by ahmedanees** [comment]
When I try to use test invoice XML using this link in Quick book
https://developer.intuit.com/v2/apiexplorer?apiname=V3QBO#?id=Invoice

XML Request:
-----------------
<Invoice>
<CustomField>
<DefinitionId>1</DefinitionId>
<Name>LFI Invoice #</Name>
<Type>StringType</Type>
<StringValue>LFI5003</StringValue>
</CustomField>
<DocNumber/>
<TxnDate>2015-09-17</TxnDate>
<Line>
<Description>QB Test Product Sept 15, 14</Description>
<Amount>112.0</Amount>
<DetailType>SalesItemLineDetail</DetailType>
<SalesItemLineDetail>
<ItemRef>123</ItemRef>
<UnitPrice>8.0</UnitPrice>
<Qty>14.0</Qty>
</SalesItemLineDetail>
</Line>
<Line>
<Amount>67.2</Amount>
<DetailType>DiscountLineDetail</DetailType>
<DiscountLineDetail>
<PercentBased>true</PercentBased>
<DiscountPercent>60.0</DiscountPercent>
<DiscountAccountRef>86</DiscountAccountRef>
</DiscountLineDetail>
</Line>
<Line>
<Amount>0.0</Amount>
<DetailType>DiscountLineDetail</DetailType>
<DiscountLineDetail>
<DiscountAccountRef>86</DiscountAccountRef>
</DiscountLineDetail>
</Line>
<CustomerRef>115</CustomerRef>
</Invoice>

Response:
-----------


<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2015-09-17T05:52:01.051-07:00">
  <Fault type="SystemFault">
    <Error code="10000">
      <Message>An application error has occurred while processing your request</Message>
      <Detail>System Failure Error: unexpected element (uri:"", local:"Invoice"). Expected elements are &lt;{http://schema.intuit.com/finance/v3}Account&gt;,&lt;{http://schema.intuit.com/finance/v3}Attachable&gt;,&lt;{http://schema.intuit.com/finance/v3}Bill&gt;,&lt;{http://schema.intuit.com/finance/v3}BillPayment&gt;,&lt;{http://schema.intuit.com/finance/v3}BooleanTypeCustomFieldDefinition&gt;,&lt;{http://schema.intuit.com/finance/v3}Budget&gt;,&lt;{http://schema.intuit.com/finance/v3}ChargeCredit&gt;,&lt;{http://schema.intuit.com/finance/v3}Class&gt;,&lt;{http://schema.intuit.com/finance/v3}Company&gt;,&lt;{http://schema.intuit.com/finance/v3}CompanyCurrency&gt;,&lt;{http://schema.intuit.com/finance/v3}CompanyInfo&gt;,&lt;{http://schema.intuit.com/finance/v3}CreditMemo&gt;,&lt;{http://schema.intuit.com/finance/v3}CustomFieldDefinition&gt;,&lt;{http://schema.intuit.com/finance/v3}Customer&gt;,&lt;{http://schema.intuit.com/finance/v3}DateTypeCustomFieldDefinition&gt;,&lt;{http://schema.intuit.com/finance/v3}Department&gt;,&lt;{http://schema.intuit.com/finance/v3}Deposit&gt;,&lt;{http://schema.intuit.com/finance/v3}EmailDeliveryInfo&gt;,&lt;{http://schema.intuit.com/finance/v3}Employee&gt;,&lt;{http://schema.intuit.com/finance/v3}Estimate&gt;,&lt;{http://schema.intuit.com/finance/v3}ExchangeRate&gt;,&lt;{http://schema.intuit.com/finance/v3}FixedAsset&gt;,&lt;{http://schema.intuit.com/finance/v3}IntuitBatchRequest&gt;,&lt;{http://schema.intuit.com/finance/v3}IntuitObject&gt;,&lt;{http://schema.intuit.com/finance/v3}IntuitResponse&gt;,&lt;{http://schema.intuit.com/finance/v3}InventorySite&gt;,&lt;{http://schema.intuit.com/finance/v3}Invoice&gt;,&lt;{http://schema.intuit.com/finance/v3}Item&gt;,&lt;{http://schema.intuit.com/finance/v3}JournalCode&gt;,&lt;{http://schema.intuit.com/finance/v3}JournalEntry&gt;,&lt;{http://schema.intuit.com/finance/v3}MasterAccount&gt;,&lt;{http://schema.intuit.com/finance/v3}NumberTypeCustomFieldDefinition&gt;,&lt;{http://schema.intuit.com/finance/v3}OLBStatus&gt;,&lt;{http://schema.intuit.com/finance/v3}OtherName&gt;,&lt;{http://schema.intuit.com/finance/v3}Payment&gt;,&lt;{http://schema.intuit.com/finance/v3}PaymentMethod&gt;,&lt;{http://schema.intuit.com/finance/v3}Preferences&gt;,&lt;{http://schema.intuit.com/finance/v3}PriceLevel&gt;,&lt;{http://schema.intuit.com/finance/v3}Purchase&gt;,&lt;{http://schema.intuit.com/finance/v3}PurchaseOrder&gt;,&lt;{http://schema.intuit.com/finance/v3}QbdtEntityIdMapping&gt;,&lt;{http://schema.intuit.com/finance/v3}RefundReceipt&gt;,&lt;{http://schema.intuit.com/finance/v3}ReimburseCharge&gt;,&lt;{http://schema.intuit.com/finance/v3}Report&gt;,&lt;{http://schema.intuit.com/finance/v3}SalesOrder&gt;,&lt;{http://schema.intuit.com/finance/v3}SalesReceipt&gt;,&lt;{http://schema.intuit.com/finance/v3}SalesRep&gt;,&lt;{http://schema.intuit.com/finance/v3}StatementCharge&gt;,&lt;{http://schema.intuit.com/finance/v3}Status&gt;,&lt;{http://schema.intuit.com/finance/v3}StringTypeCustomFieldDefinition&gt;,&lt;{http://schema.intuit.com/finance/v3}SyncActivity&gt;,&lt;{http://schema.intuit.com/finance/v3}SyncErrorResponse&gt;,&lt;{http://schema.intuit.com/finance/v3}TDSMetadata&gt;,&lt;{http://schema.intuit.com/finance/v3}Task&gt;,&lt;{http://schema.intuit.com/finance/v3}TaxAgency&gt;,&lt;{http://schema.intuit.com/finance/v3}TaxCode&gt;,&lt;{http://schema.intuit.com/finance/v3}TaxRate&gt;,&lt;{http://schema.intuit.com/finance/v3}Term&gt;,&lt;{http://schema.intuit.com/finance/v3}TimeActivity&gt;,&lt;{http://schema.intuit.com/finance/v3}Transfer&gt;,&lt;{http://schema.intuit.com/finance/v3}UserAlert&gt;,&lt;{http://schema.intuit.com/finance/v3}Vendor&gt;,&lt;{http://schema.intuit.com/finance/v3}VendorCredit&gt;,&lt;{http://schema.intuit.com/finance/v3}VendorType&gt;</Detail>
    </Error>
  </Fault>
</IntuitResponse>

**Comment by minimul** [comment]
Do you have in the company preference Sales Form Entry -> Discounts enabled?

**Comment by minimul** [comment]
On the JSON request you probably didn't have the Content-Type application/json . I believe you get that error because Intuit defaults to application/xml.

**Comment by ahmedanees** [comment]
![image](https://cloud.githubusercontent.com/assets/275278/9957854/380e017e-5e1d-11e5-9ee1-753dec8768d1.png)

Thanks for you reply , attached screen for discount already enabled

**Comment by ahmedanees** [comment]
![image](https://cloud.githubusercontent.com/assets/275278/9958297/e0778e4e-5e21-11e5-98d7-33382c043208.png)
![image](https://cloud.githubusercontent.com/assets/275278/9958304/eede841a-5e21-11e5-90fb-2565cbf8e12b.png)

Now trying with json with 
 content-type=	application/json 
Request: 
------------
```json
{"line_items":[{"amount":"160.0","description":"QB Test Product Sept 15, 20\n","detail_type":"SalesItemLineDetail","sales_line_item_detail":{"unit_price":"8.0","quantity":20,"item_ref":{"value":123}}},{"amount":"0.0","detail_type":"DiscountLineDetail","discount_line_detail":{"discount_account_ref":{"value":86}}}],"customer_ref":{"value":"115"},"txn_date":"2015-09-18","doc_number":"","custom_fields":[{"id":1,"name":"LFI Invoice #","type":"StringType","string_value":"LFI5007"}]}
```

Response: 
------------
```json
{"Fault":{"Error":[{"Message":"Request has invalid or unsupported property","Detail":"Property Name:Unrecognized field \"line_items\" (class com.intuit.schema.finance.v3.Invoice), not marked as ignorable (67 known properties: \"DocNumber\", \"HomeTotalAmt\", \"TotalAmt\", \"TxnSource\", \"AllowOnlinePayment\", \"EmailSt specified is unsupported or invalid","code":"2010"}],"type":"ValidationFault"},"time":"2015-09-18T04:22:32.355-07:00"}
```

**Comment by minimul** [comment]
Needs to be "Line": not "line_items": Actually, all of your JSON is in snake case. 
See proper JSON -> https://developer.intuit.com/docs/api/accounting/Invoice

If you're using this gem you need to be using XML. If you prefer JSON build something basic with Faraday, HTTParty, or Unirest.

**Comment by ahmedanees** [comment]
If i use line instead of line_item it gives me below error

undefined method `line' for #<Quickbooks::Model::Invoice:0x00000007d11440>

AND
I  just render invoice object in json and xml format and try to double check with query browser 

```ruby
 discount_line_item = Quickbooks::Model::InvoiceLineItem.new
            discount_line_item.amount = discount_amount#149
            discount_line_item.discount_item! do |detail|
              detail.discount_account_id = 86
            end
            invoice.line_items << discount_line_item
return render :json => invoice
or
return render :xml => invoice
```

**Comment by ahmedanees** [comment]
I was missing in my testing in query window , invoice header "xmlns="http://schema.intuit.com/finance/v3"
So when i try with this i am not getting any error but discount  does not apply in Quick book invoice

<Invoice xmlns="http://schema.intuit.com/finance/v3">

Request:
~~~xml
<Invoice xmlns="http://schema.intuit.com/finance/v3">
<CustomField>
<DefinitionId>1</DefinitionId>
<Name>LFI Invoice #</Name>
<Type>StringType</Type>
<StringValue>LFI5012</StringValue>
</CustomField>
<DocNumber/>
<TxnDate>2015-09-20</TxnDate>
<Line>
<Description>QB Test Product Sept 15, 20</Description>
<Amount>160.0</Amount>
<DetailType>SalesItemLineDetail</DetailType>
<SalesItemLineDetail>
<ItemRef>123</ItemRef>
<UnitPrice>8.0</UnitPrice>
<Qty>20.0</Qty>
</SalesItemLineDetail>
</Line>
<Line>
<Amount>96.0</Amount>
<DetailType>DiscountLineDetail</DetailType>
<DiscountLineDetail>
<PercentBased>true</PercentBased>
<DiscountPercent>60.0</DiscountPercent>
<DiscountAccountRef>86</DiscountAccountRef>
</DiscountLineDetail>
</Line>
<Line>
<Amount>0.0</Amount>
<DetailType>DiscountLineDetail</DetailType>
<DiscountLineDetail>
<DiscountAccountRef>86</DiscountAccountRef>
</DiscountLineDetail>
</Line>
<CustomerRef>115</CustomerRef>
</Invoice>
~~~

Response:
-------------

~~~xml
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2015-09-21T00:19:37.814-07:00">
  <Invoice domain="QBO" sparse="false">
    <Id>224</Id>
    <SyncToken>0</SyncToken>
    <MetaData>
      <CreateTime>2015-09-21T00:19:36-07:00</CreateTime>
      <LastUpdatedTime>2015-09-21T00:19:36-07:00</LastUpdatedTime>
    </MetaData>
    <CustomField>
      <DefinitionId>1</DefinitionId>
      <Name>LFI Invoice #</Name>
      <Type>StringType</Type>
      <StringValue>LFI5012</StringValue>
    </CustomField>
    <DocNumber>1100</DocNumber>
    <TxnDate>2015-09-20</TxnDate>
    <Line>
      <Id>1</Id>
      <LineNum>1</LineNum>
      <Description>QB Test Product Sept 15, 20</Description>
      <Amount>160.00</Amount>
      <DetailType>SalesItemLineDetail</DetailType>
      <SalesItemLineDetail>
        <ItemRef name="QB Test Product Sept 15 NorCal">123</ItemRef>
        <UnitPrice>8</UnitPrice>
        <Qty>20</Qty>
        <TaxCodeRef>NON</TaxCodeRef>
      </SalesItemLineDetail>
    </Line>
    <Line>
      <Amount>160.00</Amount>
      <DetailType>SubTotalLineDetail</DetailType>
      <SubTotalLineDetail />
    </Line>
    <TxnTaxDetail>
      <TotalTax>0</TotalTax>
    </TxnTaxDetail>
    <CustomerRef name="QB Test User Sept 15">115</CustomerRef>
    <BillAddr>
      <Id>161</Id>
      <Line1>123 Test Street</Line1>
      <City>San Francisco</City>
      <CountrySubDivisionCode>CA</CountrySubDivisionCode>
      <PostalCode>94109</PostalCode>
      <Lat>37.7814854</Lat>
      <Long>-122.4053204</Long>
    </BillAddr>
    <ShipAddr>
      <Id>162</Id>
      <Line1>123 Test Street</Line1>
      <City>San Francisco</City>
      <CountrySubDivisionCode>CA</CountrySubDivisionCode>
      <PostalCode>94109</PostalCode>
      <Lat>37.7814854</Lat>
      <Long>-122.4053204</Long>
    </ShipAddr>
    <DueDate>2015-10-20</DueDate>
    <TotalAmt>160.00</TotalAmt>
    <ApplyTaxAfterDiscount>false</ApplyTaxAfterDiscount>
    <PrintStatus>NeedToPrint</PrintStatus>
    <EmailStatus>NotSet</EmailStatus>
    <Balance>160.00</Balance>
    <Deposit>0</Deposit>
    <AllowIPNPayment>false</AllowIPNPayment>
    <AllowOnlinePayment>false</AllowOnlinePayment>
    <AllowOnlineCreditCardPayment>false</AllowOnlineCreditCardPayment>
    <AllowOnlineACHPayment>false</AllowOnlineACHPayment>
  </Invoice>
</IntuitResponse>
~~~

**Comment by drewish** [comment]
For reference here's some code I'm using to build a discount:
```rb
    discount_item = Quickbooks::Model::InvoiceLineItem.new(
      amount: discount_amount.abs.round(2),
      description: "Coupon"
    )
    discount_item.discount_item! do |detail|
      detail.percent_based = false
    end

    invoice.line_items << discount_item
```

One thing that was surprising to me is that you can put multiple discounts on an invoice, but QBO ignores all but the last one. I was expecting it to act more like QB Desktop where you can put a discount line below each sale line.
