### ISSUE TITLE
Not able to connect to QB. 

### ISSUE THREAD

**Issue by markixnim** [ruckus/quickbooks-ruby#272]
Version 0.4.1

I followed the setup instructions in README and was able to get all the credentials back, such as  access_token and company_id. 

Now I'm trying to make the first call to get a list of customers. 

The following code is failing: 

service = Quickbooks::Service::Customer.new
service.company_id = realm_id 
service.access_token = access_token
customers = service.query

service.query is returning this error: 

undefined method `get' for "THE_VALUE_OF_MY_ACCESS_TOKEN":String

The error is coming from: /quickbooks/service/base_service.rb:234:in `do_http'", which is trying to call get on the @oauth variable. 

Does anyone know what may have caused this error?

**Comment by ruckus** [comment]
Is `access_token` an instance of `OAuth::AccessToken`?

See: https://github.com/ruckus/quickbooks-ruby#creating-an-oauth-access-token

**Comment by markixnim** [comment]
Thanks for the quick response. 

Yes, that seems to the problem. I'm using the string access_token which is persisted in the db.
