### ISSUE TITLE
Has anyone discovered a way to check Intuit openID?

### ISSUE THREAD

**Issue by gotoAndBliss** [ruckus/quickbooks-ruby#280]
Based on Intuit Developer documentation [found here] (https://developer.intuit.com/docs/0050_quickbooks_api/0020_authentication_and_authorization/0011_from_the_intuit_app_center#/Implement_the_OpenID_user_authorization_workflow) , it appears that the README is slightly incorrect when it says ..

```
      callback = sso_intuit_success_url
      token    = $qb_oauth_consumer.get_request_token(oauth_callback: callback)
      session[:qb_request_token] = token
      redirect_to("https://appcenter.intuit.com/Connect/Begin?oauth_token=#{token.token}") and return
```

This is because in this workflow, a user will be redirected to authorize/login even if they're already logged in. This error will also cause your app to not be qualified to be listed with Intuit as a qualified app.

I was curious if anyone found a strategy to integrate Intuit Open ID to circumvent this. Where by, we send an Open ID request, verify it's logged in, and redirect directly to the ``sso_intuit_success_url```. If nobody has, I'll keep posting to this comment, and with the gem owner's permission, submit an amend to this gem that would allow this..

**Comment by ruckus** [comment]
Hi @gotoAndBliss - this is the first I've seen / heard of the Open ID auth flow. All I've used (and apparently the other gem users) is the OAuth flow.

By all means, I'm open to contributions that support Open ID. Thanks!

**Comment by minimul** [comment]
OpenID and OAuth are for totally different purposes. OpenID is 
for authorization within your app and OAuth is for authorization against
the QBO API.
