### ISSUE TITLE
Cannot visit Quickbooks::Model::BaseReference

### ISSUE THREAD

**Issue by jimiguru** [ruckus/quickbooks-ruby#282]
I'm wondering if Intuit changed something in their recent API update.  I have a simple call to download invoices that has run hourly perfect for the last 6 months and today out of the blue, with no changes to the code, I'm seeing this error.

Cannot visit Quickbooks::Model::BaseReference

**Comment by ruckus** [comment]
Can you post the request / response debugging output?

**Comment by ruckus** [comment]
Closing due to lack of information
