### ISSUE TITLE
Retrieving an Exchange Rate?

### ISSUE THREAD

**Issue by praveenperera** [ruckus/quickbooks-ruby#283]
Is it possible to retrieve and exchange rate?

https://developer.intuit.com/docs/0100_accounting/0300_developer_guides/currency#/Retrieving_an_exchange_rate

**Comment by ruckus** [comment]
Hi @praveenperera - at this time support for Exchange Rates has not been implemented. Fortunately, adding it should be relatively straight-forward - want to take a stab at a PR?

**Comment by praveenperera** [comment]
Ya sounds good, I take a shot at it this weekend

**Comment by muhammad-abubakar** [comment]
@praveenperera  Are you still working on it? Because I want to implement it?
