### ISSUE TITLE
Getting and Updating Stock Level

### ISSUE THREAD

**Issue by georgeedwards** [ruckus/quickbooks-ruby#284]
Is there any support for accessing and updating stock levels?

**Comment by ruckus** [comment]
Do you mean inventory for an Item (`QtyOnHand`)?

**Comment by georgeedwards** [comment]
Yes, reading that, adding and subtracting from it.

**Comment by ruckus** [comment]
The API docs:

https://developer.intuit.com/docs/api/accounting/Item

dont flag that attribute as being read-only which would suggest you can update that property and then save the Item.
