### ISSUE TITLE
Problems with invoices

### ISSUE THREAD

**Issue by markixnim** [ruckus/quickbooks-ruby#285]
I have recently deployed our integration to production. It was able to create payments in QBO, however, getting "java.lang.NullPointerException" when I try to create invoices. 

Given the unfriendly error message, I am assuming this is a temporary issue on the QBO side.

Please let me know if your QBO invoice API is failing today, or not. 

Thanks!
Mark

**Comment by minimul** [comment]
That's not the error you get on an outage.
Let's see the code.

**Comment by markixnim** [comment]
I see the following errors in the heroku log:

"An application error has occurred while processing your request: 
System Failure Error: java.lang.NullPointerException"

Thanks, 
Mark

**Comment by markixnim** [comment]
What's also strange is that the same set of records synced over correctly through dev/sandbox environment.

**Comment by minimul** [comment]
Closing:
An application error has occurred while processing your request: 
System Failure Error: java.lang.NullPointerException is bad request XML/JSON.
You need to scrutinize the request to find the problem.
