### ISSUE TITLE
to_xml_ns method in base_model.rb is inserting extra xml elements.

### ISSUE THREAD

**Issue by Demonyx** [ruckus/quickbooks-ruby#291]
So I have this issue where calling create on a journal entry causes quickbooks to respond with an xml parsing error. It seems that somewhere an extra `<?xml version=\"1.0\" encoding=\"UTF-8\"??>` is being inserted. Maybe I am misunderstanding but it does seem to be an issue with the gem code.

I am willing to take a crack at fixing it. I dont know if anyone else has had this issue

**Comment by minimul** [comment]
I have a client doing much JE creation. Let me see the code and the exact output.

**Comment by Demonyx** [comment]
here is my code:
`class JournalEntryService
  def initialize oauth_client, realm_id
    @journal_entry_service = Quickbooks::Service::Account.new
    @journal_entry_service.access_token = oauth_client
    @journal_entry_service.company_id = realm_id
  end

  def create account_credited, account_debited, amount, description
    line = {
        :Line => [
            {
                :ID => '',
                :Description => description,
                :Amount => amount.to_i,
                :DetailType => 'JournalEntryLineDetail',
                :JournalEntryLineDetail => {
                    :PostingType => 'Debit',
                    :AccountRef => {
                        :value => account_debited[0][:id].to_i,
                        :name => account_debited[0][:name]
                    }
                }
            },
            {
                :Description => description,
                :Amount => amount,
                :DetailType => 'JournalEntryLineDetail',
                :JournalEntryLineDetail => {
                    :PostingType => 'Credit',
                    :AccountRef => {
                        :value => account_credited[0][:id].to_i,
                        :name => account_credited[0][:name]
                    }
                }
            }
        ]
    }
    @journal_entry = Quickbooks::Model::JournalEntry.new
    @journal_entry.line_items << line
    @journal_entry_service.create(@journal_entry)
  end

  def read_journal_entry journal_entry_id
    @journal_entry = @journal_entry_service.fetch_by_id(journal_entry_id)
  end
end`

and when i run it the output i get is:
`An application error has occurred while processing your request:
	System Failure Error: org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 79; The processing instruction target matching "[xX][mM][lL]" is not allowed.`

and when I look at the xml that is produced, its this: 
`"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<JournalEntry xmlns=\"http://schema.intuit.com/finance/v3\" sparse=\"false\"><?xml version=\"1.0\" encoding=\"UTF-8\"??>\n<hash>\n  <line type=\"array\">\n    <line>\n      <id/>\n      <description type=\"array\">\n        <description>ersaitni</description>\n      </description>\n      <amount type=\"integer\">20</amount>\n      <detailtype>JournalEntryLineDetail</detailtype>\n      <journalentrylinedetail>\n        <postingtype>Debit</postingtype>\n        <accountref>\n          <value type=\"integer\">7</value>\n          <name>Advertising</name>\n        </accountref>\n      </journalentrylinedetail>\n    </line>\n    <line>\n      <description type=\"array\">\n        <description>ersaitni</description>\n      </description>\n      <amount type=\"integer\">20</amount>\n      <detailtype>JournalEntryLineDetail</detailtype>\n      <journalentrylinedetail>\n        <postingtype>Credit</postingtype>\n        <accountref>\n          <value type=\"integer\">85</value>\n          <name>Billable Expense Income</name>\n        </accountref>\n      </journalentrylinedetail>\n    </line>\n  </line>\n</hash>\n</JournalEntry>"`

any help would be greatly appreciated

**Comment by minimul** [comment]
You're not making a line item correctly. See https://github.com/ruckus/quickbooks-ruby/blob/master/spec/lib/quickbooks/model/journal_entry_spec.rb

**Comment by Demonyx** [comment]
Ah thanks so much!
