### ISSUE TITLE
Change Data Capture support

### ISSUE THREAD

**Issue by Craggar** [ruckus/quickbooks-ruby#295]
I'm implementing (well, I've mostly implemented) the Change Data Capture service, which provides a list (including the full object for each) of changed entities since a given date within the last 30 days.

When you query it, you can provide a list of entity types you care about, so I'm wondering what the consensus might be on the expected return. I currently have a function on the CDC object which is "all_changed_items", which returns a hash of changed items. I can think of three different expectations (there are maybe more):

1. The hash contains only changes. That is, given a request for three types - Invoices, Bills, and Payments - would return the following if nothing has changed: `{}`. If only the bills contained changes you would just get: `{"Bills": [Bill, Bill, Bill]}`.

2. The contains a full rundown of the requested entries. Again, if you request Invoices, Bills, and Payments, but there were only changes in bills you would get:
```{
  "Bill": [Bill, Bill, Bill],
  "Invoice": [],
  "Payment": []
}```.

3. The final option would be to just return a hash of all supported entities. So with the example again that you request Invoices, Bills, and Payments, but there were only changes in bills you would get:
```{
  "Bill": [Bill, Bill, Bill],
  "Invoice": [],
  "Payment": [],
  "Transfer": [],
  "Purchase": []
  ...etc
}```.

Any thoughts/preferences/other suggestions?

**Comment by minimul** [comment]
Personally, I haven't used CDC yet. If you find this useful I think it will get merged
no problem but to answer your question I don't have any feedback.

**Comment by ruckus** [comment]
I havent used CDC either.

Option 2 seems like the least-surprise. At least it tells me there is nothing there. Option 1 would imply I asked about any Invoices that changed, but in the result the key was not present so I'd have to infer no changes. Not sure if it ultimately matters though.

Option 3 seems like an extension of Option 2. 

I dont have a good opinion either way on which is best.

Thanks for your work on this!!

**Comment by minimul** [comment]
I recently used the CDC service. I am of the opinion that the developer should handle the CDC output with custom parsing and no abstraction should be added to this library. Of course, PRs are welcome but closing for now.
