### ISSUE TITLE
Approach 1 to fetch results from Quickbooks is not working

### ISSUE THREAD

**Issue by lmatiolis** [ruckus/quickbooks-ruby#298]
The [first approach](https://github.com/ruckus/quickbooks-ruby#approach-1) to get results from Quickbooks is not working...

I saw that this was just merged, so I imagine it's not released yet?

Just checking... since you mentioned the second approach will be removed, I wanted to start refactoring here! :)

Thanks!

**Comment by ruckus** [comment]
Hi @lmatiolis - I un-merged this PR. You're right in that its currently non-functional in its current form.

For the time being forget about the PR and its business as usual.

Sorry for the confusion.

**Comment by lmatiolis** [comment]
No worries, @ruckus!

Thanks!
