### ISSUE TITLE
As_json and to_json

### ISSUE THREAD

**Issue by bendangelo** [ruckus/quickbooks-ruby#300]
```
      customers = service.all.first.as_json
```

Will go into an infinite loop and crash.

# /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:161:in `map'
     # /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:161:in `as_json'
     # /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:52:in `as_json'
     # /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:142:in `block in as_json'
     # /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:142:in `map'
     # /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:142:in `as_json'
     # /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:161:in `block in as_json'
     # /Users/ben/.rvm/gems/ruby-2.3.0@braavos/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/object/json.rb:161:in `each'

**Comment by minimul** [comment]
Any ideas of how to fix?

**Comment by bendangelo** [comment]
I just did this. 
`json = Hash.from_xml(found_invoice.to_xml.to_s).to_json`

**Comment by minimul** [comment]
Closed in https://github.com/ruckus/quickbooks-ruby/pull/302

**Comment by shir** [comment]
Looks like this issue appear again. I've updated to latest version 0.6.1 from 0.4.2 and get this issue with infinity `as_json`
