### ISSUE TITLE
Querying Item by Type doesn't appear to be working... 

### ISSUE THREAD

**Issue by lmatiolis** [ruckus/quickbooks-ruby#301]
To be fair, this looks more like an issue with the quickbooks api than with this gem, but just wanted to make sure. And of course, you will know better! ;)

I'm trying to get only the Items of type Service, but the query returns no matches:

```
pry(main)> item_service.find_by(:type, Quickbooks::Model::Item::SERVICE_TYPE)
I, [2016-03-04T10:07:34.133893 #10103]  INFO -- : ------ QUICKBOOKS-RUBY REQUEST ------
I, [2016-03-04T10:07:34.133956 #10103]  INFO -- : METHOD = get
I, [2016-03-04T10:07:34.133980 #10103]  INFO -- : RESOURCE = https://sandbox-quickbooks.api.intuit.com/v3/company/123145730024557/query?query=select+*+from+item+where+Type+%3D+%27Service%27+STARTPOSITION+1+MAXRESULTS+20&minorversion=4
I, [2016-03-04T10:07:34.134001 #10103]  INFO -- : REQUEST BODY:
I, [2016-03-04T10:07:34.134021 #10103]  INFO -- : {}
I, [2016-03-04T10:07:34.134052 #10103]  INFO -- : REQUEST HEADERS = {"Content-Type"=>"application/xml", "Accept"=>"application/xml", "Accept-Encoding"=>"gzip, deflate"}
I, [2016-03-04T10:07:36.642494 #10103]  INFO -- : ------ QUICKBOOKS-RUBY RESPONSE ------
I, [2016-03-04T10:07:36.642634 #10103]  INFO -- : RESPONSE CODE = 200
I, [2016-03-04T10:07:36.642695 #10103]  INFO -- : RESPONSE BODY:
I, [2016-03-04T10:07:36.643142 #10103]  INFO -- : <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2016-03-04T05:07:36.484-08:00">
  <QueryResponse/>
</IntuitResponse>

=> #<Quickbooks::Collection:0x00000006c78890 @count=0, @entries=[]>
```

If I just check the first entry querying for all:

```
pry(main)> item_service.all.first
=> #<Quickbooks::Model::Item id: 3, sync_token: 1, meta_data: {"create_time"=>2016-01-25 10:36:03 -0800, "last_updated_time"=>2016-01-28 12:47:47 -0800}, name: Concrete, sku: nil, description: Concrete for fountain installation, active?: true, sub_item?: nil, parent_ref: nil, level: nil, fully_qualified_name: Concrete, taxable?: true, sales_tax_included?: nil, unit_price: 0.0, rate_percent: nil, type: Service, income_account_ref: {"name"=>"Landscaping Services:Job Materials:Fountains and Garden Lighting", "value"=>"48", "type"=>nil}, purchase_desc: nil, purchase_tax_included?: nil, purchase_cost: 0.0, expense_account_ref: nil, asset_account_ref: nil, track_quantity_on_hand?: false, quantity_on_hand: nil, sales_tax_code_ref: nil, purchase_tax_code_ref: nil, inv_start_date: nil>
```

It shows I have items of type 'Service':

```
pry(main)> item_service.all.first.type
=> "Service"
```

So the gem appears to be building the correct query and issuing the correct request to filter by type, so I don't know what's going on.

Thanks in advance!

**Comment by muhammad-abubakar** [comment]
Yes this is an issue with the quickbooks API. I tested it extensively. Item filters are working on every other queryable field except service. I checked the `URL` using `url_for_query` method and it generates perfect URL.

**Comment by lmatiolis** [comment]
@muhammad-abubakar How you suggest we approach this? Do you know a way to contact Intuit about this?

Thanks!

**Comment by muhammad-abubakar** [comment]
I think only solution would be to contact Intuit. [https://developer.intuit.com/v2/help](https://developer.intuit.com/v2/helpl) Give them url and explain the problem. They will fix it or tell you a work around. I've heard that they are very responsive :-)

**Comment by muhammad-abubakar** [comment]
Mean while you can apply filter locally. Which is of course not ideal but only solution

**Comment by lmatiolis** [comment]
@muhammad-abubakar Yep, that's what I'm already doing here! ;)

**Comment by lmatiolis** [comment]
@muhammad-abubakar That link you provided is returning a 404... anyway, I'll find their contact here later and submit a question there as soon as I get some time.

I'll post here the outcome.

Thanks!

**Comment by minimul** [comment]
Closing. Bug on Intuit's side.
