### ISSUE TITLE
Creating TaxRate

### ISSUE THREAD

**Issue by guydu** [ruckus/quickbooks-ruby#304]
Hi,
I'm trying to create TaxRate via the TaxService - but it it keeps raising an error:
NoMethodError: undefined method `tax_rate_name' for #<Quickbooks::Model::TaxRateDetail:0x007f9ad4e8a910>

while and never use tax_rate_name. here is my TaxRateDetail :
#<Quickbooks::Model::TaxRateDetail tax_rate_ref: {"id"=>nil, "sync_token"=>nil, "meta_data"=>nil, "name"=>"name3", "description"=>"desc", "active?"=>nil, "rate_value"=>10, "agency_ref"=>{"name"=>nil, "value"=>3, "type"=>nil}, "tax_return_line_ref"=>nil, "special_tax_type"=>nil, "display_type"=>nil, "effective_tax_rate"=>nil}, tax_type_applicable: nil, tax_order: nil>

any idea what is it? maybe the gem doesn't support it yet?
Thanks!
Guy.

**Comment by minimul** [comment]
TaxService is supported: see here https://github.com/ruckus/quickbooks-ruby#json-support

That said, I don't use this implementation of TaxService in production so if it has some issues please jump in and do a PR.

But let me say this. If you are just getting started with the integration you might want to take a look at my gem `qbo_api` which is JSON-only from the ground up. https://github.com/minimul/qbo_api

**Comment by guydu** [comment]
Thanks for the quick response! btw your gem looks pretty awesome - started watching it ;)
Is there a way to specify that I want to use the json version rather than the XML version ?

Thanks!

**Comment by minimul** [comment]
re: specify
For quickbooks-ruby? See the specs on how to use the TaxService exactly.

**Comment by guydu** [comment]
Cool! that worked for me! thanks! =)
here is the link for future reference:
https://github.com/ruckus/quickbooks-ruby/blob/master/spec/lib/quickbooks/service/tax_service_spec.rb
