### ISSUE TITLE
Issue with apostrophes in queries

### ISSUE THREAD

**Issue by dheerajk3** [ruckus/quickbooks-ruby#309]
I came across a scenario where I need to query on ITEM for NAME with the Apostrophe. Basically apostrophe can be of two types( apostrophe ’ or Typewriter apostrophe ' ). when we use Typewriter apostrophe every thing seems to be Good, But when I query using normal apostrophe(which is not there in normal keyboard), code seem to break with this Error: "" Invalid content. Lexical error at line 1, column 43. Encountered: "\u2019" (8217), after : "\'%Fleur" ""

This is what I am using to escape Apostrophe:

Working with ' : 

```
util = Quickbooks::Util::QueryBuilder.new
clause1 = util.clause("NAME", "LIKE", "%Fleur't")
item_services.query("SELECT * FROM ITEM WHERE #{clause1}")
```

Not Working ’ :

```
util = Quickbooks::Util::QueryBuilder.new
clause1 = util.clause("NAME", "LIKE", "%Fleur’t")
item_services.query("SELECT * FROM ITEM WHERE #{clause1}")
```

Is there any fix for these kind of special characters? Thanks

![c811fdcc-bc8f-11e5-9d15-b9fab837ea82](https://cloud.githubusercontent.com/assets/10532799/14456852/a441168e-00c4-11e6-9cf9-2c23ecec741c.png)

**Comment by minimul** [comment]
Could you add support for this type of apostrophe.

Code: https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/util/query_builder.rb

Spec: https://github.com/ruckus/quickbooks-ruby/blob/master/spec/lib/quickbooks/util/query_builder_spec.rb
