### ISSUE TITLE
Bug in Deposit data model

### ISSUE THREAD

**Issue by dotcom900825** [ruckus/quickbooks-ruby#310]
I was trying to sync a `Deposit` record to QB, but the **customer** data is not syning over successfully. I also tried fetching the existing `Deposit` record from QB but the `DepositLineDetail` item is not filling out correctly as well. 

According to QB's [API doc](https://developer.intuit.com/docs/api/accounting/Deposit.), you should be able to pass in `DepositLineItem` record as deposit's line items. And for each `DepositLineItem`, you can specify the `DepositLineDetail` which contains `Entity` to represent the customer info. 

Here is the example response from QB API explorer when you try to fetch a deposit record with Customer info.
```
<Deposit domain="QBO" sparse="false">
    <Id>446</Id>
    <SyncToken>1</SyncToken>
    <MetaData>
      <CreateTime>2016-04-12T17:39:12-07:00</CreateTime>
      <LastUpdatedTime>2016-04-12T17:53:37-07:00</LastUpdatedTime>
    </MetaData>
    <TxnDate>2016-04-12</TxnDate>
    <CurrencyRef name="United States Dollar">USD</CurrencyRef>
    <PrivateNote>wxcv</PrivateNote>
    <Line>
      <Id>1</Id>
      <LineNum>1</LineNum>
      <Description>Trust Deposit</Description>
      <Amount>13.00</Amount>
      <DetailType>DepositLineDetail</DetailType>
      <DepositLineDetail>
        <Entity name="Nicole Tang" type="CUSTOMER">58</Entity>
        <AccountRef name="MC Trust Accounts - Liabilities">92</AccountRef>
        <PaymentMethodRef name="Credit Card">13</PaymentMethodRef>
      </DepositLineDetail>
    </Line>
    <TxnTaxDetail />
    <DepositToAccountRef name="Trust account">91</DepositToAccountRef>
    <TotalAmt>13.00</TotalAmt>
  </Deposit>
```

Since this deposit linked to a customer, in the 2nd line item, there is a **Entity** element in the DepositLineDetail tag. 

If we replace the Deposit model's xml fixture with this, the `Quickbooks::Model::Deposit.from_xml(xml)` won't able to parse the `Entity` correctly and instead return nil.

I wonder if this is an existing bug in the Gem?

**Comment by minimul** [comment]
I believe this was just fixed in pr #311. Grab master.
