### ISSUE TITLE
Issues creating PurchaseOrder

### ISSUE THREAD

**Issue by UnderpantsGnome** [ruckus/quickbooks-ruby#315]
It's a good possibility that I'm doing something wrong here, but I've been unable to track down anything on this. Any help or pointers to some working examples would be great.

Thanks

Here's the code building the PO.

    po = PurchaseOrder.find(purchase_order_id)

    qb_po = Quickbooks::Model::PurchaseOrder.new(
      po_status: 'Open',
      doc_number: po.id,
      total_amount: po.total
    )

    qb_po.meta_data = {
      create_time: Time.now,
      last_updated_time: po.updated_at
    }

    qb_po.ap_account_ref = {
      value: 33,
      name: 'Accounts Payable (A/P)'
    }

    network_contact = po
      .originator
      .network_contacts
      .find_by_contact_id(po.supplier.id)

    qb_po.vendor_ref = {
      value: network_contact.quickbooks_id,
      name: network_contact.contact.name
    }

    lines = [].tap do |lines|
      po.line_items.each do |line_item|
        line = Quickbooks::Model::PurchaseLineItem.new

        line.amount = line_item.total_price
        line.detail_type = 'ItemBasedExpenseLineDetail'

        # this just looks up an existing Item to use the ID
        # or returns an unsaved one to be created on save
        item = find_or_create_line_item(line_item)

        line.item_based_expense! do |detail|
          detail.billable_status  = 'NonBillable'
          detail.unit_price = line_item.unit_price
          detail.quantity = line_item.quantity
          detail.item_ref = {
            value: item.id,
            name: item.name,
            description: item.description,
            amount: line_item.total_price
          }
        end

        lines << line
      end
    end

    qb_po.line_items = lines

    service = QuickBooks.get_service(po.originator, Quickbooks::Service::PurchaseOrder)
    created_qb_po = service.create(qb_po)

Here's the JSON it's building.

    {"line_items"=>
      [{"amount"=>"12345.0",
        "detail_type"=>"ItemBasedExpenseLineDetail",
        "item_based_expense_line_detail"=>
         {"billable_status"=>"NonBillable",
          "item_ref"=>
           {"value"=>nil,
            "name"=>"ABC-123",
            "description"=>"This is the description for ABC-123",
            "amount"=>"12345.0"},
          "unit_price"=>"123.45",
          "quantity"=>"100.0"}},
       {"amount"=>"4567.0",
        "detail_type"=>"ItemBasedExpenseLineDetail",
        "item_based_expense_line_detail"=>
         {"billable_status"=>"NonBillable",
          "item_ref"=>
           {"value"=>nil,
            "name"=>"ABC-124",
            "description"=>"This is the description for ABC-124",
            "amount"=>"4567.0"},
          "unit_price"=>"45.67",
          "quantity"=>"100.0"}}],
     "ap_account_ref"=>{"value"=>33, "name"=>"Accounts Payable (A/P)"},
     "vendor_ref"=>{"value"=>35, "name"=>"Computers by Jenni"},
     "total"=>"16912.0",
     "po_status"=>"Open",
     "meta_data"=>
      {"create_time"=>"2016-04-20T14:11:39.421-05:00",
       "last_updated_time"=>"2016-04-19T11:37:32.021-07:00"},
     "doc_number"=>6}

And here's the error, all of those numbers look sane to me

    Quickbooks::IntuitRequestException: Invalid NumberInvalid NumberInvalid NumberInvalid Number:
      Invalid Number : <?xml version="1.0" encoding="UTF-8"?>
    <hash>
      <value nil="true"/>
      <name>ABC-123</name>
      <description>This is the description for ABC-123</description>
      <amount type="decimal">12345.0</amount>
    </hash>
    Invalid Number : <?xml version="1.0" encoding="UTF-8"?>
    <hash>
      <value nil="true"/>
      <name>ABC-124</name>
      <description>This is the description for ABC-124</description>
      <amount type="decimal">4567.0</amount>
    </hash>
    Invalid Number : <?xml version="1.0" encoding="UTF-8"?>
    <hash>
      <value type="integer">35</value>
      <name>Computers by Jenni</name>
    </hash>
    Invalid Number : <?xml version="1.0" encoding="UTF-8"?>
    <hash>
      <value type="integer">33</value>
      <name>Accounts Payable (A/P)</name>
    </hash>

**Comment by ruckus** [comment]
Interesting. How are you generating the JSON? The library itself uses XML.

Anyways, I haven't encountered this before. But my first thought is that your numbers are sent as strings. By looking at the JSON (again, not what would be sent)

```json
"amount"=>"12345.0"},
"unit_price"=>"123.45",
"quantity"=>"100.0"}},
```

Quoted strings around the numbers.

You'd think Intuit would be smart enough to parse those as numbers - maybe thats why its barfing? Maybe it really does want quote-less numbers? Just an idea.

**Comment by UnderpantsGnome** [comment]
@ruckus the JSON was output via [#as_json](https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/model/base_model.rb#L30-L36) 

I've found most BIg Company APIs are rarely smart enough to figure things out 😏 

Thanks for taking a look.

Here is some raw logging data using `Quickbooks.log = true` this is the request and error response.

    I, [2016-04-20T20:29:07.849551 #77308]  INFO -- : ------ QUICKBOOKS-RUBY REQUEST ------
    I, [2016-04-20T20:29:07.849589 #77308]  INFO -- : METHOD = post
    I, [2016-04-20T20:29:07.849603 #77308]  INFO -- : RESOURCE = https://sandbox-quickbooks.api.intuit.com/v3/company/123145749462197/purchaseorder
    I, [2016-04-20T20:29:07.849615 #77308]  INFO -- : REQUEST BODY:
    I, [2016-04-20T20:29:07.849841 #77308]  INFO -- : <?xml version="1.0" encoding="utf-8"?>
    <PurchaseOrder xmlns="http://schema.intuit.com/finance/v3" sparse="false">
    <MetaData>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;create-time type="dateTime"&gt;2016-04-19T11:37:31-07:00&lt;/create-time&gt;
      &lt;last-updated-time type="dateTime"&gt;2016-04-19T11:37:32-07:00&lt;/last-updated-time&gt;
    &lt;/hash&gt;
    </MetaData>
    <DocNumber>6</DocNumber>
    <TxnDate>2016-04-19 11:37:31 -0700</TxnDate>
    <Line>
    <Amount>12345.0</Amount>
    <DetailType>ItemBasedExpenseLineDetail</DetailType>
    <ItemBasedExpenseLineDetail>
    <ItemRef>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value nil="true"/&gt;
      &lt;name&gt;ABC-123&lt;/name&gt;
      &lt;description&gt;This is the description for ABC-123&lt;/description&gt;
      &lt;amount type="decimal"&gt;12345.0&lt;/amount&gt;
    &lt;/hash&gt;
    </ItemRef>
    <UnitPrice>123.45</UnitPrice>
    <Qty>100.0</Qty>
    <BillableStatus>NonBillable</BillableStatus>
    </ItemBasedExpenseLineDetail>
    </Line>
    <Line>
    <Amount>4567.0</Amount>
    <DetailType>ItemBasedExpenseLineDetail</DetailType>
    <ItemBasedExpenseLineDetail>
    <ItemRef>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value nil="true"/&gt;
      &lt;name&gt;ABC-124&lt;/name&gt;
      &lt;description&gt;This is the description for ABC-124&lt;/description&gt;
      &lt;amount type="decimal"&gt;4567.0&lt;/amount&gt;
    &lt;/hash&gt;
    </ItemRef>
    <UnitPrice>45.67</UnitPrice>
    <Qty>100.0</Qty>
    <BillableStatus>NonBillable</BillableStatus>
    </ItemBasedExpenseLineDetail>
    </Line>
    <VendorRef>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value type="integer"&gt;35&lt;/value&gt;
      &lt;name&gt;Computers by Jenni&lt;/name&gt;
    &lt;/hash&gt;
    </VendorRef>
    <APAccountRef>&lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value type="integer"&gt;33&lt;/value&gt;
      &lt;name&gt;Accounts Payable (A/P)&lt;/name&gt;
    &lt;/hash&gt;
    </APAccountRef>
    <TotalAmt>16912.0</TotalAmt>
    <POStatus>Open</POStatus>
    </PurchaseOrder>

    I, [2016-04-20T20:29:07.850108 #77308]  INFO -- : REQUEST HEADERS = {"Content-Type"=>"application/xml", "Accept"=>"application/xml", "Accept-Encoding"=>"gzip, deflate"}
    I, [2016-04-20T20:29:08.236951 #77308]  INFO -- : ------ QUICKBOOKS-RUBY RESPONSE ------
    I, [2016-04-20T20:29:08.237028 #77308]  INFO -- : RESPONSE CODE = 400
    I, [2016-04-20T20:29:08.237070 #77308]  INFO -- : RESPONSE BODY:
    I, [2016-04-20T20:29:08.237570 #77308]  INFO -- : <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2016-04-20T18:29:08.177-07:00">
      <Fault type="ValidationFault">
        <Error code="2090" element="Line.ItemBasedExpenseLineDetail.ItemRef.value">
          <Message>Invalid Number</Message>
          <Detail>Invalid Number : &lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value nil="true"/&gt;
      &lt;name&gt;ABC-123&lt;/name&gt;
      &lt;description&gt;This is the description for ABC-123&lt;/description&gt;
      &lt;amount type="decimal"&gt;12345.0&lt;/amount&gt;
    &lt;/hash&gt;
    </Detail>
        </Error>
        <Error code="2090" element="Line.ItemBasedExpenseLineDetail.ItemRef.value">
          <Message>Invalid Number</Message>
          <Detail>Invalid Number : &lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value nil="true"/&gt;
      &lt;name&gt;ABC-124&lt;/name&gt;
      &lt;description&gt;This is the description for ABC-124&lt;/description&gt;
      &lt;amount type="decimal"&gt;4567.0&lt;/amount&gt;
    &lt;/hash&gt;
    </Detail>
        </Error>
        <Error code="2090" element="VendorRef.value">
          <Message>Invalid Number</Message>
          <Detail>Invalid Number : &lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value type="integer"&gt;35&lt;/value&gt;
      &lt;name&gt;Computers by Jenni&lt;/name&gt;
    &lt;/hash&gt;
    </Detail>
        </Error>
        <Error code="2090" element="APAccountRef.value">
          <Message>Invalid Number</Message>
          <Detail>Invalid Number : &lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;hash&gt;
      &lt;value type="integer"&gt;33&lt;/value&gt;
      &lt;name&gt;Accounts Payable (A/P)&lt;/name&gt;
    &lt;/hash&gt;
    </Detail>
        </Error>
      </Fault>
    </IntuitResponse>

**Comment by ruckus** [comment]
strange how the log output switches from escaped to un-escaped XML?

**Comment by ruckus** [comment]
My guess this is causing problems:

```
    line.item_based_expense! do |detail|
      detail.billable_status  = 'NonBillable'
      detail.unit_price = line_item.unit_price
      detail.quantity = line_item.quantity
      detail.item_ref = {
        value: item.id,
        name: item.name,
        description: item.description,
        amount: line_item.total_price
      }
    end
```
Any `ref=` assignment expects a full-fledged model instance and not a hash. Furthermore, assigning `amount` at the `Item` level seems odd.

I think you want something more like:

```ruby
line.amount = line_item.total_price
line.item_based_expense! do |detail|
  detail.billable_status  = 'NonBillable'
  detail.unit_price = line_item.unit_price
  detail.quantity = line_item.quantity  
  detail.item_id = item.id # this will use the item_ref setter
end
```

Notice that I moved the `line.amount` out from the block as well

**Comment by UnderpantsGnome** [comment]
Thanks that and changing the other _ref setters seems to have fixed my issue.

Thanks again for all the work you've put in on this gem.
