### ISSUE TITLE
Issue regards creating Item on Quickbooks.

### ISSUE THREAD

**Issue by gurmindersingh42** [ruckus/quickbooks-ruby#318]
I am integrating the Quickbooks online in existing web application build in ROR. While creating product from the web application to the quickbooks, we are getting error regarding the "IncomeAccountRef". We are having the concern regarding its type. Do we need to send only the ID for the account along with other params.
Here is the code we are using to upload the product  
	product = Quickbooks::Model::Item.new
	product.type = "NonInventory"
	product.name = @product.name
	product.active = true
	product.fully_qualified_name = @product.name
	product.description = @product.description
	product.quantity_on_hand = @product.units_in_stock			
	product.income_account_ref = {:value => "81" , :name=> "Inventory Asset"}
	service.create(product)

income_account_ref is a mandatory field. Please let us know the datatype for the income_account_ref so that we can proceed. With this code it is giving the invalid number error and when we pass the integer it is giving the xml error.
Are we passing the wrong income account refernce?

Here is the error message i am getting:
Invalid Number: Invalid Number : <?xml version="1.0" encoding="UTF-8"?> <hash> <value>48</value> <name>Sales of Product Income</name> </hash>

**Comment by minimul** [comment]
Do this:
```ruby
product.income_account_ref = Quickbooks::Model::BaseReference.new(81, name: 'Inventory Asset')
```

**Comment by gurmindersingh42** [comment]
Thanks.
This worked for me perfectly.
