### ISSUE TITLE
Adding the shipping fee to the invoice.

### ISSUE THREAD

**Issue by gurmindersingh42** [ruckus/quickbooks-ruby#319]
Is there any option in the quickbooks-ruby gem to add the shipping address to the invoice?

**Comment by minimul** [comment]
Your issue title and comment ask 2 different things:

**Adding a shipping fee:**
To add a shipping fee make a new line item with the ItemRef pointing to the Shipping Item id then you don't have to include the quantity and rate.
e.g.
```json
        "Amount": 2.00,
        "DetailType": "SalesItemLineDetail",
        "SalesItemLineDetail": {
          "ItemRef": {
            "value": "SHIPPING_ITEM_ID"
          }
        }
      }
```

The end invoice will look something [like this](https://d2gcv4sxt84gxu.cloudfront.net/uploads/assets/43177/original.png?1454628611).

This gem supports this.

**Adding a shipping address to an invoice.** Yes this gem [supports that as well](https://github.com/ruckus/quickbooks-ruby/blob/master/spec/lib/quickbooks/model/invoice_spec.rb).

**Comment by gurmindersingh42** [comment]
My requirement is regarding the addition of Shipping Fee. Do we need to initialize and shipping class to submit the shipping fee. As we do while adding the tax. e.g.
Quickbooks::Model::TransactionTaxDetail.new
How to initialize the object for shippig Fee?

**Comment by gurmindersingh42** [comment]
I am not able to add the shipping fee in the above mentioned way.

**Comment by minimul** [comment]
Let see the code. Errors. Need details.

**Comment by gurmindersingh42** [comment]
Here is the code i am using to create the invoice. However i am not able to find the class to add the shipping to the invoice as we are adding the tax and discount in the below code. Please let me know what class to initialize with and where to pass that params in the invoice object.

**def set_discount_line(discount_amount)
discount_line_item = Quickbooks::Model::InvoiceLineItem.new
discount_line_item.amount = discount_amount
discount_line_item.discount_item! do |detail|
detail.discount_account_id = 86
end
discount_line_item
end

def set_transaction_tax(tax_amount)
transaction = Quickbooks::Model::TransactionTaxDetail.new
transaction.txn_tax_code_id = 2 # TaxRate e.g. "Sales Tax" in sandbox
transaction.total_tax = tax_amount
transaction
end

line_item = Quickbooks::Model::InvoiceLineItem.new
line_item.amount = cost
line_item.description = o_l.product.description
line_item.sales_item! do |detail|
detail.unit_price = unit_price_order
detail.quantity = o_l.quantity
detail.item_id = o_l.product.quickbook_product_id
detail.tax_code_id = 'TAX'
end
quickbook_invoice.line_items << line_item

# add discount
quickbook_invoice.line_items << set_discount_line(@invoice.discount)

#add tax	
quickbook_invoice.txn_tax_detail = set_transaction_tax(@invoice.tax_charge)

#add shipping			       


#save the invoice
service = Quickbooks::Service::Invoice.new
service.company_id = @quickbook_setting.realm_id
service.access_token = @access_token 								
quickbook_invoice = service.create(quickbook_invoice)**

**Comment by minimul** [comment]
A shipping cost line item would look like this:
```
line_item.sales_item! do |detail|
 detail.item_id = SHIPPING_ITEM_ID
end
```

**Comment by gurmindersingh42** [comment]
This was helpful. I am not able to adding the shipping fee. Thanks.

**Comment by minimul** [comment]
Was that "not" or meant to be "now"?

**Comment by chileap** [comment]
@minimul when I added that line item, it also add one more role in invoice too.

here is my code
```
line_item = Quickbooks::Model::InvoiceLineItem.new
line_item.amount = order["base_shipping_amount"]
tax_code_no_id = tax_code_service.find_by(:name, 'Exempt').entries.first.id

line_item.sales_item! do |detail|
  detail.item_id = 'SHIPPING_ITEM_ID'
  detail.tax_code_ref = Quickbooks::Model::BaseReference.new("#{tax_code_no_id}")
end
sales_receipt_model.line_items << line_item
```

**Comment by kirit-pendyala** [comment]
Hi @minimul 

I'm having the same issue with adding the shipping cost to the invoice. Following is my code


`
                       $invoiceBody['Line'][0]["DetailType"] = "SalesItemLineDetail";
			$invoiceBody['Line'][0]["Amount"] = $totalPrice;
			$invoiceBody['Line'][0]["SalesItemLineDetail"]["Qty"] = $request->buyer_quantity;
			$invoiceBody['Line'][0]["SalesItemLineDetail"]["UnitPrice"] = $unitPrice;
			$invoiceBody['Line'][0]["SalesItemLineDetail"]["ItemRef"]["value"] = $product->quickbooks_id;
			// $invoiceBody['ShippingLineDetail'] = $request->shipping_clearing;
			$invoiceBody['Line'][0]["SalesItemLineDetail"]["ItemRef"]["Shipping"]["value"] = $request->shipping_clearing;`
			
			
	Please correct me, Where I'm doing wrong?
