### ISSUE TITLE
Subscription for company has lapsed or Invalid destination URL is used. Sandbox company works with Sandbox URL and Production company works with Production URL.; errorCode=007001; statusCode=400",

### ISSUE THREAD

**Issue by sachin-7777** [ruckus/quickbooks-ruby#321]
Hi minimul,
Subscription for company has lapsed or Invalid destination URL is used. Sandbox company works with Sandbox URL and Production company works with Production URL.; errorCode=007001; statusCode=400",
In node.js i tried through Rest API as well as using module but couldnt do in right way,how to pass oauth parameter in both type of scenario

**Comment by minimul** [comment]
Let's see the request

**Comment by sachin-7777** [comment]
Hi this is my request---
this.execute = function(input,output) {
        request({
            oauth: {
                consumer_key        : input._oauth.consumer_key,
                consumer_secret     : input._oauth.consumer_secret,
                token               : input._oauth.access_token,
                token_secret        : input._oauth.access_secret_token
            },
            headers: {
                "Content-Type": "application/json",
                "User-Agent": "APIExplorer",
            },
            url : "https://quickbooks.api.intuit.com/v3/company/"+input.company_id +"/customer/"+input.employee_id,
            method : "GET"

        },function(err,response,body){
          
            if(err){
                return output(err);
            }
            else{
                if(response.statusCode && response.statusCode >=200 && response.statusCode < 400){

                    if (typeof(body) == 'string') {
                        body = JSON.parse(body);
                    }
                    return output(null, body);
                }
                output(body);
            }
        })
    };
