### ISSUE TITLE
service.query() arguments 

### ISSUE THREAD

**Issue by michaelchewy17** [ruckus/quickbooks-ruby#323]
I am trying to retrieve Trialbalance results from different periods. How would I retrieve a trial balance ending at a specified date "one_year_ago"?

The code:  
tb = service.query('TrialBalance', start_date, one_year_ago) 

produces the error: 
undefined method `each' for "2015-06-20":String

**Comment by ruckus** [comment]
To construct a query which uses a custom-timeframe you need to construct an actual SQL-like query. In other words, filter params are not specified as key/value pairs.

See this section in the docs which constructs a query for customers in the given time-frame

https://github.com/ruckus/quickbooks-ruby#pagination

For convenience methods on building queries you might also want to check out:

https://github.com/ruckus/quickbooks-ruby#query-building--filtering
