### ISSUE TITLE
Auth. error on attempt to download invoice PDF

### ISSUE THREAD

**Issue by neilberkman** [ruckus/quickbooks-ruby#324]
When trying to download a PDF following the sample code [here](https://github.com/ruckus/quickbooks-ruby/blob/master/README.md#download-pdf-of-an-invoice-or-salesreceipt) I'm getting:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2016-06-25T13:26:41.968-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="AUTHENTICATION">
        <Error code="3200">
            <Message>message=ApplicationAuthenticationFailed; errorCode=003200; statusCode=401</Message>
        </Error>
    </Fault>
</IntuitResponse>
```

This is immediately after having successfully created an Invoice using the same `Quickbooks::Service::Invoice` instance.  I've tried this with both production and development keys, and with sandbox and production companies.  Is it possible that the `pdf` method is broken at the moment?

**Comment by ruckus** [comment]
Thats odd, working fine for me. Try again now? Maybe it was an intermittent issue on Intuit's side?

**Comment by neilberkman** [comment]
Unfortunately I'm still seeing the same response today.  Again, the invoice is created successfully and an attempt to call the `pdf` method using the same `Quickbooks::Service::Invoice` instance immediately after fails.

There's some extra detail in the message I get when I run against a sandbox company:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse time="2016-06-27T11:27:05.674-07:00" xmlns="http://schema.intuit.com/finance/v3">
    <Fault type="AUTHENTICATION">
        <Error code="3200">
            <Message>message=ApplicationAuthenticationFailed; errorCode=003200; statusCode=401</Message>
            <Detail>SignatureBaseString: GET&amp;https%3A%2F%2Fsandbox-quickbooks.api.intuit.com%2Fv3%2Fcompany%2F******%2Finvoice%2Fpdf&amp;oauth_consumer_key%3D*********%26oauth_nonce%*********%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1467052024%26oauth_token%3D********O7%26oauth_version%3D1.0</Detail>
        </Error>
    </Fault>
</IntuitResponse>
```

**Comment by ruckus** [comment]
I'm wondering if this is an issue with a freshly created invoice?

To narrow down the problem, try generating a PDF for a known and retrieved invoice. Try something like this:

```ruby
invoices = invoice_service.query # this will retrieve the first page of invoices
invoice = invoices.entries.last
data = invoice_service.pdf(invoice)
File.open("foo.pdf", "wb") { |f| f.write(data) }
```

If that works, then it means that someone thing about a freshly created invoice is lacking the parameters needed. We know its `id` is set.. which is presumably all the PDF endpoint needs...

https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/service/invoice.rb#L21

hmm....

**Comment by neilberkman** [comment]
The problem was on my end.  I had something like: 

``` ruby
invoice_service = Quickbooks::Service::Invoice
invoice = Quickbooks::Model::Invoice.new
[...]
created_invoice = invoice_service.create(invoice)
invoice_service.pdf(invoice)
```

I switched this to `invoice_service.pdf(created_invoice)` and it works fine now.  The auth error confused me but I should have been able to figure this out.  Thanks for your help!
