### ISSUE TITLE
Idea: Query Cache

### ISSUE THREAD

**Issue by hubrix** [ruckus/quickbooks-ruby#326]
The Quickbooks API is slow and often glitchy. I've implemented one-off caching for some things we query for but have been thinking about implementing a query/result cache/memoization mechanism at a lower level. Would like to get people's thoughts on the idea before I commit a pull request that no one likes.

**Comment by minimul** [comment]
I'd like to see what you've done. Can you post some snippets? That way you don't have to invest the time in a PR.

**Comment by hubrix** [comment]
I can post some snippets a bit later but the basic ones I have done is
cache single objects retrieved from queries or the complete result set for
exact query matches. It helps make for easier loop construction without
having to think about whether I have this object somewhere or not. I do
this at the service level and abstract the query into a function like
bill_service_query(QBQL) and return a cached result if the query matches
exactly unless a force parameter is added. The correct way is to clear the
cache when an insert update or delete is done by the service

**Comment by ruckus** [comment]
Interesting proposal. My first thought is that its outside the scope of the library. But we can all agree that the QB API is flaky, so if there is some way to smooth over those wrinkles it might not be a bad idea.

In terms of caching - this is the vietnam of computer science. Would the cache repository be 3rd party (e.g. redis, memcached) or would it be in-process? The latter means that in a distributed environment each process running the library would have its own cache - so there is that stale issue. 

I'm not saying no to your idea, I really appreciate your spirit. I think there could be subtle complications.

**Comment by minimul** [comment]
Yes, I agree that this cache pattern is outside the scope of the gem. 

Note: Caching say a `Bill` query in the fashion described doesn't take into a account if the user has modified/created/deleted a `Bill` on QBO itself. In this case you want a webhook or CDC query to clear the cache as well.

QBO API flakiness doesn't hurt as much on data query's but for creation, modification, and deletes they can: take a look at [implementing](https://github.com/ruckus/quickbooks-ruby/issues/256) [`requestid`](https://developer.intuit.com/hub/blog/2015/04/06/15346)
