### ISSUE TITLE
Upgrading OAuth

### ISSUE THREAD

**Issue by drewish** [ruckus/quickbooks-ruby#329]
I'm curious if there's a reason you're not using the 0.5.x release of the oauth gem. I'd like to use a newer version to get access to the rest-client proxy.

**Comment by ruckus** [comment]
Good question. I dont remember the exact details but I do remember it that version of the OAuth gem playing nicely with multipart uploads - which we do here:

https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/util/multipart.rb

At the time of developing the multipart stuff I had tried later version of the gem and I was running into issues. 

But that was awhile ago and could very well be resolved. Its probably worth looking into:

1. Updating to latest OAuth gem version
2. Attempting an Attachable upload

If it works then we potentially no reason why we cannot upgrade across the board.

**Comment by drewish** [comment]
Thanks, I'll spend a little time testing that in the next week or two. I need to wrap up some other tasks before I get back to this.

**Comment by drewish** [comment]
I'm going to close this. The new OAuth stuff seems pretty buggy and I don't want to spend the time debugging it.
