### ISSUE TITLE
Getting invoice url from api?

### ISSUE THREAD

**Issue by mmahalwy** [ruckus/quickbooks-ruby#334]
I'd like to reference an invoice on their site, for example

`https://sandbox.qbo.intuit.com/app/invoice?txnId=67` given that I have invoice id `67` saved. How can I get the url of their quickbooks?

**Comment by ruckus** [comment]
Do you mean the URL of the Invoice PDF?

If so, have a look at this method which returns the actual PDF.

https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/service/invoice.rb#L20

You could inspect the URL that is generated and then note it for later reference.

Given that you have the Invoice ID it might be somewhat wasteful to fetch the `Invoice` instance just so you can pass it to the PDF `invoice()` method, so we should probably update this method to be smart about taking either an `Invoice` object or a `String/Integer` which represents an Invoice ID.

In the meantime you could hack it like this:

```ruby
invoice_id = 67
s = Struct.new(:id)
invoice_mock = s.new(invoice_id)

service.pdf(invoice_mock)
```

**Comment by ruckus** [comment]
Thanks for the information; it will definitely be helpful for others.
