### ISSUE TITLE
Any plans for supporting the Item bundles; for Invoices, etc?!

### ISSUE THREAD

**Issue by florinpatrascu** [ruckus/quickbooks-ruby#335]
Hi there,

Are there any plans, or works in progress, for supporting the [item bundles](https://developer.intuit.com/docs/0100_quickbooks_online/0200_dev_guides/accounting/item_bundles_using_groups)?

If not, what would be the suggested approach for dealing with invoices containing bundles.

Thank you,
Florin

**Comment by lev** [comment]
+1

**Comment by florinpatrascu** [comment]
My Ruby is a bit rusty but I started yesterday to add the support for understanding the new Invoice line items of type `GroupLineDetail`. These are the item bundles. The work so far is in my fork, here: [1ff2761](https://github.com/florinpatrascu/quickbooks-ruby/commit/1ff2761a3092b54209c3c71dd917b08b8ca62b40), for now. Also added the tests for validating the new functionality ([lib/quickbooks/service/invoice_spec.rb:248](https://github.com/florinpatrascu/quickbooks-ruby/blob/1ff2761a3092b54209c3c71dd917b08b8ca62b40/spec/lib/quickbooks/service/invoice_spec.rb#L248)) and will attempt to continue this work so that I can also create invoices with bundles, and sparse update the bundle line items, for existing invoices. Any feedback is more than welcome. HTH - Florin

**Comment by florinpatrascu** [comment]
finished the support for the Item Bundles. Now I can create invoices containing Bundles. The code is in my fork at: [florinpatrascu/quickbooks-ruby](https://github.com/florinpatrascu/quickbooks-ruby), and I need to run few more tests and eventually cleanup up some code, before sending a PR.

**Comment by florinpatrascu** [comment]
Supported starting with version 0.4.5. Thank you for accepting the PR.
