### ISSUE TITLE
Rails Questions

### ISSUE THREAD

**Issue by mastertechrv** [ruckus/quickbooks-ruby#337]
How can I implement an alert to notify that if a record is created and it already exists in QBO, how can I alert saying that the record already exists, I tried creating a record and it failed so I looked at the production(development) logs and the response from QBO said that customer already exists, so how can I display and alert telling that a record already exists. 

Also, I was reading through the readme and you said something about Persisting Credentials, how can I implement that into my app?

**Comment by minimul** [comment]
You are going to have a to catch the error. Look at the [code](https://github.com/minimul/qbo_rails/blob/master/lib/qbo_rails.rb) in the [qbo-rails gem](https://github.com/minimul/qbo_rails).

**Comment by ruckus** [comment]
Thanks @minimul for chiming in. @minimul is correct in that this is application-specific. QB enforces uniqueness on QB Item Name or Customer Name, etc. Its purely up to you how you handle these conflicts. This library makes zero assumptions in that regard.
