### ISSUE TITLE
Employee API Endpoints for Payroll

### ISSUE THREAD

**Issue by garethburrows** [ruckus/quickbooks-ruby#340]
This is not an issue with the quickbooks-ruby gem per se, but I suspect someone will find this when pulling their hair out and it might be useful.

Please note that Quickbooks purchased and bolted on their payroll solution rather than developing it, and the structure for Employee information with payroll enabled is completely different than that for Employee information when payroll is not enabled. 

This means if you have a working application talking to the Employee API endpoints and someone enables payroll for their company in Quickbooks online, carnage will ensue. As the original API endpoints for Employees will still exist, your code may appear to continue to work without errors, but the result will not be reflected in the Quickbooks UI as that is now looking at a different set of data.

**Comment by florinpatrascu** [comment]
Good to know, thank you!

**Comment by minimul** [comment]
Yes, QB integration hair pulling is very bad for our appearances.
Thanks much for sharing.
