### ISSUE TITLE
No Logged In event?

### ISSUE THREAD

**Issue by amerritt14** [ruckus/quickbooks-ruby#342]
Following the tutorial http://minimul.com/integrating-rails-and-quickbooks-online-via-the-version-3-api-part-1.html and the ReadMe.

The screencast mentions checking the QB log to see that the login has occurred. I don't get a login note on my Audit log. I also don't show any active connections that need to be disconnected in the developer side.

Logging in is redirecting back to my home page with the "Your QuickBooks account has been successfully linked." message.

Any help would be appreciated.

**Comment by minimul** [comment]
Are you getting the OAuth credentials back after logging in?

Are you looking at the Audit log of the correct sandbox?

**Comment by amerritt14** [comment]
This is what I'm showing in my server log.

`Started GET "/users/authenticate" for ::1 at 2016-11-16 07:35:31 -0500
Processing by UsersController#authenticate as HTML
Redirected to https://appcenter.intuit.com/Connect/Begin?oauth_token=q...Z
Completed 302 Found in 472ms (ActiveRecord: 0.0ms)

Started GET "/users/oauth_callback?oauth_token=q...Z&oauth_verifier=f...s&realmId=1...9&dataSource=QBO" for ::1 at 2016-11-16 07:35:47 -0500
Processing by UsersController#oauth_callback as HTML
  Parameters: {"oauth_token"=>"q...Z", "oauth_verifier"=>"f...s", "realmId"=>"1...9", "dataSource"=>"QBO"}
Redirected to http://localhost:3000/
Completed 302 Found in 469ms (ActiveRecord: 0.0ms)`

This is my first attempt at using OAuth, but I think there should have been a POST message with an Access Token if the the connection was authorized, correct?
As far as the audit log, I only have one sandbox, and I've double checked that it's the same one that I'm attempting to connect with.

**Comment by minimul** [comment]
You are getting the OAuth info back correctly so I wouldn't to be too
concerned about the Audit log. I did that tutorial probably almost 3 years
ago.
