### ISSUE TITLE
Dealing with Net::ReadTimeout during batch save

### ISSUE THREAD

**Issue by drewish** [ruckus/quickbooks-ruby#343]
I've been running into some `Net::ReadTimeout` exceptions when saving batches of records. I'm not sure what the default timeout is but with 30 records it happens pretty frequently, dropping it down to 10 records cuts it down considerably. 

It looks like a simple retry strategy will result in duplicate records (I was surprised to learn that QBO doesn't seem to have many unique indexes). I'm curious what folks do to deal with this. Do you catch exceptions then search for the submitted values to see if any records saved? Anyone spent time figuring out how to extend the timeouts in the OAuth client?

**Comment by drewish** [comment]
I finally came across the [`requestid` parameter](https://developer.intuit.com/docs/0100_quickbooks_online/0300_references/rest_essentials_for_the_quickbooks_api#Request_id) in the docs:
> The request ID uniquely identifies the HTTP request sent from the app to the service. It enables the app to correlate requests and responses in case the app needs to resend a request because of a dropped connection or other situation in which a write, modify, or delete request has been sent, but no response received. Use of the request ID is strongly recommended for any request that writes, modifies, or deletes data as it guarantees idempotency of the request. 

I found https://github.com/ruckus/quickbooks-ruby/issues/256 which added that to the invoice creation but it doesn't seem like it was applied to the batch service. I'll open up a PR to address that.

**Comment by drewish** [comment]
Just for reference here's how I'm using it:
```rb
  def batch_it
    request = Quickbooks::Model::BatchRequest.new

    # ... build the batch

    service = Quickbooks::Service::Batch.new(auth)
    # Keep the requestid consistent across retries so we get the same response
    # on timeouts.
    options = {query: {requestid: SecureRandom.urlsafe_base64(32)}}
    response = execute_with_retries do
      service.make_request(request, options)
    end

    # ... read out the responses
  end

  # Pass a block in and it'll be retried for network issues or hitting the rate
  # limit.
  def execute_with_retries tries: 3
    remaining = tries

    yield

  rescue Net::ReadTimeout, Quickbooks::ThrottleExceeded => e
    if (remaining -= 1) > 0
      if e.is_a? Quickbooks::ThrottleExceeded
        nap_time = rand(15..30)
        logger.info "Hit the rate limit, sleeping for #{nap_time} seconds."
        sleep nap_time
      else
        logger.info "Hit #{e} error but will try again #{tries} more times."
      end

      retry
    else
      logger.info "Made #{tries} tries to avoid the rate limit. Aborting"

      raise
    end
  end
```

**Comment by bcackerman** [comment]
So the play here is to retry until it works?

**Comment by bcackerman** [comment]
@drewish @minimul what do you guys recommend?

**Comment by drewish** [comment]
I recommend the sample code posted.
