### ISSUE TITLE
Backslash at the end not getting escaped properly when syncing over object to QB

### ISSUE THREAD

**Issue by dotcom900825** [ruckus/quickbooks-ruby#345]
I was using the `Quickbooks::Util::QueryBuilder` to constuct query for the ServiceItem model on QuickBooks.

Here is my code snippet:
```
    util = Quickbooks::Util::QueryBuilder.new
    name_clause = util.clause('Name', '=', item_name)
    items = item_service.query("select * from item where #{name_clause}")
```

If my item_name contains a backslash at the end for example: `Case preparation b\`, and when I try to execute the query, it will give me an exception: 

```
Quickbooks::IntuitRequestException: Error parsing query: QueryParserError: Invalid content. Lexical error at line 1, column 98.  Encountered: <EOF> after : "\'Case preparation  b\\\' STARTPOSITION 1 MAXRESULTS 20"
```

Is working fine if the backslash is not the very last character within the query

**Comment by ruckus** [comment]
Is there a literal backslash in your ItemService name record or is that a manifestation of your search query? 

Put another way, is the actual value in QBO of your ItemService something like `Case preparation b\foobar` ?

**Comment by dotcom900825** [comment]
It's a literal backslash within the ItemService name, I think one of user has accidentally put a backslash into their entity name which we used to execute a query, I know this a rather weird use case and might not have been encountered by a lot of the Gem user, but still want to see if this warrant a fix in the Gem or something we need to escaped properly in our own app
