### ISSUE TITLE
Card Processing Fee into Quickbooks Online

### ISSUE THREAD

**Issue by chileap** [ruckus/quickbooks-ruby#350]
Hello there,

Currently I am working with integrating Quickbooks and Magento and I am really thankful for this gem. 

I have a question with creating Card Processing Fee into Quickbook. I wonder if there are any to create this fee into quickbooks.

Card Processing Fee has any model to create it?

**Comment by ruckus** [comment]
Are you referring to creating an invoice and then adding a line-item representing a fee? If so, please have a look at this example in the README:

https://github.com/ruckus/quickbooks-ruby#generating-an-invoice

**Comment by chileap** [comment]
Actually I thought that there are other ways to create Card Processing Fee like tax. But I might just create other line-item like you mentioned.

Anyway thanks for your answer.
