### ISSUE TITLE
`all` returns `nil` rather than empty array for no results

### ISSUE THREAD

**Issue by drewish** [ruckus/quickbooks-ruby#353]
I had some code that looked like:
```rb
records = service(type).all(query)
records.each do |record|
  ...
end
```
It was blowing up with an "NoMethodError: undefined method `each' for nil:NilClass" error.

A little poking shows that `.all` returns `nil` rather than the empty array I'd expect if the query returns no results:
```rb
irb(main):029:0> con.quickbooks.service(:customer).query("select * from customer where id = '-1'")
=> #<Quickbooks::Collection:0x007fb89a1a2638 @count=0, @entries=[]>
irb(main):030:0> con.quickbooks.service(:customer).query("select * from customer where id = '-1'").entries
=> []
irb(main):031:0> con.quickbooks.service(:customer).all("select * from customer where id = '-1'")
=> nil
```

The issue seems to be in the [implementation of `all`](https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/service/service_crud.rb#L15):
```rb
      def all(object_query=nil, options={})
        collection = []
        self.query_in_batches(object_query, options) do |batch|
          collection << batch.entries
        end
        collection.flatten!
      end
```

Looking at the ruby docs, I learned that in addition to modifying the array in place, `flatten!`:
> Returns nil if no modifications were made (i.e., the array contains no subarrays.)
http://ruby-doc.org/core-2.2.0/Array.html#method-i-flatten-21

So I'll open up a PR to change that to `flatten` and provide a less surprising result.

**Comment by drewish** [comment]
I should mention there's an easy work around for the current behavior. I changed my code to:
```rb
records = service(type).all(query) || []
```

**Comment by ruckus** [comment]
@drewish this is/was resolved by your PR that just got merged?

**Comment by drewish** [comment]
Yeah I'm surprised it didn't auto close with the merge.

**Comment by drewish** [comment]
Oh didn't auto close because the duplicate PR was merged
