### ISSUE TITLE
Enhance token renewal example

### ISSUE THREAD

**Issue by drewish** [ruckus/quickbooks-ruby#355]
My first pass at the token renewal code was based off what's in the readme. It assumes an `error_code="0"` so if you hit the `"212"` you'll overwrite valid credentials with nil values. We should add some error handling hints.

There were a couple of other things I'd like to tweak:
- Date computation uses 5 and 6 months but Intuit says the token is valid for 180 days and can be renewed 30 days ahead. I think it'd be better to go of those values rather than the vaguer "months".
- It suggests storing two date fields but you really only need token_expires_at, you can just factor the 30 days into the query to find expiring credentials. 

I'll open up a PR for this next year. Mostly just putting this in as a reminder for myself.

**Comment by ruckus** [comment]
Hi @drewish - firstly thanks for all of your recent contributions and comments! Very much appreciated.

Everything you said above is accurate and would make for great README updates and/or code updates (if needed). 

Thanks again!

**Comment by drewish** [comment]
@ruckus oh you're very welcome! everyone that's contributed has saved me a huge amount of time so I'm happy to return the favor. the PR is up so let me know what you think.
