### ISSUE TITLE
Add typed exception for requests that are too large

### ISSUE THREAD

**Issue by drewish** [ruckus/quickbooks-ruby#361]
Right now if you create a batch that exceeds the byte limit restrictions you'll get a `RuntimeError` which isn't easy to recognize:
```
RuntimeError: HTTP Error Code: 413, Msg: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>413 Request Entity Too Large</title>
</head><body>
<h1>Request Entity Too Large</h1>
The requested resource<br />/v3/company/123145730715194/batch<br />
does not allow request data with POST requests, or the amount of data provided in
the request exceeds the capacity limit.
</body></html>
```
It would be nice if we could turn that into a typed exception that could be matched in a rescue block and divide the batch into smaller chunks.

**Comment by minimul** [comment]
Very interesting. Haven't run into this error yet. Agreed that it should be handled more properly by the gem.

**Comment by drewish** [comment]
Ha you must not have a QA person throwing a couple hundred line items on an invoice ;)

**Comment by drewish** [comment]
I'm having trouble replicating this. When I get really big invoices I'm more likely to hit Net::Http's read timeout. The default 30 seconds seems too low. I'm going to figure out how to bump that up and try again.

**Comment by drewish** [comment]
Took a little digging to figure out how to pass the options through the OAuth gem to `Net::HTTP` so I'll post it here for future Googling. Easiest way is to pass the options in through the initializer
```
$qbo_oauth_consumer = OAuth::Consumer.new(
  Rails.application.secrets.qbo_oauth_key,
  Rails.application.secrets.qbo_oauth_secret,
  {
    site:                  "https://oauth.intuit.com",
    request_token_path:    "/oauth/v1/get_request_token",
    authorize_url:         "https://appcenter.intuit.com/Connect/Begin",
    access_token_path:     "/oauth/v1/get_access_token",
    timeout:               60, # will be used for read and open timeouts
    open_timeout:          30, # sets the open timeout back to the default
  }
)
```

**Comment by drewish** [comment]
I'm going to close this since I'm unable to replicate it even after making some pathological changes.

I've been using this script (calls into some of my wrappers up to) to try and generate a very large batch:
```rb
connection = QBO::QBOConnection.first.quickbooks
item = connection.service(:item).query.first
customer = connection.service(:customer).query.first

Quickbooks.log = true

batch_req = Quickbooks::Model::BatchRequest.new

for i in 0..29
  invoice = Quickbooks::Model::Invoice.new
  invoice.customer_id = customer.id
  invoice.customer_memo = "-=" * 500
  invoice.private_note = "_-" * 2000

  250.times do
    line_item = Quickbooks::Model::InvoiceLineItem.new
    line_item.amount = 50
    line_item.description = "-" * 4000
    line_item.sales_item! do |detail|
      detail.unit_price = 50
      detail.quantity = 1
      detail.item_id = item.id
    end
    invoice.line_items << line_item
  end

  batch_req.add("bId#{i}", invoice, "create")
end

batch_response = connection.service(:batch).make_request(batch_req)
batch_response.response_items.each do |res|
  puts res.bId
  puts res.fault? ? "error" : "success"
end
```

Upping the `timeout` to 90 seconds I was able to send some very big batches but couldn't trigger the error. So unless I start seeing this popping up again I'll assume it was a fluke on the QBO side.

**Comment by minimul** [comment]
Thanks for taking the time to update. Great info.

**Comment by drewish** [comment]
Hum... I got another one of these from our production environment. I'm now wondering if there's a difference between how they handle it with their sandbox and prod companies. I guess I'll have to sign up for a free trial and retry the testing against the production environment.
