### ISSUE TITLE
Posting to Sandbox QB works, regardless of the sandbox setting

### ISSUE THREAD

**Issue by plicjo** [ruckus/quickbooks-ruby#367]
I have a sandbox QB company setup using this gem on my local machine. Whether I have Sandbox set to true or false, it seems to just work regardless.

Is this desired behavior? I expected it to not work when posting sandbox data via the production URL `Quickbooks.sandbox_mode = false`

**Comment by plicjo** [comment]
I opened up a ticket with Quickbooks.

> Hello Joshua, 
> 
> Thanks for reporting this issue. It is a bug in the service side. 
> We've shared all related details with our PD team. It should be fixed in near future(we don't have any ETA for that). 
> 
> We would request you to use sandbox base URL with sandbox companies and production base URL for any trial/production QBO account. 
> 
> We're closing this ticket. If you have any related qts/concern then please reply on this mail thread. 
> 
> Sincerely, 
> 
> Manas Mukherjee 
> Intuit Developer Group 

Currently, it looks like it doesn't matter what mode QB is in. All that matters is whether the API keys are sandbox or production.

**Comment by minimul** [comment]
Yup, this is indeed the case. The URL doesn't matter. If your consumer key and secret are the development ones then the sandbox is used. If using production consumer key and secret then the production API is used.

**Comment by garyfoster** [comment]
Should this option be removed from the Gem and README then?

**Comment by minimul** [comment]
Not yet, they stated that it should be fixed in the "near feature". As unconvincing as that is for an ETA let's give'm them benefit of the doubt and trust that it will be fixed soon.
