### ISSUE TITLE
Question re Connection

### ISSUE THREAD

**Issue by jemagee** [ruckus/quickbooks-ruby#370]
My company has recently started using Quickbooks Enterprise through RightNetworks.  I've found the available for pay plug ins for importing quite lacking.  Will this gem connect to Quickbooks Enterprise accounts?

Didn't see it in the Wiki...thanks

**Comment by ruckus** [comment]
This gem is only used for QB Online. QB Enterprise sounds like QB Desktop. To integrate with QB Desktop you will need to use the Web Connector and communicate via HTTP / SOAP (also called QBXML). See this landing page for further information: https://developer.intuit.com/docs/0200_quickbooks_desktop/0100_essentials/0000_overview

**Comment by jemagee** [comment]
Thank you for the quick response though bummer it doesn’t work -

**Comment by ruckus** [comment]
I've needed to integrate with QB desktop installations from a Ruby/Rails apps and some gems that have proven to be awesome are:

* Qbxml: - https://rubygems.org/gems/qbxml
* WashOut - https://rubygems.org/gems/wash_out

I've also found this blog post to be useful: http://ruckus.tumblr.com/post/88152229186/rails-quickbooks-web-connector-qwc
