### ISSUE TITLE
Quickbooks Authentication with Ruby Script

### ISSUE THREAD

**Issue by chileap** [ruckus/quickbooks-ruby#372]
Hi I have been working with QBO Api and authentication it using ruby script. I have read your document about that but mostly with Rails app. Have you give me some clues with authentication it by ruby script
?

**Comment by minimul** [comment]
No the README examples are in plain ruby.

**Comment by drewish** [comment]
I think the one tricky part of doing a straight ruby script is you'll need to run though the OAuth flow in a more manual way since you won't have a web server to redirect you and then parse the response.
