### ISSUE TITLE
Can't update TaxRate 

### ISSUE THREAD

**Issue by chileap** [ruckus/quickbooks-ruby#373]
Hi

I have implemented updating tax_rate and I saw that it has this feature in here. But I got error while I use. Please take a look with image.

<img width="697" alt="screen shot 2017-04-06 at 5 57 57 pm" src="https://cloud.githubusercontent.com/assets/10094437/24751198/d564aec6-1af2-11e7-9109-85942c3088db.png">

I wonder if anyone could help me with this.

**Comment by ruckus** [comment]
As of this writing the QBO API does not support updating the `TaxRate` entity. 

This `TaxRateService#update` should be updated to raise an exception
