### ISSUE TITLE
Creating a customer with an apostrophe generates "&#39;" instead

### ISSUE THREAD

**Issue by bcackerman** [ruckus/quickbooks-ruby#374]
Hi have a customer `Warrior's` that when created in QuickBooks, creates `Warrior&#39;s`

Is this a bug or something I'm not aware of?

**Comment by minimul** [comment]
Use the [QueryBuilder](https://github.com/ruckus/quickbooks-ruby#query-building--filtering).

**Comment by bcackerman** [comment]
Hi @minimul this is even for creating customers in QuickBooks, not querying for them?

**Comment by minimul** [comment]
Oops. I see. Can you post the logged request.

**Comment by bcackerman** [comment]
Error on my end using Rails `truncate`.  Noted to use `truncate("", escape: false)` going fwd.
