### ISSUE TITLE
Suggestion:  Email discrepancy between Invoice and Sales Receipt

### ISSUE THREAD

**Issue by vanboom** [ruckus/quickbooks-ruby#375]
The billing email address handling is different between sales receipts and invoices:

Invoice uses "billing_email_address = "
Sales receipt uses "email ="

This is a minor inconsistency.  I can offer a PR, but maybe the designers could weigh in on which method would be preferred?

**Comment by ruckus** [comment]
Hi @vanboom - perhaps I am misunderstanding your feedback (thanks for it tho!).

In the Invoice model it is `bill_email`:

https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/model/invoice.rb#L56

And in the SalesReceipt model its also `bill_email`:

https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/model/sales_receipt.rb#L21

Perhaps you are seeing it in another place?

**Comment by vanboom** [comment]
Hi Cody,

I was referring to the helper method that allows us to set the EmailAddress...


Invoice Model:

https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/model/invoice.rb#L85

SalesReceipt Model:
https://github.com/ruckus/quickbooks-ruby/blob/master/lib/quickbooks/model/sales_receipt.rb#L57



________________________________

**Comment by ruckus** [comment]
Oh I see! Yes, I agree that should be consistent. Care to make a PR? We should keep the current setter for backwards compatibility too

**Comment by vanboom** [comment]
Sure, I'll give it a go.  Thanks
