### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by drewish** [ruckus/quickbooks-ruby#378]
It would be great if tags could be added when releases are cut. I'm trying to see what's changed in 0.4.8 and it's definitely harder without out tags.

**Comment by drewish** [comment]
Oh, while looking at https://github.com/ruckus/quickbooks-ruby/compare/v0.4.6...master I just noticed that we've now got a `RELEASE.md` file. So I'll open up a PR to mention tagging the release there ;)

**Comment by drewish** [comment]
I can't tell from [the docs](https://github.com/svenfuchs/gem-release#gem-bump) if it should be tagging and pushing by default now so not sure a PR will help.

**Comment by ruckus** [comment]
hi @drewish I've just cut `0.4.9` and I have tagged it. I will try and be diligent about tagging releases going forward.
