### ISSUE TITLE
ROXML is unmaintained

### ISSUE THREAD

**Issue by plicjo** [ruckus/quickbooks-ruby#386]
This gem is dependent on [ROXML](https://github.com/Empact/roxml), but it hasn't been updated in 5 years.

Ruby 2.4.1 is raising a deprecation warning from inside of the Roxml gem.

```
lib/roxml/definition.rb:156: warning: constant ::Fixnum is deprecated
```

Could the dependency be changed to maintained gems like [Ox](https://github.com/ohler55/ox)?

**Comment by ruckus** [comment]
Its a good question - ROXML is getting long in the teeth.

Perhaps a more long-term approach is to phase out the XML version of this gem in favor of a JSON version which QBO is slowly moving toward anyways.

> Could the dependency be changed to maintained gems like Ox?

Perhaps, but from what I can tell Ox is a generic reader/writer of XML, whereas the use of ROXML is for the conversion of XML to Ruby objects - its a mapping library more than the actual XML parser.

I think the best move is to rewrite this gem using the Representable gem as the workhorse for the XML (and JSON!) serialization:

https://github.com/trailblazer/representable

**Comment by s-mansouri** [comment]
So how long that is take to remove the ROXML? It's great to remove this gem early

**Comment by ruckus** [comment]
@s-mansouri I dont know; I havent had a chance to start researching that task. And I dont know if I will get a chance any time soon. Want to take a crack at it?

**Comment by pusewicz** [comment]
It has just been updated to [version 4.0.0](https://github.com/Empact/roxml/blob/9c6e27c621ed8ff8f030c80fb30ad23333717045/History.txt)

**Comment by plicjo** [comment]
Yeah, it looks like they cleaned house.
