### ISSUE TITLE
OAuth Error: Parameter rejected

### ISSUE THREAD

**Issue by nk-mandilwar** [ruckus/quickbooks-ruby#395]
When I am calling get_request_token method using oauth consumer object, I am getting this exception.
OAuth error: Parameter rejected.
Please fix this. My quickbook sandbox app is using OAuth 2.0

**Comment by drewish** [comment]
Give https://github.com/ruckus/quickbooks-ruby/issues/389 a look. QBO sprung this change with little notice and OAuth 2 support isn't fully ready.

**Comment by nk-mandilwar** [comment]
@drewish Thank you.
When this issue can be fixed?

**Comment by NaumanZahid** [comment]
@drewish also waiting for OAuth 2.0 implementation. It would be huge help for the community.
