### ISSUE TITLE
Error attempting to create customer and/or invoice

### ISSUE THREAD

**Issue by jmore009** [ruckus/quickbooks-ruby#397]
I've been able to successfully connect to QB using oauth2 and the code provided in the 389 branch but when I attempt to create a customer using the oauth1 example methods I get the following error:

`NoMethodError: undefined method `post' for #<String:0x007faa54863de0>`

Is this a result of how the API now creates customers or how the gem works with the updated API?

**Comment by ruckus** [comment]
Are you still experiencing this? I just pulled in the `389-oauth2` branch into my Rails app (which still runs under oauth1) and was able to successfully create a new QB Customer.

**Comment by jmore009** [comment]
@ruckus yes, the issue for me after receiving the access token, when I pass it as such:

`@customer_service.access_token = access_token`

I get this error on customer create:

`ArgumentError: wrong number of arguments (given 3, expected 1..2)`

when I pass just the token part of the response (and not the whole response) I get that other error for undefined method post. I must be doing something wrong. Any ideas?

**Comment by ruckus** [comment]
hi @jmore009 can you please provide more code. what **is** your `access_token` - it should be an instance of `OAuth::AccessToken` or `OAuth2::AccessToken` which you are building from the initial auth flow, ala

https://github.com/ruckus/quickbooks-ruby/blob/389-oauth2/webapp/app.rb#L36

**Comment by jmore009** [comment]
@ruckus this is what my callback looks like:

`oauth_params = {:site => "https://appcenter.intuit.com/connect/oauth2", :authorize_url => "https://appcenter.intuit.com/connect/oauth2", :token_url => "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer"}`
  
`oauth_client = OAuth2::Client.new([my client id], [my secret], oauth_params)`

`resp = oauth_client.auth_code.get_token(params[:code], :redirect_uri => "https://2848d90c.ngrok.io/admin/oauth_callback")`
 `@data = {}`
          `@data[:token] = resp.token`
          `@data[:refresh_token] = resp.refresh_token`
         ` @data[:realmId] = params[:realmId]`
          `token = OAuth2::AccessToken.new(oauth_client, @data[:token])`

and the token variable has the following output:

![image](https://user-images.githubusercontent.com/5374579/32119668-f7ef8c28-bb23-11e7-8667-1a6d49f3a273.png)

`

**Comment by ruckus** [comment]
@jmore009 thanks. do you have a line-number and/or stacktrace for the 

`ArgumentError: wrong number of arguments (given 3, expected 1..2)`

**Comment by jmore009** [comment]
@ruckus (thanks for whiting out that info, didnt look close at). This is the whole process when passing `token.token` 

![image](https://user-images.githubusercontent.com/5374579/32122639-09f109f0-bb2f-11e7-988e-f5c6f7c7e54a.png)

and this is when passing just `token`

![image](https://user-images.githubusercontent.com/5374579/32122654-1338c6ce-bb2f-11e7-98d0-0791cf24134e.png)

**Comment by ruckus** [comment]
@jmore009 try passing the `token` instance object into the QB setter, NOT just the string token property,

e.g instead of

`@customer_service.access_token = token.token`

do

`@customer_service.access_token = token`

**Comment by jmore009** [comment]
@ruckus when I pass in

`@customer_service.access_token = token`

that's when I get the `ArgumentError` (documented in the second screenshot above)

**Comment by ruckus** [comment]
@jmore009 interesting.

I have this command line script to play with the library and its working under OAuth2 to create a customer (see `mode = 3`) - I just successfully created a customer using this.

https://github.com/ruckus/quickbooks-ruby/blob/389-oauth2/webapp/client.rb

**Comment by ruckus** [comment]
@jmore009 

Run it from the root:

```bash
cd quickbooks-ruby
$ ruby webapp/client.rb
...
```

**Comment by MrHubble** [comment]
@jmore009 did the solution in the last comment above work for you? I'm not experiencing this myself, just curious as to whether you were able to resolve it.

**Comment by cupnoodle** [comment]
Hi @ruckus , I managed to reproduce the same error @jmore009  encountered (`ArgumentError: wrong number of arguments (given 3, expected 1..2)`) by creating an invoice using OAuth2.

You can try it with this gist [create_invoice.rb](https://gist.github.com/cupnoodle/fdde7207b2acf4ddddabde6d998c013e)
The error occurs after I call the `service.create`

I am using the branch `389-oauth2`

The error stack trace : 
<img width="682" alt="screen shot 2018-04-17 at 3 21 27 pm" src="https://user-images.githubusercontent.com/3954625/38854753-19325ba6-4254-11e8-92df-27b29ddc2f38.png">

**Comment by ruckus** [comment]
@cupnoodle are you using the latest from the `389-oauth2` branch? I just tried this again and can successfully create an invoice (using your code, albeit with Customer & Item ID differences)
