### ISSUE TITLE
Should we stop queries on non-queryable properties?

### ISSUE THREAD

**Issue by fabrouy** [ruckus/quickbooks-ruby#403]
Right now we can do:
```ruby
service = ::Quickbooks::Service::Vendor.new(company_id: 'xxx', access_token: <access_token_obj>)
vendors = service.find_by("PrimaryEmailAddr", 'john@doe.com')
```
However this raises:
```ruby
Quickbooks::IntuitRequestException: Invalid query:
	QueryValidationError: property 'PrimaryEmailAddr' is not queryable
```

And this is the raw response from Intuit:
```xml
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2017-10-30T13:30:06.485-07:00">
  <Fault type="ValidationFault">
    <Error code="4001">
      <Message>Invalid query</Message>
      <Detail>QueryValidationError: property 'PrimaryEmailAddr' is not queryable</Detail>
    </Error>
  </Fault>
</IntuitResponse>
```

Looking at https://developer.intuit.com/docs/api/accounting/vendor I see PrimaryEmailAddr is not a property we can use to filter (should say `filterable`).

Here's a list of non filterable vendor properties (same non filterable properties could be filterable for instance, customers):
`SyncToken, Title, PrimaryPhone, AlternatePhone, Mobile, Fax, PrimaryEmailAddr, WebAddr, BillAddr, OtherContactInfo, TaxIdentifier, TermRef, Balance, AcctNum, Vendor1099, CurrencyRef, TaxReportingBasis, APAccountRef`.

Maybe this goes over the quickbooks-ruby library scope (as a wrapper).

**Comment by ruckus** [comment]
Personally I dont think its necessary to hold the users hands like this and have to maintain a list of filterable properties (which might or might not change in the future?)

**Comment by fabrouy** [comment]
I agree. Maybe I only add a little note on the README about this.
