### ISSUE TITLE
Is it possible to make a query for fields that are objects?

### ISSUE THREAD

**Issue by marinakap** [ruckus/quickbooks-ruby#405]
I need something like this: 
`@deposit_service.query("SELECT * FROM Deposit WHERE DepositToAccountRef.id='116'")
`
I've seen that kind of query work for the MetaData field, but not anything else. Is there a way?

**Comment by minimul** [comment]
Nope, only `Id` and `TxnDate` can be used in a where clause (called *filterable* in the API docs) for the **Deposit** resource.

You are going to have to bring'em all down and use Ruby to find the `DepositToAccountRef.id` you're looking for. You can use the `TxnDate` to at least make that query result smaller.
