### ISSUE TITLE
Is anyone getting this errors in production?

### ISSUE THREAD

**Issue by fabrouy** [ruckus/quickbooks-ruby#409]
```ruby
Quickbooks::IntuitRequestException: :
	<?xml version="1.0"?>
```
RESPONSE BODY: `<?xml version="1.0"?>`

This started Dec 6, 2017 for me.

They do not happen in the sandbox mode.
And directly in QBO API explorer interfase they pull the same request just fine.

Sandbox log:
```bash
I, [2017-12-08T14:32:34.044886 #13780]  INFO -- : ------ QUICKBOOKS-RUBY REQUEST ------
I, [2017-12-08T14:32:34.044972 #13780]  INFO -- : METHOD = get
I, [2017-12-08T14:32:34.044993 #13780]  INFO -- : RESOURCE = https://sandbox-quickbooks.api.intuit.com/v3/company/xxxxxxxxxx/query?query=SELECT+%2A+FROM+Customer+STARTPOSITION+1+MAXRESULTS+20
I, [2017-12-08T14:32:34.045008 #13780]  INFO -- : REQUEST BODY:
I, [2017-12-08T14:32:34.045026 #13780]  INFO -- : {}
I, [2017-12-08T14:32:34.045069 #13780]  INFO -- : REQUEST HEADERS = {"Content-Type"=>"application/xml", "Accept"=>"application/xml", "Accept-Encoding"=>"gzip, deflate"}
I, [2017-12-08T14:32:39.719075 #13780]  INFO -- : ------ QUICKBOOKS-RUBY RESPONSE ------
I, [2017-12-08T14:32:39.719162 #13780]  INFO -- : RESPONSE CODE = 200
I, [2017-12-08T14:32:39.719191 #13780]  INFO -- : RESPONSE BODY:
I, [2017-12-08T14:32:39.721594 #13780]  INFO -- : <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2017-12-08T09:32:39.278-08:00">
  <QueryResponse startPosition="1" maxResults="20">
    <Customer domain="QBO" sparse="false">
      <Id>1</Id>
      <SyncToken>7</SyncToken>
      <MetaData>
      ...
      Well generated XML
```

Production log:
```bash
I, [2017-12-08T12:31:46.169484 #1464]  INFO -- : ------ QUICKBOOKS-RUBY REQUEST ------
I, [2017-12-08T12:31:46.169605 #1464]  INFO -- : METHOD = get
I, [2017-12-08T12:31:46.169687 #1464]  INFO -- : RESOURCE = https://quickbooks.api.intuit.com/v3/company/xxxxxxxxxx/query?query=SELECT+%2A+FROM+Customer+STARTPOSITION+1+MAXRESULTS+20
I, [2017-12-08T12:31:46.169716 #1464]  INFO -- : REQUEST BODY:
I, [2017-12-08T12:31:46.169746 #1464]  INFO -- : {}
I, [2017-12-08T12:31:46.169789 #1464]  INFO -- : REQUEST HEADERS = {"Content-Type"=>"application/xml", "Accept"=>"application/xml", "Accept-Encoding"=>"gzip, deflate"}
I, [2017-12-08T12:31:46.936385 #1464]  INFO -- : ------ QUICKBOOKS-RUBY RESPONSE ------
I, [2017-12-08T12:31:46.937018 #1464]  INFO -- : RESPONSE CODE = 200
I, [2017-12-08T12:31:46.937391 #1464]  INFO -- : RESPONSE BODY:
I, [2017-12-08T12:31:46.938771 #1464]  INFO -- : <?xml version="1.0"?>
```

It's like an empty or truncated XML. No errors I see.

**Comment by gloubier** [comment]
I've got the same problem since yesterday... I tried to figure out what changed, but didn't find anything...

**Comment by fabrouy** [comment]
@gloubier I'm still having trouble, same for you? I'm running a OAuth2 app.

**Comment by Loubz** [comment]
Yup, still got the problem with a OAuth2 app. I'll probably have some time to try to resolve this problem next week (or one of my colleagues will). 

It's weird because everything was working fine and we didn't change a thing in our code after with put it online. It just broke...

**Comment by gloubier** [comment]
Yup, still got the problem with a OAuth2 app. I'll probably have some time to try to resolve this problem next week (or one of my colleagues will). 

It's weird because everything was working fine and we didn't change a thing in our code after with put it online. It just broke...

**Comment by fabrouy** [comment]
Yes, same for me. I'm having a call with QBO today. Will let you know what comes out of it.

**Comment by ruckus** [comment]
I'm not able to reproduce this from running the Sinatra app under `webapp/` . I can create a new OAuth2 connection; get credentials; and fetch a Customer

**Comment by gloubier** [comment]
I'm getting the error while fetching Invoices and Items... I don't know if that could change something...

**Comment by fabrouy** [comment]
It's working now for me in production env.

What about you @gloubier ?

I'm pretty sure they fixed something on their end, because again haven't changed anything on mine.

**Comment by gloubier** [comment]
Seems to be fixed for me too!

**Comment by fabrouy** [comment]
Closing this :) For real I hope 😂
