### ISSUE TITLE
Adding description line item to invoices

### ISSUE THREAD

**Issue by arifkalayci** [ruckus/quickbooks-ruby#411]
The [documentation](https://developer.intuit.com/docs/api/accounting/invoice) describes a 'Description only' line item type for invoices. However it seems `InvoiceLineItem` does not define that type.

**Comment by marinakap** [comment]
I really need this too. Is there any way to use the description type?

**Comment by ruckus** [comment]
`0.6.1` should be on RubyGems shortly with support for description only line items:

Usage:

```
line_item = Quickbooks::Model::InvoiceLineItem.new
line_item.description = "Plush Baby Doll"
line_item.description_only!
invoice.line_items << line_item
```
