### ISSUE TITLE
Undefined method `plain_body' for #<OAuth2::Response> when downloading PDF in 389-oauth2

### ISSUE THREAD

**Issue by jorgeacaballero** [ruckus/quickbooks-ruby#414]
I have a simple method to get the PDF using this example:

https://github.com/ruckus/quickbooks-ruby/tree/389-oauth2#download-pdf-of-an-invoice-or-salesreceipt

This is the method:

```ruby
def get_invoice_pdf
     # Create Invoice Service
      invoice_service = Quickbooks::Service::Invoice.new
      invoice_service.company_id = current_user.realm_id
      invoice_service.access_token = access_token

      # Fetch invoice
      qbo_invoice = invoice_service.fetch_by_id(@invoice.qbo_id)
      raw_pdf_data = invoice_service.pdf(qbo_invoice)
      send_data raw_pdf_data, :filename => "#{@invoice.consecutive_key}_invoice.pdf"
end
```
The invoice is begin fetch correctly, so an auth problem is out of the table.

I'm getting this exception on this line `raw_pdf_data = invoice_service.pdf(qbo_invoice)`: `undefined method 'plain_body' for #<OAuth2::Response:0x007fb02e860c78>`

Based on intuit documentation https://developer.intuit.com/docs/api/accounting/invoice in the "Get an invoice as PDF" section, it is possible to get it using the mentioned endpoint. 

The line raising the exception is this https://github.com/ruckus/quickbooks-ruby/blob/389-oauth2/lib/quickbooks/service/invoice.rb#L23

But I can't seem to find the reason of this error. Any ideas?

**Comment by ruckus** [comment]
Hi @jorgeacaballero I think see whats happening. This should now be resolved in the HEAD of `389-oauth2`. 

I've also verified this in my command line test script: https://github.com/ruckus/quickbooks-ruby/blob/0361c0c2a1e652bcd981f7dc4380b419c0ce8129/webapp/client.rb#L74

**Comment by jorgeacaballero** [comment]
Hi @ruckus Thanks! It's working great now.

Thanks again!
