### ISSUE TITLE
Support for multiple quickbooks accounts

### ISSUE THREAD

**Issue by jordan-realfoto** [ruckus/quickbooks-ruby#424]
Our current setup requires us to support two separate quickbooks accounts. And when I say account I don't mean the quickbooks Account api but an entirely separate Quickbooks Online account. The oauth setup requires a single secret and key at initialization so I'm guessing this hasn't been implemented or encountered before. Is this a realistic possibility or would it require a major rewrite?

**Comment by whereisciao** [comment]
I've been running a multi-quickbooks rails instance for a few years now. The approach I took was initializing the connection in a model or a plain ruby object. Here is an example pseudo-code for a multi-quickbooks.

`OAUTH_CONSUMER_KEY` and `OAUTH_CONSUMER_SECRET` will remain the same between companies as those values are associated to an Intuit Developers Account. 

```
# Single Company initializes Quickbooks connection upon Rails initialization
# This file is not needed for a multi-instance
# Create config/initializers/quickeebooks.rb
QB_KEY = "<copy from developer.intuit.com>"
QB_SECRET = "<copy from developer.intuit.com>"

$qb_oauth_consumer = OAuth::Consumer.new(QB_KEY, QB_SECRET, {
    :site                 => "https://oauth.intuit.com",
    :request_token_path   => "/oauth/v1/get_request_token",
    :authorize_url        => "https://appcenter.intuit.com/Connect/Begin",
    :access_token_path    => "/oauth/v1/get_access_token"
})


# Multi-Company initialize the Quickbooks connection when the model is needed
# Best to wrap the QBO related functions in a module
# Example Rails Model
OAUTH_CONSUMER_KEY = "OAUTH_CONSUMER_KEY"
OAUTH_CONSUMER_SECRET = "OAUTH_CONSUMER_SECRET"

class Company < ActiveRecord::Base
  # Fields
  # qbo_id
  # token_key
  # token_secret

  def qbo_consumer
    OAuth::Consumer.new(OAUTH_CONSUMER_KEY, OAUTH_CONSUMER_SECRET, {
        :site                 => "https://oauth.intuit.com",
        :request_token_path   => "/oauth/v1/get_request_token",
        :authorize_url        => "https://appcenter.intuit.com/Connect/Begin",
        :access_token_path    => "/oauth/v1/get_access_token"
    })    
  end

  def qbo_access_token
    access_token = OAuth::AccessToken.new(qbo_consumer, token_key, token_secret)
  end
end
```

**Comment by jordan-realfoto** [comment]
@whereisciao thank you so much for the detailed response! It's been so long since I originally set up my quickbooks developer account I forgot that the oauth key was different from the quickbooks access key. I'm using the quickbooks-base gem as well so i have to configure it in my quickbooks module initializer. not sure if there's a more elegant way to achieve this though.

`
  def initialize(type=nil, account_id)
    @account = Account.find_by_id(account_id)
    Quickbooks::Base.configure do |c|
      c.oauth_consumer = @account.qb_consumer
      c.persistent_token = 'qb_access_token'
      c.persistent_secret = 'qb_access_secret'
      c.persistent_company_id = 'qb_company_id'      
    end
    @base = Quickbooks::Base.new(@account, type)
  end
`

**Comment by whereisciao** [comment]
@jordan-realfoto I'm not too familiar with the [quickbooks-ruby-base gem](https://github.com/minimul/quickbooks-ruby-base). I ended up creating by own base class for my needs. Whatever code that is repeating, I recommend finding some way to extract it into a module. 

Here is a sample pseudo-code of what developed:
```
# Common Quickbooks Base code
module ActsAsQboResource
  def acts_as_qbo_resource(settings = {}, &block)
    class_eval do
      # Setup the Quickbooks Connection
      self.qbo_class_name  = settings[:as]
      self.qbo_api_version = settings[:api_version] || :v2

      # Belongs to a company
      company = settings[:company_class] || :company
      belongs_to company,
        :primary_key => 'qbo_id',
        :foreign_key => 'qbo_realm_id'

      # Company is where the OAuth Token Key and Secret is stored
      delegate :name, to: :company, prefix: true, allow_nil: true
    end
  end
end

# Add to ActiveRecord
class ActiveRecord::Base
  extend ActsAsQboResource
end

# Extend by Quickbooks model type
class Account < ActiveRecord::Base
  acts_as_qbo_resource :as => :account
end

class Invoice < ActiveRecord::Base
  acts_as_qbo_resource :as => :invoice
end
```
