### ISSUE TITLE
Taxes issue

### ISSUE THREAD

**Issue by mantgomery** [ruckus/quickbooks-ruby#426]
I am facing the problem with the taxes. 

Our user from Great Britain creates an invoice with 0% tax for goods - 0.0% ECG - EC Goods Zero-rated EGS-ECGS and we are trying to push it on Quickbooks, but it fails all the time. All other 0% taxes are working well. We can't find a reason.

Thanks in advance.

error:
A business validation error has occurred while processing your request:Business Validation Error: We're sorry, QuickBooks encountered an error while calculating tax

**Comment by ruckus** [comment]
Difficult to say if this is a QB API issue or is related to this gem?
