### ISSUE TITLE
Bug using requestid

### ISSUE THREAD

**Issue by bcackerman** [ruckus/quickbooks-ruby#430]
I'm trying to use `requestid` as used here - https://github.com/ruckus/quickbooks-ruby/blob/31119c0eb24b2d3a65d6d14daa7c313b696ae835/spec/lib/quickbooks/service/invoice_spec.rb#L244

But am receiving this error
`System Failure Error: java.lang.NumberFormatException: For input string: "4?requestid"`

Here's my code
`
service.create(qb_category, query: {requestid: category.qb_request_id})
`

Any idea what's going on?

**Comment by bcackerman** [comment]
Here's the URL that's being sent
`https://quickbooks.api.intuit.com/v3/company/123145934922624/item?minorversion=4?requestid=1526534836`

**Comment by ruckus** [comment]
Yeah I can see the problem; the query string parameters should be ampersanded together betweent he `minorversion` and `requestid` parameter except there is a duplicate `?` instead. Let me work on an update

**Comment by ruckus** [comment]
Resolved with `0.6.2` release

**Comment by bcackerman** [comment]
Thank you @ruckus!
