### ISSUE TITLE
IntuitRequestException thrown when querying using boolean value

### ISSUE THREAD

**Issue by john-goldsmith** [ruckus/quickbooks-ruby#439]
When using the [`Service#find_by`](https://github.com/ruckus/quickbooks-ruby/blob/4d788fbc9bf49cd849199b12a667dc3cce4c20cf/lib/quickbooks/service/service_crud.rb#L28-L34) method, it appears that passing a boolean value results in `IntuitRequestException` being thrown.  I'm pretty sure this is due to the single quotes found in the string interpolation.

Throws:

```ruby
Quickbooks::Service::Employee.new({company_id: "...", access_token: "..."}).find_by(:active, true)
# => Quickbooks::IntuitRequestException: An application error has occurred while processing your request: System Failure Error: java.lang.String cannot be cast to java.lang.Boolean
```

Throws (note the single quotes):

```ruby
Quickbooks::Service::Employee.new({company_id: "...", access_token: "..."}).query("select * from employee where Active = 'true'")
# => Quickbooks::IntuitRequestException: An application error has occurred while processing your request: System Failure Error: java.lang.String cannot be cast to java.lang.Boolean
```

Works (note the lack of single quotes):

```ruby
Quickbooks::Service::Employee.new({company_id: "...", access_token: "..."}).query("select * from employee where active = true")
```

**Comment by ruckus** [comment]
Interesting; thanks for the heads up. I guess we could introspect the class query value and if its `TrueClass` or `FalseClass` then dont surround it with single-quotes; for all others then continue to single-quote it.. ?

**Comment by jaredmoody** [comment]
I took a stab at fixing this in the PR, LMK your thoughts/if you would like something done differently!
