### ISSUE TITLE
Getting BookCloseDate

### ISSUE THREAD

**Issue by marinakap** [ruckus/quickbooks-ruby#442]
Hello, I would like to get the BookCloseDate property that's supposed to be under AccountingInfoPrefs in the Preferences object.

Quickbooks documentation says it needs minor version 21.

Is this possible to do currently?

**Comment by ruckus** [comment]
I've just released `0.6.3` with support for Preferences / minorversion=21. 

When you perform a `query` on the Preferences service object you should get back the updated payload.
