### ISSUE TITLE
Version 0.6.3 doesn't get installed

### ISSUE THREAD

**Issue by marinakap** [ruckus/quickbooks-ruby#444]
Hello! I'm doing bundle update quickbooks-ruby, and it won't install the new version. Looking at the latest commits here https://github.com/ruckus/quickbooks-ruby/releases, it also doesn't look right.

**Comment by ruckus** [comment]
What version of Ruby are you running?

**Comment by brianhenryhf** [comment]
not sure if it's relevant, but https://github.com/ruckus/quickbooks-ruby/blob/0.6.3/lib/quickbooks/version.rb is still on the old version in that release.

**Comment by marinakap** [comment]
That did the trick! It's working fine now.
