### ISSUE TITLE
What if I won't be having end users access data?

### ISSUE THREAD

**Issue by thehashrocket** [ruckus/quickbooks-ruby#447]
I won't be having people log in to quickbooks or anything. I just need to talk to the api to post customers, invoices, purchase orders for accounting purposes. Our application won't be serving customers. Will I still need to have the client authorize quickbooks? I'm starting to think that I will. What do you think?

**Comment by ruckus** [comment]
AFAIK as I understand yes you will need to authorize your app with QBO even for internal purposes. What I believe you can skip is the technical review; since its not customer facing.

**Comment by thehashrocket** [comment]
I believe your right, after sleeping on it, I think I have an idea how to pursue that route.

I'm using the 389-oauth2 branch for my project, it seems that the minimul website is pretty out of date when it comes to working with oauth2. I'm not even getting the authorization button to appear right now. Do you know of an up to date guide or anything to getting started?

**Comment by ruckus** [comment]
> it seems that the minimul website is pretty out of date when it comes to working with oauth2

Are you referring to the sinatra app in the `webapp` directory?

```bash
$ cd webapp
$ ruby app.rb
```

<img width="343" alt="screen shot 2018-12-21 at 12 01 32 pm" src="https://user-images.githubusercontent.com/320/50361389-3949c280-0518-11e9-89e3-235c463041af.png">

**Comment by thehashrocket** [comment]
oh, no, sorry, I was referring to https://minimul.com/integrating-rails-and-quickbooks-online-via-the-version-3-api-part-1.html

I looked at the update video, too, but it's 2+ years old apparently.

I'm running into a 401 error now. I made it past the `The App you are looking for is not found, please check the locale or App name`, though! So I've got that going for me.

The URL that i'm is making the request when I click the button is : `https://sandbox-quickbooks.api.intuit.com/connect/oauth2?
client_id=Q0ylntW6N9sMcb0gycxF81OfmUmkZjVFMg9OxcfCD0nnEImR96&
redirect_uri=https%3A%2F%2Fwellgistics.local%3A3000%2Femployee_users%2Foauth_callback&
response_type=code&
scope=com.intuit.quickbooks.accounting&
state=3bfd04d70d0b7f296b94a8a5`

I'm not sure what I'm missing. :/

**Comment by thehashrocket** [comment]
Just an addition, The script file I'm using is:

`<script src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js" type="text/javascript"></script>
<script>
    intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: "https://wellgistics.local:3000/employee_users/authenticate"});
</script>
`

**Comment by ruckus** [comment]
Try the frontend code that is in the sinatra webapp example. The layout is here:

https://github.com/ruckus/quickbooks-ruby/blob/389-oauth2/webapp/views/layout.erb

The webapp example has a `datasources` object

**Comment by thehashrocket** [comment]
I ended up going here: https://github.com/IntuitDeveloper/OAuth2_RubyOnRails and rolled my own and it worked right away. I think the url endpoints are different. It looks like the gem is going here: https://sandbox-quickbooks.api.intuit.com/connect/oauth2 which results in a 401 error, but if I go to https://sandbox-quickbooks.api.intuit.com/connect/oauth2/v3 then it works.
