### ISSUE TITLE
Considering update rspec dependency to current version?

### ISSUE THREAD

**Issue by wayne5540** [ruckus/quickbooks-ruby#454]
We are using `2.14.1` now, the latest version is `3.8.0`, are you considering update it to current version, it will break some tests because of removed syntax like `its` and `be_false`, but they are easy to fix. Happy to help.

Reference: https://github.com/ruckus/quickbooks-ruby/pull/453

**Comment by drewish** [comment]
I like the idea so I opened up https://github.com/ruckus/quickbooks-ruby/pull/494 to start working on this.
