### ISSUE TITLE
Bundled Items in SalesReceipt Creation

### ISSUE THREAD

**Issue by msalo3** [ruckus/quickbooks-ruby#464]
Is there a way to create a sales receipt containing a bundled item?

I can achieve this when creating an invoice, but I get the error `NoMethodError - undefined method group_line_detail!' for #<Quickbooks::Model::Line:0x0055abebb97598>`  when attempting the same with a sales receipt. That makes sense as there isn't a group line detail option in the Line model.

Am I missing something or is this functionality not yet available?

**Comment by ruckus** [comment]
Hi @msalo3 thanks for the heads up. You're right, the `Line` class should support a `GroupLineDetail`.

The pickle I'm running into is when I add support for `group_line_detail` to `line` I get a circular dependency issue.

`GroupLineDetail` references `Line` and vice-versa.

I've tried various require / require_relative statements but I cannot seem to get around this.

Any ideas? Are you more knowledgeable in dependency inclusion?

https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/salesreceipt

**Comment by gorandev** [comment]
Hi! I work with @msalo3 and I've tried to solve this, with no success.

I've gotten as far as modifying a spec and being able to add GroupLine items, but I'm not sure I understood the whole issue.

Still, @ruckus, if you have the time to take a look, it would be much appreciated! My fork and branch are here (https://github.com/flowlink/quickbooks-ruby/tree/feature/group-line-detail) and if you compare to your `master` branch you'll see the changes.

Thanks for all your work on this gem!

**Comment by gorandev** [comment]
I think I fixed this! Check out the PR: https://github.com/ruckus/quickbooks-ruby/pull/478
