### ISSUE TITLE
Quickbooks::IntuitRequestException: Error parsing query

### ISSUE THREAD

**Issue by rppandi** [ruckus/quickbooks-ruby#471]
Hi There,

Thanks for building the quickbooks-ruby. It was awesome.

I have a little parsing error while fetching the vendor from quickbooks.
the company name and display name both are contains single quote. How do i handle this in 
quickbooks-ruby.

 service.find_by(:display_name, "Aido's  LLC")

Error message shows
Quickbooks::IntuitRequestException: Error parsing query:
	QueryParserError: Encountered " <IDENTIFIER> "s "" at line 1, column 48.
Was expecting one of:
    <EOF> 
    <AND> ...
    "iterator" ...
    "maxresults" ...
    <OR> ...
    "order" ...
    "orderby" ...
    "startposition" ..

**Comment by ruckus** [comment]
Have a look at the query building interface to properly escape input:

https://github.com/ruckus/quickbooks-ruby#query-building--filtering

**Comment by rppandi** [comment]
Thank you.

**Comment by legacy370** [comment]
I'm glad your code is so readable.  My query was bombing on something like O'Keefe.  Since I already had
`@customer_service.find_by(:display_name, family.formal_name)`

I used the code in your utility class to replace it with

```
escaped_name = family.formal_name.gsub("'", "\\\\'")
@customer_service.find_by(:display_name, escaped_name)
```
