### ISSUE TITLE
Looks like BigDecimal is being deprecated

### ISSUE THREAD

**Issue by henrytseng** [ruckus/quickbooks-ruby#472]
Looks like we'll need to upgrade `roxml` gem since BigDecimal will be deprecated

```
/usr/local/bundle/gems/roxml-4.0.0/lib/roxml/definition.rb:179: warning: BigDecimal.new is deprecated; use BigDecimal() method instead.
```

**Comment by andjosh** [comment]
It has been merged into roxml (https://github.com/Empact/roxml/pull/62) but not yet released (https://github.com/Empact/roxml/issues/64)

**Comment by jacobjlevine** [comment]
@andjosh considering a new version of the gem hasn't been published since that fix was merged into master 18 months ago, is it possible to tie this gem to the latest commit of roxml? Or are there other options available for enabling forward movement?

**Comment by jacobjlevine** [comment]
Also, in case anyone else visits this issue because they're trying to move to Ruby 2.7, I added this to my Gemfile and it seems to have fixed the issue for now.

`gem 'roxml', github: 'Empact/roxml', ref: '0d6fd8e'`
