### ISSUE TITLE
Unable to use allow_ipn_payment?  on invoice

### ISSUE THREAD

**Issue by ponnuchamy51** [ruckus/quickbooks-ruby#474]
Unable to create invoice with **allow_online_ach_payment** this option.
For this i am getting syntax error while using

invoice.allow_online_ach_payment? = true

i am using 389 branch

syntax error, unexpected '='

For THIS
      invoice =  Quickbooks::Service::Invoice.new
      **invoice.allow_online_ach_payment? = true**

**Comment by ruckus** [comment]
You should be setting that method on the model, not the service object.

So instead of:

```ruby
invoice = Quickbooks::Service::Invoice.new
invoice.allow_online_ach_payment? = true
```

Try this:

```ruby
invoice = Quickbooks::Model::Invoice.new
invoice.allow_online_ach_payment = true # notice the writer does not have '?'
```
