### ISSUE TITLE
v0.6.7 missing commits

### ISSUE THREAD

**Issue by Zajn** [ruckus/quickbooks-ruby#475]
Hi all! Our dependency bot created a pull request for the version bump from v0.6.6 --> v0.6.7, but it looks like 2 of the commits aren't in any branches in the repository. 

The commits were listed as:
<summary>Commits</summary>

- [`bba7162`](https://github.com/ruckus/quickbooks-ruby/commit/bba7162b7c9fe4b42846d9976bb311c8a638416a) Release of 0.6.7 with CustomField support for Preferences and Items
- [`fc3edff`](https://github.com/ruckus/quickbooks-ruby/commit/fc3edff35baf588a8729a0978be832e9ca4931ee) * Implemented minorversion support for Customer (at 33)
- [`b3b7423`](https://github.com/ruckus/quickbooks-ruby/commit/b3b742389c438351f0826013e128ba706f1ed41c) exposing time attribute from response received via CDC endpoint ([#468](https://github-redirect.dependabot.com/ruckus/quickbooks-ruby/issues/468))
- [`d148a5f`](https://github.com/ruckus/quickbooks-ruby/commit/d148a5f6cf3e4d2eea41021bdc7d6e2fdde0d70e) Preferences sales_forms_prefs CustomField support ([#465](https://github-redirect.dependabot.com/ruckus/quickbooks-ruby/issues/465))
- [`86326f6`](https://github.com/ruckus/quickbooks-ruby/commit/86326f68574d7338d3be75b4bcf9793603f9f2f1) log response headers.   Most interesting is the Intuit TID, which ([#456](https://github-redirect.dependabot.com/ruckus/quickbooks-ruby/issues/456))
- [`a0323b0`](https://github.com/ruckus/quickbooks-ruby/commit/a0323b07f020112614798bc21c3f31e7386bb065) Update HISTORY.md ([#457](https://github-redirect.dependabot.com/ruckus/quickbooks-ruby/issues/457))
- See full diff in [compare view](https://github.com/ruckus/quickbooks-ruby/compare/v0.6.6...0.6.7)
</details>

I couldn't find bba7162 or fc3edff anywhere.
I created this little ruby script to find what branches contain the commits:

```ruby
# frozen_string_literal: true

require 'pp'

class FindCommits
  attr_reader :commits

  def initialize(commits)
    @commits = commits
  end

  def find_in_branch
    results = {}
    command = 'git branch -a --contains'
    puts "Running #{command}"
    commits.each do |sha|
      results[sha] = `#{command} #{sha}`
    end

    pp results
  end
end

FindCommits.new(ARGV).find_in_branch
```

Running this resulted in:

```
$  ruby ./commits.rb bba7162 fc3edff b3b7423 d148a5f 86326f6 a0323b0     
Running git branch -a --contains
{"bba7162"=>"",
 "fc3edff"=>"",
 "b3b7423"=>
  "* master\n" +
  "  remotes/origin/HEAD -> origin/master\n" +
  "  remotes/origin/master\n",
 "d148a5f"=>
  "* master\n" +
  "  remotes/origin/HEAD -> origin/master\n" +
  "  remotes/origin/master\n",
 "86326f6"=>
  "* master\n" +
  "  remotes/origin/HEAD -> origin/master\n" +
  "  remotes/origin/master\n",
 "a0323b0"=>
  "* master\n" +
  "  remotes/origin/HEAD -> origin/master\n" +
  "  remotes/origin/master\n"}
```

The output is a little messy, but as you can see, bba7162 and fc3edff weren't found in any remote or local branches.

I can check out the `0.6.7` tag and see the commits there. I wasn't sure if this was just a git workflow I was unfamiliar with or if these "missing" commits would actually become a problem.

**Comment by ruckus** [comment]
Hi Zach, thank you for the heads up. I had neglected to push my local changes upstream. But they were contained in the 0.6.7 released gem as you noticed.

I just pushed and those commits are now in `master`. Thanks for the heads up.
