### ISSUE TITLE
Undefined method `alias_attribute' for file "lib/quickbooks/model/sales_receipt.rb:51"

### ISSUE THREAD

**Issue by francismf** [ruckus/quickbooks-ruby#480]
Cant able to require quickbooks-ruby , encountered with the following error 
undefined method `alias_attribute' for #<Class:0x0000000005209540>
  Did you mean?  class_attribute
# /usr/local/rvm/gems/ruby-2.5.1/gems/quickbooks-ruby-0.6.7/lib/quickbooks/model/sales_receipt.rb:51:in `<class:SalesReceipt>'
# /usr/local/rvm/gems/ruby-2.5.1/gems/quickbooks-ruby-0.6.7/lib/quickbooks/model/sales_receipt.rb:3:in `<module:Model>'
# /usr/local/rvm/gems/ruby-2.5.1/gems/quickbooks-ruby-0.6.7/lib/quickbooks/model/sales_receipt.rb:2:in `<module:Quickbooks>'
# /usr/local/rvm/gems/ruby-2.5.1/gems/quickbooks-ruby-0.6.7/lib/quickbooks/model/sales_receipt.rb:1:in

**Comment by ruckus** [comment]
I'm not able to reproduce this when running the test specs. I switched to Ruby 2.5.1 which you are using and the test suite runs green.

Whats the output from `gem env`?

**Comment by A-Scott-Rowe** [comment]
I got this same error when running with a ruby version where rails was not installed. `gem install rails` or including it in your Gemfile may fix this.

**Comment by drewish** [comment]
API docs make it seem like it's part of ActiveModel which is one of this gem's dependencies https://api.rubyonrails.org/classes/ActiveModel/AttributeMethods/ClassMethods.html#method-i-alias_attribute
