### ISSUE TITLE
What is OAUTH_CONSUMER_KEY?

### ISSUE THREAD

**Issue by aura-software** [ruckus/quickbooks-ruby#496]
Trying to port my App to oauth2. 

In the README.md it says set up your OAUTH_CONSUMER_KEY and OAUTH_CONSUMER_SECRET. What are those? In QBO developer they have "client ID" and "client secret". Can't really find anything on the interwebs that uses this nomenclature.....

**Comment by aura-software** [comment]
Docs also say "grantUrl above" .... but there is no grantUrl above :)

**Comment by ruckus** [comment]
Thanks for the heads up, yes the README was using mis-leading variable names. I have updated the README. 

The names are Client ID and Client Secret.

The `grantUrl` is your own endpoint that initializes the OAuth system and redirects the user to Intuit for authentication.
