### ISSUE TITLE
Adding dedicated shipping item to the invoice

### ISSUE THREAD

**Issue by designscience** [ruckus/quickbooks-ruby#504]
Loving this gem but I'm having trouble figuring out how to fill in the dedicated Shipping field in an invoice using quickbooks-ruby. Of course, a basic line-item could be added but I'm most interested in filling the dedicated shipping field provided by QBO (please see attached image). I was not successful finding an example for this in the API explorer. 

![Screen Shot 2020-01-31 at 1 26 38 PM](https://user-images.githubusercontent.com/880096/73575668-87283e00-442d-11ea-952c-f1f365ade3ce.png)

One hint that this is possible was a PHP example forwarded by a colleague (source unknown).
```
// And a shipping charge
$ShippingLine = new QuickBooks_Object_Invoice_ShippingLine();
$ShippingLine->setAmount($data['shipping_amount']);
$Invoice->addShippingLine($ShippingLine);

```
Any thoughts or hints on how to do this with this gem would be most helpful. Thank you!

**Comment by ruckus** [comment]
Huh, interesting. This is the first time I've seen a shipping cost field. I'm looking at the docs for the Invoice object and nothing is jumping out:

https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice

By looking at the source code to the Quickbooks PHP library at:

https://github.com/consolibyte/quickbooks-php

It **appears** that PHP line is for QB Desktop integration and not for QB Online.

I would open a Support Ticket with QBO support and ask them if this field is available via the API (perhaps its undocumented?). If it is available let us know and we can add support for it.

**Comment by gbkane** [comment]
It's not super well documented by Intuit (I've only seen it in the examples), but you need to send 'SHIPPING_ITEM_ID' as the ItemRef to apply shipping to that field on an invoice.

You can do something like this
```
shipping_line = Quickbooks::Model::InvoiceLineItem.new
shipping_line.sales_item! do |detail|
  detail.item_ref = Quickbooks::Model::BaseReference.new('SHIPPING_ITEM_ID')
  ...
end 
```

**Comment by ruckus** [comment]
Thanks @gbkane it sounds like your solution can solve the OPs issue.

**Comment by Diego-Gomez17** [comment]
I have the same problem. How can I fix it? I created the shipping type item, but it still won't accept it.

**Comment by ruckus** [comment]
Wouldn't `SHIPPING_ITEM_ID` in the comment https://github.com/ruckus/quickbooks-ruby/issues/504#issuecomment-594110515 need to be a constant referencing the actual Item ID? And not a single-quoted string value?
