### ISSUE TITLE
missing ClassRef in Item

### ISSUE THREAD

**Issue by gregdymek** [ruckus/quickbooks-ruby#519]
hi,
is there a way we can get ClassRef from Item?
it's documented here: https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/item
but there is no attr_accessor in quickbooks-ruby,
many thanks,
Greg

**Comment by ruckus** [comment]
@gregdymek I released `1.0.8` with support for `Item#ClassRef` which itself is available via minorversion `41`. Please have a look

**Comment by gregdymek** [comment]
wow, what a speed, many thanks
