### ISSUE TITLE
Feature ClassRef not supported with minor version: null, please use minor version: 41 or above

### ISSUE THREAD

**Issue by gregdymek** [ruckus/quickbooks-ruby#522]
on POST
http://sandbox-quickbooks.api.intuit.com:443/v3/company/XXX/item
it looks like we're not sending minor version on service item,
looking at the code we only append minorversion for url_for_query shouldn't we also send it in other methods?
it stopped working ~ a week ago

**Comment by gregdymek** [comment]
hey @ruckus, we are little blocked here, any chance you can release it soon?

**Comment by ruckus** [comment]
Hi @gregdymek - gotcha. Before I release the gem it would be great if you could test it. Are you in a position to give this branch a whirl:

https://github.com/ruckus/quickbooks-ruby/tree/global-minorversion

Thanks!

**Comment by gregdymek** [comment]
hi @ruckus - so far everything is working for us

**Comment by ruckus** [comment]
@gregdymek great I have just released `1.0.11`

https://github.com/ruckus/quickbooks-ruby/commit/3c68b685e963195970ab67f27f34503bc1000d7b
