### ISSUE TITLE
Update roxml gem dependency for Ruby 2.7 support

### ISSUE THREAD

**Issue by jacobjlevine** [ruckus/quickbooks-ruby#523]
roxml v 4.1.0 was just released with fixes to address a deprecation warning from Ruby 2.6 and related breaking change in Ruby 2.7.

**Comment by pjrashidi** [comment]
@jacobjlevine Woohoo, nice catch! But actually...I don't know what is required to safely make this update without breaking things for people... I'm pretty new to ruby and contributing to open source projects like this one

**Comment by ruckus** [comment]
This should be resolved by #524 which was just merged in! :)

**Comment by jacobjlevine** [comment]
Thanks, @rmacklin for your work on this!

@ruckus thanks for your attention on this as well. What're you thinking in terms of publishing a new version of the gem?

**Comment by rmacklin** [comment]
1.0.10 has been released: https://rubygems.org/gems/quickbooks-ruby/versions/1.0.10
