### ISSUE TITLE
Purchase object always return "Invalid account type: You need to select a different type of account for this transaction."

### ISSUE THREAD

**Issue by carlosbrb** [ruckus/quickbooks-ruby#532]
Hey. I'm having an issue with purchases. Every time I try to create a purchase I get an "Invalid account type" from server (sandbox mode). Below is the Purchase object I'm trying:

`=> #<Quickbooks::Model::Purchase global_tax_calculation: nil, id: nil, sync_token: nil, meta_data: nil, doc_number: nil, txn_date: nil, private_note: nil, line_items: [#<Quickbooks::Model::PurchaseLineItem id: nil, line_num: nil, description: TFC Application Fee, amount: 40, detail_type: AccountBasedExpenseLineDetail, received: nil, account_based_expense_line_detail: {"customer_ref"=>nil, "class_ref"=>nil, "account_ref"=>{"name"=>"Meals and Entertainment", "value"=>"13", "type"=>nil}, "billable_status"=>nil, "tax_amount"=>nil, "tax_code_ref"=>nil}, item_based_expense_line_detail: nil, group_line_detail: nil>], account_ref: {"value"=>"42", "name"=>"Visa"}, txn_tax_detail: nil, payment_type: CreditCard, entity_ref: nil, remit_to_address: nil, total: nil, print_status: nil, department_ref: nil, currency_ref: nil, exchange_rate: nil, linked_transactions: [], credit?: nil>`

The error is coming from the Line item (AccountBasedExpenseLineDetail). The account id is fine. I'm missing something or doing wrong something? 

The full error message is:

Quickbooks::IntuitRequestException: Invalid account type used:
        Invalid account type: You need to select a different type of account for this transaction.
from /home/carlos/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/quickbooks-ruby-1.0.12/lib/quickbooks/service/base_service.rb:407:in `parse_and_raise_exception'

**Comment by ruckus** [comment]
Can you post the client building code please?

**Comment by carlosbrb** [comment]
sure:

```ruby
purchase = Quickbooks::Model::Purchase.new
purchase.payment_type = 'CreditCard'
purchase.account_ref = {"value"=>"42", "name"=>"Visa"}
purchase_item = Quickbooks::Model::PurchaseLineItem.new
purchase_item.detail_type=Quickbooks::Model::PurchaseLineItem::ACCOUNT_BASED_EXPENSE_LINE_DETAIL
purchase_item.account_based_expense! do |a|
  a.account_id=13
end
purchase.line_items << purchase_item


```

**Comment by ruckus** [comment]
@carlosbrb I think the issue is with this line:

`purchase.account_ref = {"value"=>"42", "name"=>"Visa"}`

Since its a reference [setter] you should use the `account_id = ` pattern:

https://github.com/ruckus/quickbooks-ruby#reference-setters

So try updating it to this:

`payment.account_id = 42`

and give that a try.

**Comment by carlosbrb** [comment]
@ruckus it worked. You rock man, thanks! Closing the issue.
