### ISSUE TITLE
BillRate attribute not included in Quickbooks::Model::Vendor.rb

### ISSUE THREAD

**Issue by themudassarhassan** [ruckus/quickbooks-ruby#535]
I need bill_rate attribute in my application via QB API. Calling API for getting vendors from QB API is not giving the bill_rate attribute. Going through the code I found that this attribute is not included in the Vendor Model file.

**Comment by ruckus** [comment]
Thanks for the report. I just pushed version `1.0.14` with `Vendor#BillRate` support

**Comment by themudassarhassan** [comment]
Yeah I worked like a charm. Thank you so much!
