### ISSUE TITLE
Having trouble with apostrophes in queries

### ISSUE THREAD

**Issue by cwoolum** [ruckus/quickbooks-ruby#54]
I am trying to search a customer with an apostrophe in the name. The query that the query explorer generates is 

Select \* from customer where companyname %3D'mcgee%5C's'

which returns the correct data. The gem generates the following query which fails

Select+*+from+customer+where+companyname+%3D%27mcgee%255C%27s%27

The query builder uses URI.encode_www_form_component to generate the proper encoded string but i think apostrophes need to be ignored.

**Comment by dheerajk3** [comment]
I came across a scenario where I need to query on ITEM for NAME with the Apostrophe. Basically apostrophe can be of two types( apostrophe ’ or Typewriter apostrophe ' ). when we use Typewriter apostrophe every thing seems to be Good, But when I query using normal apostrophe(which is not there in normal keyboard), code seem to break with this Error: "" Invalid content. Lexical error at line 1, column 43.  Encountered: &quot;\u2019&quot; (8217), after : &quot;\'%Fleur&quot;</Detail></Error></Fault></IntuitResponse> ""

This is what I am using to escape Apostrophe:

```sh
Working with ' : 

util = Quickbooks::Util::QueryBuilder.new
clause1 = util.clause("NAME", "LIKE", "%Fleur't")
item_services.query("SELECT * FROM ITEM WHERE #{clause1}")

Not Working ’ :

util = Quickbooks::Util::QueryBuilder.new
clause1 = util.clause("NAME", "LIKE", "%Fleur’t")
item_services.query("SELECT * FROM ITEM WHERE #{clause1}")

```
Is there any fix for these kind of special characters? Thanks
![apostrophe](https://cloud.githubusercontent.com/assets/10532799/12372976/c811fdcc-bc8f-11e5-9d15-b9fab837ea82.png)

**Comment by ruckus** [comment]
Interesting. I dont see any easy solution here. 

I tried replacing curly-quote with straight single-quote hoping that Intuit would recognize them as the same but that didnt yield any results during a query. 

Looks like escaping them like normal also doesnt work - I get the same error you do.

**Comment by vanboom** [comment]
```ruby
    @vendor_service.find_by(:display_name, vendor.name.gsub("'"){"\\'"}).entries.first
```

**Comment by ruckus** [comment]
@vanboom did you try using the `QueryBuilder` utility class?

```ruby
util = Quickbooks::Util::QueryBuilder.new
clause1 = util.clause("NAME", "LIKE", "%Fleur't")
item_services.query("SELECT * FROM ITEM WHERE #{clause1}")
```

**Comment by varun07j** [comment]
It worked me by Escape special characters:
        displayName = displayName.Replace("'", "\\'"); //Escape special characters
        QueryService<Customer> customerQueryService = new QueryService<Customer>(context);
        return customerQueryService.Where(m => m.DisplayName == displayName).FirstOrDefault()
