### ISSUE TITLE
Tags support for invoices

### ISSUE THREAD

**Issue by varun43in** [ruckus/quickbooks-ruby#542]
Hi guys, 

QBO recently implemented ability to add tags when creating invoices.
Will this be added to this gem in the near future?

Thanks as always for your amazing work!

**Comment by ruckus** [comment]
Hi @varun43in this is the first I have heard of invoices & tags, but I also don't follow the latest Intuit / QBO news.

Do you have a link to a reference?

But a PR with tag support would be amazing too 😉   !

**Comment by varun43in** [comment]
Good question!  

I just looked in the Dev docs and tags isn't listed anywhere 
(as a separate entity or a property on Invoices or Sales Receipts)  

So it looks like I totally jumped the gun here, as QBO themselves haven't exposed it yet via the API haha.
