### ISSUE TITLE
Missing IsProject attribute on Customer

### ISSUE THREAD

**Issue by jocekuswanto** [ruckus/quickbooks-ruby#546]
I'm working on adding a project integration with QBO, however I noticed it's missing `IsProject` from the `Customer` model. From the QBO API docs there is a flag to indicate if a customer is a project and I'm able to query it through Postman (only on a production QBO company). 

![Screen Shot 2021-03-08 at 5 20 37 PM](https://user-images.githubusercontent.com/17188323/110404038-fdd13b00-8032-11eb-8de8-53c603046b45.png)

Is there a reason why it's currently not on `Customer` or can I open a PR to add it?

**Comment by ruckus** [comment]
Thanks for the heads-up, I just pushed `1.0.16` with support for `Customer#IsProject`.

Accessible via the `isproject?` inquiry method.

**Comment by jocekuswanto** [comment]
Thank you!
