### ISSUE TITLE
SalesItemLineDetail doesn't provide way to add TaxInclusiveAmt 

### ISSUE THREAD

**Issue by vinayakkatkar** [ruckus/quickbooks-ruby#569]
as per the documentation from official quickbooks API https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/invoice TaxInclusiveAmt is available when minorversion=1 is sent in query parameters. Need support for this in quickbooks-ruby gem.

**Comment by ruckus** [comment]
@vinayakkatkar Thanks for the heads up. I just released version `1.0.19`

Addition of `TaxInclusiveAmt` attribute `Line.SalesItemLineDetail`, `Line.ItemBasedExpenseLineDetail`, and `Line.AccountBasedExpenseLineDetail` line types.

**Comment by vinayakkatkar** [comment]
@ruckus thanks, appreciate the quick response. Will check and let you know if anything else is required
