### ISSUE TITLE
Strange response from email_address.address

### ISSUE THREAD

**Issue by timmyd87** [ruckus/quickbooks-ruby#585]
Hey team, i'm getting an array of [email, mobile and id] when getting all contacts. I'm saving them to my app with

`c.email = (contact.email_address.address if contact.email_address.present?),`

but what's being saved is:

<img width="795" alt="Screen Shot 2022-10-09 at 6 58 40 pm" src="https://user-images.githubusercontent.com/12996091/194744908-2b1f1105-432c-4041-8944-23081d544a5e.png">

(see the values in the [] brackets).

I also reverted to using the raw "primary_email_address.address" but i get the same output.

What's strange to me is using the same method but with 'primary_phone.free_form_number' saves the phone number beautifully.

Am i calling the wrong model to save this? Or could something have changed on Intuit's end?

**Comment by ruckus** [comment]
That is odd. Do you know what the raw XML looks like?

You can [Enable Logging](https://github.com/ruckus/quickbooks-ruby#logging) or use an HTTP Proxy to view the data.

**Comment by timmyd87** [comment]
Thanks @ruckus , Screenshot of XML from logs here:

<img width="415" alt="Screen Shot 2022-10-10 at 2 11 06 pm" src="https://user-images.githubusercontent.com/12996091/194794417-e5ebab76-1d36-4d14-b6e3-afe582036b22.png">

Which looks fine to me, removing '.address' and just saving what's coming back from the gem using contact.email_address - i get:

![Screen Shot 2022-10-10 at 2 16 11 pm](https://user-images.githubusercontent.com/12996091/194794682-cc7ca514-810f-4251-b105-b78b2539a2d5.png)

**Comment by ruckus** [comment]
Try reading `customer.primary_email_address` **not** `contact.email_address`, like

```ruby
c.email = (contact.primary_email_address.address if contact.primary_email_address.present?),
```

I copied and pasted that line above from your message and just noticed the trailing comma `,` .. ? Whats up with that? Could that be doing the multiple assignment?

**Comment by timmyd87** [comment]
It....... it was the comma, i had no idea a simple comma could cause such a fuss, thank you for taking the time to respond @ruckus ... i think it was a hangover from a 'find_or_create_by' action i used previously.
