### ISSUE TITLE
invoice.id appears to return Transaction ID, when it historically returned invoice doc number

### ISSUE THREAD

**Issue by vastolf** [ruckus/quickbooks-ruby#605]
I have a system that stored invoice IDs from Quickbooks in my database.

Previously, when I accessed invoice.id it gave me a number beginning in "1". e.g. `10234`, which actually seems to correspond to what is referred to as the `doc_number` (in some contexts apparently referred to as the referenceNumber). It is the number that displays in the Quickbooks invoice interface:

<img width="1042" alt="Screenshot 2024-02-22 at 12 43 49" src="https://github.com/ruckus/quickbooks-ruby/assets/2312432/c0f34b29-ebd3-45a5-8459-8bd18d3d5f0d">

Around December 14th this changed, and I had not modified my implementation of using invoice.id whatsoever.

Now, it appears to save a number beginning in a "2". This appears to be a transaction ID (`txnId`) which is linked to the invoice (e.g. `29291`)

See below where the invoice # is listed in the header of the page, but the txnId url param is this 29291 number:

<img width="945" alt="Screenshot 2024-02-22 at 12 45 38" src="https://github.com/ruckus/quickbooks-ruby/assets/2312432/1a955e86-d08f-44fb-af85-66c244254838">

I'm not sure if this is related to a change in quickbooks API or this library, though it appears I've been on 2.0.2 for some time.

Essentially, the number that actually stores in my database when calling invoice.id is the number beginning in "2", not the number beginning in "1", since around mid December.

Wondering if anyone else is experiencing this and whether there has potentially been some change to the Quickbooks API that would cause this gem's implementation to be outdated or behave unexpectedly.

**Comment by ruckus** [comment]
I don't know if Intuit made any changes. However, I don't think there is any correlation between the numeric `Invoice.Id` which is the QBO unique identifier and the `Invoice.DocNumber` aka the invoice # which is user-provided / changeable.

Here is the XML result from QBO of a random invoice:

![Zight 2024-02-23 at 8 45 05 AM](https://github.com/ruckus/quickbooks-ruby/assets/320/bdd5bccc-15a7-413f-8fd9-b5b3e507851e)

And in this case yes the `Id` happens to begin with "1" and the invoice # (which is generated by the client) is alphanumeric, but they really have no relation to each other

**Comment by vastolf** [comment]
Strange, it appears my docNumbers are always set to be the invoice #/ID, whereas the ID is actually a txnId instead of an "Invoice ID".

I will close this, but maybe someone can re-open if they're experiencing similar issues.

I just find it strange that my implementation hasn't changed yet what is getting stored has. 

Thanks for your response, if I am able to figure out what happened and what caused it, and I think it'll be useful for others, I will report back here.
