### ISSUE TITLE
Issues with updating :track_quantity_on_hand? field in Item Model

### ISSUE THREAD

**Issue by SunnyIzr** [ruckus/quickbooks-ruby#81]
Hey Guys:

Seeing an issue when trying to update the :track_quantity_on_hand field in the Item. So for instance, if I want to set that particular field to True, and I assign a date value to the :inv_start_date field in addition to assigning a BigDecimal value to the :quantity_on_hand field, and then when I call the .update on the Item Service, I get the below error. I've done a bit of research and I'm thinking this may be an error on QB's side but not completely positive. Has anyone seen this error before?

Quickbooks::IntuitRequestException: An application error has occurred while processing your request:
    System Failure Error: java.lang.NullPointerException
    from /Users/sunnyisrani/.bundler/ruby/1.9.1/quickbooks-ruby-141059e9b88b/lib/quickbooks/service/base_service.rb:258:in `parse_and_raise_exception'
    from /Users/sunnyisrani/.bundler/ruby/1.9.1/quickbooks-ruby-141059e9b88b/lib/quickbooks/service/base_service.rb:243:in`check_response'
    from /Users/sunnyisrani/.bundler/ruby/1.9.1/quickbooks-ruby-141059e9b88b/lib/quickbooks/service/base_service.rb:212:in `do_http'
    from /Users/sunnyisrani/.bundler/ruby/1.9.1/quickbooks-ruby-141059e9b88b/lib/quickbooks/service/base_service.rb:176:in`do_http_post'
    from /Users/sunnyisrani/.bundler/ruby/1.9.1/quickbooks-ruby-141059e9b88b/lib/quickbooks/service/service_crud.rb:47:in `update'
    from (irb):17
    from /Users/sunnyisrani/.rvm/gems/ruby-1.9.3-p448/gems/railties-4.0.0/lib/rails/commands/console.rb:90:in`start'
    from /Users/sunnyisrani/.rvm/gems/ruby-1.9.3-p448/gems/railties-4.0.0/lib/rails/commands/console.rb:9:in `start'
    from /Users/sunnyisrani/.rvm/gems/ruby-1.9.3-p448/gems/railties-4.0.0/lib/rails/commands.rb:64:in`<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in`<main>'

**Comment by theinventor** [comment]
hey all - I'm trying this and getting this error:

```
, 696590], ["body", "A business validation error has occurred while processing your request:\n\tBusiness Validation Error: As of date for initial quantity on hand is required.\n\nA business validation error has occurred while processing your request:\n\tBusiness Validation Error: As of date for initial quantity on hand is required.\n\n

["message", "A business validation error has occurred while processing your request:\n\tBusiness Validation Error: As of date for initial quantity on hand is required."], ["model_type", "Product"], ["request_xml", "<Item>\n  <Name>Troy4-5onhand</Name>\n  <Description>Troy has these on hand!</Description>\n  <Active>true</Active>\n  <Taxable>true</Taxable>\n  <UnitPrice>55.0</UnitPrice>\n  <Type>Inventory</Type>\n  <IncomeAccountRef>79</IncomeAccountRef>\n  <PurchaseCost>44.0</PurchaseCost>\n  <ExpenseAccountRef>80</ExpenseAccountRef>\n  <AssetAccountRef>81</AssetAccountRef>\n  <TrackQtyOnHand>true</TrackQtyOnHand>\n  <QtyOnHand>1.0</QtyOnHand>\n</Item>"], ["updated_at", Mon, 09 Mar 2015 16:10:38 PDT -07:00]]
```

any ideas??

**Comment by theinventor** [comment]
hah.. nevermind.. it was tricking me

its the inv_start_date

working for me too
