### ISSUE TITLE
Hardy Service

### ISSUE THREAD

**Issue by markrickert** [ruckus/quickbooks-ruby#92]
Hey there, so I'm working with this gem heavily now and I'm wondering if it would make sense to implement some kind of "hardy service" like the [`Harvested`](https://github.com/zmoazeni/harvested/blob/master/lib/harvest/hardy_client.rb#L46-L77) gem has... essentially instead of throwing an error when the server rate-limits the calls, it would detect the rate limiting and wait the appropriate amount of time before calling the same request over again.

Thoughts on a mechanism like this?

**Comment by minimul** [comment]
I can't see how we would implement rate-limiting sanely in the service code at this point. 

@markrickert Thanks for detailing the problem and your solution.
